---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-client-secret
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgAVELiFBuA1KBzf5K+8jfpXmysehR5cjgU+s++eLYjMg81viIs9KXucqMOChZVydrEk0FUsETB5peXjBvMAXjpU3VHosF0aHCT5WBl7UqOTR4w1mmb7H3oAWkyjRzhuVWCr/lzwhQLGr+1iWGlVJx0fD2gYpuzVhTNExRR1yUgv/3natZEcU7MlTplaLSD7/N1OmAX5b89Kegdon8LNSpvfFzw4HDxPzrw0LliJ9cUGmnv4eZC5Qiw/OdwtZLjj9cenPZr+VT3ZobKNngw0dGS774ndoSHXe0H8OiLyg2De7Ya0G09VMO7bn6+eCu33MjGt80g7cvfGP4BDJ2+qxmqR0GXqEcC2z+/W9GDewC53FNKg4cYlc4o6myqDw/yHXdKX31O5oDzehUU5YhboCtMiuHWk/Yd1I7gNwU2ZHodu2DvNqTrqt2LetIXOYaBZa5B+0UQNDVddL33rE/ZyWQDz4D3lxUh4U4g9INknGeclxH0AohK6kTF9oBiNk426CZdbpN0yB75LiGxJpwvEKm3R4auyd3t0gHKNt+6Cj/w4fmbKZnp9thd7MgGRKjOdQ9fJEnL1NpOCVFiH00D3kw6uOkuQR8jLA8pA8KHwiM9HXN46NyXQRt4blR5TPIYJpnnF5nmCyWRhEwif8eqo4ocPH2XR39/Yqc0T+9LnTYSnxohIpBbGpqq+LriGWYF/bEaJgdVvkpfatQS7jd7mRYbAiVxMXJSYT4JIGEFuVe/SU7+PaDkZX3CxJHFYYnmpSR4Zc8dMG7lhcyBwqNopby/l
  template:
    metadata:
      name: headscale-oidc-client-secret
      namespace: headscale
