---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-client-secret
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgApoA8PFOg7YJKgABv+FwgC1JxJn/jp7P96Vfm98kglVxP+ccL53vJRAd1lNkE91PqFNTyaGOLxjdulP5pJajXbVbUWuWdAdiWvGdOisSbnqLZdLEKAi9PmvrQO3vw97uutOHqaAijOEpJMrf9xLzdFfT3qomQsVm2U0gIcuNhlFD3r5OvJAPXKp2relfT2Ee/9gSEp75TSvk2KlOQUpdWKrFdYTAbRKT/BWRk915pEloatLf0Y/g1X8CpCwRIQ1FMjn3wpEuxMulmZP/8+ksH4dlYu7qbF0nEIAOom7IT557GQt/+XTq/80VCSB6UtxuhzjBNbPm3FDi65rLFa0jjMAzH1mskqysCS1fE2Xh8RzWl3D4YlY4qANT/MZeJ901NsREw7UQt3MsqfElNcGPI60jnGpY0w36+Wzpi1jp5RuycZZSnx1rd0CqJZ5c133gip19WCPqAAUK8okx4w8qU5f9Wxx+3ySDZ90tXclZ1Zey/XFYfYZQHTr/uICY/ah/SWWjD7YqZZr0ryACtu/BNuDxfB2/M35LAcyyyUYeHodSltGsFCW03NZu9g21T2qAx3+myqw/HwexG5yNg7Kh5n6gjHIQ0W7j2E0W+Nlb+ZvmFRc5u3aBI8qoJYRUcuhODHJKHljYGea7pb0+6wzFyTuQXHDShQumeX85wsF4GO5KAEMi/vqX1TBDUxsAeZcFa5E10z1cwVHLI795l1uxPkZlZ6Pf4ikgPDfrOejLOvNSZWynNc9d9TKz1aBBXLzqR1Ms4al3hipFVdklRNJZ/7
  template:
    metadata:
      name: headscale-oidc-client-secret
      namespace: headscale
