---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-pg-user
  namespace: headscale
spec:
  encryptedData:
    password: AgBLit2HDfHoDr0SDQQomPM4+MUcBAvUjL19FDhIwXqiQoo0fMMZz6EGUgXbRl8koWwy+noSZixCEH+2x1lJziXL0KIWj4/7Z2/W6L9jWXSSq83yMntDVrvfx3fJJgtnaHno/0HUW0mN9hwamJupV6ZSoPNBhvBCgUkGdhyBTBN4RPZY8wtuDwPKg1koqva9q6avekLJ0478DdKG5hlK1MEkyOTW01qaM/uYOv+RI6i+xdcQL0w0kWv0J/5wTSZ/zdDZ5OLOTScqOL+0vDsYjm8mRi33bLCChkQ+0jNMSOYkA2ZBngCzjATNPgAtphM0DGMOCqdsvpvx2fRKimdj0vfMDrC0wxuwqVp5tq0QmVPlGVXShkBSSl4DrMCStU3265PYJ1CSMXHCYyRrYyWbFwm6N2BSf9YQNMe4c9R8cuwkDo83vORPn2q/y0SsOQEgTMIa5Xea4IVsIVGbgG7ncLXzo73RR1Ar+INClg2COftiv4OYUoQLzcVvCA7JXIc6WlRyM3aDu6M3/UETIpNpuCKiVSCELsBLNhsMiUUjKyljM9U/+H6D/f36ee9Kqa4XqP5iDdAn7TMBX8MO70QTMwq9B3Q4XqahZKFWEHPU/s24yD5deNSjK1icZt8WNr8lvmrMFe6rqu8uEDmKVdePl4M561uEXs0c/jv6bCV6VMHvPShch8ECqwUkXlVr2UlTmFRMiQa2b1fmwEsYJSmg+qjR
    username: AgB9ju00SlinM5TCwQHap9znRifxq0KrCQotmHVauK5O948m5jZ0rDaWeUkGqAuhjFucFpLk6gz8ekoeBTUbFNxYtiB/FzoKq+lwLfPdbbUt9fcN9Oe1ri9dHUBDOUaMPHv06VErdxGWe+6Ll8+baKABwwGT7x4WYUFCu8hQ6PEROFbAdXUbi6OHQeAyOQ1kDebGq4hS2H1j0Y5ECiW24zEKSrRBCsCUiurMSxMyCcOPvC86WefQ/IUMagnM7QJHPNxoW/jdQtmXuk5yTGYQdLrhlzvwlYpSlLiBcrUWkC/qngXWH3dN4r0CQUFKWZsrwdt+nKE6Y+wNsxNGdKJ0t6yaNs5NtxFSY4m48XwhgMe+EOsiQxZzyIs7GjoQPrbuZesrNAbd/iMYay+C8AXhnm3jwJ4bdGTVSD9RZiJpjC4qF+9IR3Iex1i5jVYVTrfPlMd4/2Lvf5b9xIoLuJlC0Tt/tsdga7KFWmMB9cvHGIm4i5xQY/9qGkH3sCMdNFggqB8rvSE6qopRlEcKIZz8J6gdqx56QPi3AWheMcEazPp4mYZCkmkfR0AohRA0HwCtXLtaYHQVu0Ii6vVjCdtp/NBDlz/brZZC6I/WJpUnX2iNSWn/f34gCLEdWLEyTZxj1O3fWAsU8hn9TUG3BezzY4WUHUea+KCrWfKdr1YSitQLqV7gv8G+r3HaCM7Qf/tpOIkiIzkaPgsTDoU=
  template:
    metadata:
      name: headscale-pg-user
      namespace: headscale
