---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-s3-secret
  namespace: headscale
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBtnOg7EVDMR4bhD4M4VNXRCnTkT0/ZU0G+1QZl/fW3zHHDBoQRB2fQTJXDwEnw5CQREYdMUgGN79oyltkmYxanPAfGHHE709hh6xFn4IFkV5Ol8GFnhT1ss709BNVIp8uU2uphxSbxQI0TPpivdfo5TO1m+Q6BAWlcqfsQBPYT3Za4u/vlLE157/By+59si2zHGyagC9zzaHD+Vl1N0mOaN5TZyQBeGMcNbSKua9Vtww/ui9p/ikVvUb1ry1V/LxVxTr9QMomXweklsNhqhu74+Opmw+oVPhs6EPoK64Nt2g+bvEc/399IF7+z6oL8zZCL+TNRKvc8lPmhTOv49dlEmssYlPDlBbdg6sPmi3vrcUpGqQoAPbTT1/VJKLCImsfhUMyi6eMaxqrW/3+fBkqFrt8cUCjGahKW64Hx5CgUY84wec2EPRqaBMG31qA9oWakX3Ncl8/tEhJaMK0Q/Tc2cslHOdRgqs3eyMjUC4clMaUY630h1BkdPscjHWnW19RF8987iH58BTDY35c0uZ+3ot812HPRg6SdCJSQuP8wASWjZwmsKO28dMDIRiwxXA0LMY8FBN/48QWfPxTpdtDZj9f2vL8S+CWz1DnX2SDRxh1Zqx6LOGgOXIisr9zRaW0aXESuk2MCPhU8eGtzAWzy1XT9U9wGuULgA68v0kDbL3unFvdpPW9FQNAkN5wfEAf4HpNB2z90eE1NgB8YZPrtaTmGTw==
    SECRET_ACCESS_KEY: AgAepz3ufHUce6GRAdCdP8470l896dyxIXYNaQOw+p4P8OgMwxD0xRH3KUugw7L+4y25hxWa/aN1HumJHfdOJ/Q4zZ0vIZZ4OgIm98F9LdZRtEdBefIzI1/oYdkfPFxZEcDHCBqECA6gOpcsDvlwzqTdhvgfOHPgkj/lk8PfmYJHFSsmZYKjKwGxEufNKfOP1En4nbBK2N/1RjYIlxrdP5EMajUYdGyFSQTDtuyT86mDsf/Dj+YKaN/Z/KJpMvyOTxP6woui0R3nhc5oUyg0eBOz48fSLNRkyGumGGYmHzBP5Xx7YGdjB7KyGmvItxmKNAkEFJrfXsKMMRB7U6f20vXFo7EdidqKcCQkZU/Njuo84EOFnOyej0bRjcVKLzZsRb3pCFRWadZyD3kc+fQmYu81LU3k6Q6u/2XdIe3257nBZJoXiU4yPKY3LqLEi1vmQiz3MVJmBF5jqx4qd/xosjr5Lw4VdRFFA0GJTwWua9sS8bRzoWganXaX1fz6rRaVhUgceSAcvgYkHnWrqYyAK23pqMAaTXFjciF4qTF21aH4pef3/pSPtq4HGsTxsLLxmhtPdk/Ko0pXe20vntfA9I1sYg7eIyUsBpmAnmBiDMrmI+4rwirmOV+8kAfKrdqGrMiWLfd73QYursjlUxdzF4v/4H+LVQzi/4CtLBoKLfl7XRUOS5BYQ+IlJezDbMyIxDvFtX6A4gGHiOA+deM4S2s30C6AGQx51hYisYUMvmDuTYpl9tA6cCdR
  template:
    metadata:
      name: headscale-s3-secret
      namespace: headscale
