---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgBK/UExuomdII9Nxy4X4YeMMI3oxL4K0hjnKjZnBVqOIhFBkvYkaSl7GM8KaStOSKsqqBbpqhT/XeR8DmdkVxUROaCK8KnZx7CsQXpvrW4USsM2huVcRKocyCmVQtZLoZ3DeXNIUzUkNlyMfC6/0Phpcsg255JxHXmLfcQwZo3fH1/rZf5greW3qMarYxSlWEMkNI+2aZi7KS3vypS/y2F+KjR6gAcMxzE4+Psx4nYUS4NjlLeovUTCsgmZEBVe4wIgWULHPfa58ukLL8ZY+NQS54T1xHH2O2GXN4YrAfWd9/tsnoIaaTX7I47wBpOLAr23K7l/rK65gglV5zLysW6pMkxlitbk6NgkIMQHidQ6Tk14v1wupMDHCdzDqr3WeWCz8deA6K+7PBYpKXdpaKjZumK/JcTWeonqpKfr7xBXET2y6tWc72gHeTblqhV57ZSAXJu1ytYYN1SrZo1vqz87MUZ2dMF/UmW4eTkrhkx1+7f4lLoyUUlIfMz2402LHDLaslRJOmFrni5wgTMTc0U29E4fKi0LkswLE1Uh4XRtPmvWslQQ3fsIDG4K+KFAV79/s0g86ihvXn+N99ttEY1yP9hQ1KckChHTdEtpwrwiu7Wr7k2PgnvSlDJSoxG1tldB7WjnwAAVEPFw9MkEjQ6wt6K6MsynYN1KN3eimQlFC4PbtA4qOmIxlpOFnIPUA5nE9ElHiA==
    admin-user: AgBfbkyTWjB1LP4fp8qodRccTXruosgffotqqUgXeKCkWC57JWOPL0D/pvI0J2741L4Vfj1og8nAYvRyalKoJVG+WgsQgeHJodr7onvwpmUaKvyp8XrKfFFHbTNPh1R0p2vPgRraBWH/2KcIr3zAAVyo2RVGOQiitBNTVEEvf+UQQ8xwTHDFDwkkzcjwUAbW0TnHTjS3Q2knxVoOXEU3pRo7LB0BMEBlI/i8JJNYNYvyc7C9CeISCslg+aH42EwRXulvp5QXDFqIhhz6RDmdT4e2oXQym+IjG72Va4TH/ayvdOxHZQSimsTYVIeHLUjP43zE6t+oTjgw2wyZWy7tuOLI07H1Ffj3XLYwsKdbJvNmYhMMaeYZ9DrbV5ZI4cLizWj9IoDEqBG2PMy1ZKYvneUy9cAlLRL5eeWL6AhHOorNJ5rEyH7IkQ+2Lc2AbyJZAlnKJztONTYHSFgplTubA7WyB6IfQlmam76x1E6LGEnZe6UgUaQlLvM1Xk5Sd17cFwrrKeXxxBoTL/I8zGthiX19qsZvVjMR0ba+H81O3g9efd9pmyHRbkhWG+FmfVHaLZX1oH5tlU63kleJepv+/Ty8lKUwN6P1TLz6Zk8yi8FAFOSTJYM2mUSZLNlegYF860Gg0mQIhxypQJaEl8ULULF79c15//ey41r54XVw8fEwk3NXNRRwFHAuw65Q5EDKZOHHgLyDFA==
  template:
    metadata:
      name: kube-prometheus-stack-grafana
      namespace: prometheus
