---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oidc-client-secret
  namespace: open-webui
spec:
  encryptedData:
    client-secret: AgBXUJkhvagDnIJ3Sh7WXfXutvfNELSSWYNmz8ZO/KyScRs3Fh9ryRTIzF1+cd1NpmWyPSZ7YsSN7VWhtK+z65M5S4e+tiwO3HH8E3GQ/ooZfEPmkCqHW0YArfhbYBY5LRBxvRAYKPwbg4mirMaTREdVGtu5a95pfoAhw7kkTPxofEH4BQroxgDd2DpxMzvUuxfK+VvKYV2eNe8qzGLWoEm9JmjOTMxlY+PuZoo/Xn3icJSqhQ5FqVXKIW3YCTODNXvBByPqysx86FpZ4WftjgspyVU0qzKHIPFdPAndIPABICDgc67VdQ6oWrhzlAU2oo1iHFgBKm7wTsKx7Sgp9iTZeO87jEckgMFr+prWBdSsFxljt45hJSsQk7KU1PxjhJrgf8gAthOAo5M8ep4k/J8Wj99Ta7FLbDdt1kKq7NMsspiVv4Uwu0RLTWucZGyaN1QwrvwoueteHKz8E3el225w3i6ktbdkDQe/gRCitToxKu9PDlpCkWcPfqpGp4yzX8c+H7NXCy0PaPrM/rh3Gu6ZJGEZoZgmfrX6+yp99ANPQPQTYJwEdut2NNRsxm2e4SDSLjtwsRFn5pDDhXp2F+jOuv8Ruyc/WbuRoiNgJT2kt8SmT5Ee3DqZ0uAGCbayW2B7CGLDKRsrH+r6rJ6lMz8fK3dPNKFFmTNtN6GUZaCdQ8rf+/i7zeYH4KpL+RetWSbgR7YdFwjYuylaL3seC8GiCJOg7Ke7/SY/emXOmFKWae/vs4MSg0RfYjOEMCkprBnDPjDKRpAJdBB4JN33md/9
  template:
    metadata:
      name: open-webui-oidc-client-secret
      namespace: open-webui
