#!/bin/bash
# Seals the GitLab Runner authentication token and S3 cache credentials.
# Run after GitLab is deployed and a runner has been created in the GitLab UI.
#
# S3 credentials are read from Pulumi config (already set via setPulumiSecrets.sh).
# Only the runner token is prompted — it is generated by GitLab at runtime.
#
# Steps:
#   1. Deploy GitLab first (deployment/apps/gitlab.yaml)
#   2. Create a runner in GitLab UI (Admin > CI/CD > Runners > New instance runner)
#   3. Copy the runner authentication token (glrt-...)
#   4. Run this script
#
# Generates:
#   gitlab-runner-token-sealed.yaml    — Runner auth token
#   gitlab-runner-cache-s3-sealed.yaml — S3 cache credentials
set -euo pipefail

export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
NAMESPACE="gitlab-runner"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
SEAL="${SCRIPT_DIR}/../manageSealedSecrets.sh"

echo "=== GitLab Runner Secret Setup ==="
echo ""

# --- Read S3 credentials from Pulumi config ---
echo "Reading S3 credentials from Pulumi config..."
S3_ACCESS_KEY=$(cd "$REPO_DIR" && pulumi config get hetznerS3AccessKey)
S3_SECRET_KEY=$(cd "$REPO_DIR" && pulumi config get hetznerS3SecretKey)
echo "  S3 access key, S3 secret key: OK"
echo ""

# --- Prompt for runner token (only secret not in Pulumi — generated by GitLab) ---
read -rsp "Runner authentication token (glrt-...): " RUNNER_TOKEN
echo ""

# --- 1. Runner token ---
"$SEAL" "$NAMESPACE" gitlab-runner-token \
  gitlab-runner/gitlab-runner-token-sealed.yaml \
  --from-literal=runner-registration-token="" \
  --from-literal=runner-token="$RUNNER_TOKEN"

# --- 2. S3 cache credentials ---
"$SEAL" "$NAMESPACE" gitlab-runner-cache-s3 \
  gitlab-runner/gitlab-runner-cache-s3-sealed.yaml \
  --from-literal=accessKey="$S3_ACCESS_KEY" \
  --from-literal=secretKey="$S3_SECRET_KEY"

echo ""
echo "Done. Commit these files to git:"
echo "  - gitlab-runner-token-sealed.yaml"
echo "  - gitlab-runner-cache-s3-sealed.yaml"
