---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-client-secret
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgBbGrOZBUOumCh0JL6Kc8bzKvoTjn7udXm/FXvorqlcyZQ2J4LP27n8fDkiaYQsd72zYuW3lVGo8eMG5B39D54HAoPSRq0niUbpKW5ZPOSd4Ojgr3zfL/R3yhdBbupQ0E+dHgsuebZdnDbDPne4arGSbo5eLKpKFGX0mS1OwO6pkA9/Q1M8gsdMJ/7aRyEaFxHCFk8nKs5jTC5tEC8WfhdM4A/OegAXimQZcTbQWiE16AoYeqGODw6UBMagaULIbfKfnqdU6+wLhvuHCbU4B93z1kd6INsO0n/5n+1YEl7Ss8lf1KppD5ePDJTMN8JhSeUdrBqi/uI7K4RbYaycs785yy/rKmh0XQgPOtO2/eNkp1g6E0xfsSqfjZzmTMe/69A5qnMZXiQ5Iv/oPHdhaoT8XC52U6NuhqSu8b2lIxrHIOIHQ4Vr+QuMSokedDclCsweTkcZgOauMgvyNcyYCH3sa1scEG+RXX8FQ+uN52j/PpYrDnim0Iy42pET0IWR/lxFZ72tfXeL2ReHbrjbhTPjv5fkVg76lIv/Al4j+yLSvPMwZZSOuDEo8ne474fa6EG2Jc3wpUZCD4GtpcRbtVIt3eplow4ePIDAkpduRkeiUoi/Jvm+puUc+hu055UoMdTliA87l3/WOXs57qQsjWAtrdJJ/0mRt8uTyA3wltYTw4WKXpuMuQpt0BMaQ5VaLg/dqz5fjbRwvoHsJU7nzaUs6u+2tvDvTZW4HY4WKFKSQw+myZ4ioKG1ARWNUR4h6nFI+4eZE8Q1Lr0I5mcn6PtB
  template:
    metadata:
      name: headscale-oidc-client-secret
      namespace: headscale
