---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-s3-secret
  namespace: headscale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCRbQEha5Gj99A6iGHuucrKo+pEeKArbr3pNA4ZurWvXLiEw3tCSzrJAxS5PJzBLNg2xIceEls30ZjjM8BmM7iuoxLsvr6rXijVHBYK0f8S7e49mURfrpCBAh+8kd/tEweYTjuGb4WvQMt88xAnPgCKqtNB+IUO1NlkxgLNKBXgrnVXvbJFYeXPBZ9atVE+4R5y9mKbE1vHS2Y335AeY3ClJ17DUqNeFiC4HABPZsoOehaK1baaIeeNqQ/u7Kx4Pgy7mzkeqOCviGntvP7547KPGDCRShbEVKtPk2+y1DKTWbMg0KZQZcEL5MbmVzZk3HXQCNoMChqWyTwGdUtQ3Iyqilp/q26Qij6AaOdSPJEEfPu1Z7FWTYXegeKwJ34StTAiKWsdu0VG13plz8YKupmF9csCgvxb3fhb9e76UOxhZgof3H8b6SZVAPC8yXPr76u4RVoelJfI3VBiVvbAQAoLsNn1oidrHR1oYmKre6g/a8n4qFWIwXBEKJXDeohkE3lGjvHRR43bYtV6P3m5u+r8w+/CeEjInz4ZdQB1C/ZcjT6UsUC6BCctm1SFvYcd7dvB/OyRwbwzz7Kv/PQQw1WXByJ0wIBNnjfK3nxG/OuJmNrmPa/AzF7TPlGC8UJIW5DEaTDTGcdNhyH2vmkujtCAWNQUcsKu8p91wt8j+L9Thz1LCpzTEa/FXqUqENP6kOeuVHqJyVXVC4V66cJE0FQbmLp/mA==
    SECRET_ACCESS_KEY: AgBsSA0dSyHs1MaIdRtSTiqTQw+Se6h+gEHoKcvK9Mx/H9e2mp2rypHD6fR00/U1qS6oeECpGArpW5qsg4jL2B0RFoVhKJ6jjWPtqe4JI8d5+KSxxP6QvqcBdKG7DAABmzNfyVFTF3ct9e6AZcaaur63aObs9POBPdiSS0tbeI+vl/1pCGaaFo8xAzyWJLskUFZFWkHy2oVTHEOb7zEclL5w1GJVLl0zYkM+oURDJybJxS8pHWmXzYLJZIg1W7HYt8Lh7v7sA6izKQsfrAMW1pZlf6QuZoFI0BNuLPQlukSzfh+NdhdwCMoVCXtJ4BaboPWyvKfAOl4JbzAYDvDxU/jG91PUXHpvcR6+rQ9L326P2yvl45I9PjFA9AOvVEI0q6gteIM/X+NaU3ozO1uE9krFED/X/q08hJL6KWPPGgDUUPzAwk3lwiLjsrS5qdjkFaKR8iEOyXMGIkCcDAZuwtIhlEv0VwpEUgrd9xQB63YOfA72V5TlIARyLoTuwTUiq/+C3RtTJ1rOxjE25VuAyKYO5f6BLTEhEvs0htKxieLOgPNg+s4q9Gihk1H641IIjeCTajjfliAfjwz03MMd6TjszSXnBshMh3/XwThVGWlT55vds/VUNzVLzY3kKvUIuNYl7K9UyqjC4EkFUzlCRNGCmFJ2CjLwPO2bAErVD4SKALmkf0Df+oGdoOn7+84niUaMIoFVm7LWacrSkNUXC0QaPYhEixd/vfxiGTnJAOggEh9mMgXK/8UK
  template:
    metadata:
      name: headscale-s3-secret
      namespace: headscale
