---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-client-secret
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgBvgL7Zuuc8wjbQdA1W44dhAbeffQrGmeJoPWg21Kkl9rBG409bC//hQNsZ7p4XH65ebVrICnp96GpOvr25Bk4q78LIOzGKTQ4HS2hfm1T8JVuh61u6RY414cea9wqMRb7KiqOh+a07b4TCVcekjOvwz3JmPb6Tn7e2gAg6oKr/lReBuhHrMavX6djhf/TDvTux+ua1RynFZ3JBJuUPnN88XXJfHd2Rizt1R+ufEAbax+b8Nuk/v4/MuD6mnq024/HowZO9mFaG5YpXb+88R8JrW9nJmVgD9L4OvesiOG75AynrrjJLUIEAgo+sGCxPRzCFUe6rmzTv1OyRDqIkiw/mky4sWt+GyVFX38CMETCoDebUuS+HwPISlwOtuYAQscHpEy+Li8Wv4BmT2RB3gVvk1oV/bFsyWpzNMApijRYMT9Fd8JV0+C5FfY+OpcUd7tQtxaXNTAAQuDvAyyeIRSxCLrzp49ISupoOZCshCcWush9j0DBnWuwiRNIK9+V5GTN82aiUEH1s6eFoCd7yXJ7np9PqQe6Ad/QY4s4x629W+yxzzyHqYXZE3Wpthm2M/Txx+gBYJ0PoyYjA1CJBW1WgL7P2nBLHMaFJZzOaO+ObRBrxixMRKLr1IauCGuHu7/67cJp3PysjANk8WQZsrH0XntFRdwz60m707AX/QGoRTZQ30IJuGv3kGiN141uq2pm69TAqpf6QiFgeTlHFws/xpl16sJjSuXPqU6iqSgvtXbH6UfbeId15yFdxJs1r+oVW/z/pj2Ta6lM99k9km1xh
  template:
    metadata:
      name: headscale-oidc-client-secret
      namespace: headscale
