---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-pg-user
  namespace: headscale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAv+z4hfW71pYKIMn98JePJ4Kt232w35RxKTc45atYyeNfg0rFKUSOU1ENo/+RftrN38dj1DASVuWRFfMfbAqXbSgD/+ktzqsuAm0d98nHiSN9WKY3uNqccHZho7enmeTSntfVFogIfGh+zszr/tJzWVA/Tdheruduqmiff9dj06FpGPs7vOfTL/5htAesFeZm56/ORW9L2OU0NRCz43FU/xewAs+mbeGJcoqE9frpR2Q3HtC6y/Nnkyr8HxrP12EMoJFaDaquJtaoLxAFMSVXrH5+GkGlZQvb/lpvYvX6I/rM/xY1bqAPYAdb8DAm18nfWzvaU1jeGalRVtbXxe2D5v8b8HGLtexuVpDqEaQ1CU4rwImibDM17AymGTQ+mM/kKsk72M6QwQQISCLfZo3qZYPK5bPfYYWdKhriU6UnGHl4rds8/snMvvwnk7OGIXOxM5nj4dhaT7UpGuZsLfBYKnzZ5aAAax9UtlkY4Tj4RviqHHhkjpn8H4vTFlSBvS2+eQmJRfyol9Fi65roq/7emO7YNG7wF2lKNUAjvkYSp7h4WQvrhj8ax1Ztih31cUpojXyj0PxvJ5vfubeSLkrlG/9PBRXZHaQYdvNO3FPfYpkGtJgWhzsM9mp1xhjNlR1sxl/7Orx5cw/vr0ILuSIdJPzzMANHkJpZKY8TwcNU9GJUpZYyZXDZS+UsyxHIcumPuA46dwbmtBxbAtpWogQslCH1sA9v4gwsr5YorSHa5CUQ7DowRMLs2zQhjirUVoZc=
    username: AgBYq5tjGDXcq1b5KslqRERAojfTDRkQuu2Kp+34CCAwuacPao/mgH8Y8vbh6b7sG9S9GEFsqT38Uk43TmQiCNcoTIXDWOY213d2NrLB6WzWoj5hhw+bpE4SNwIB/5r6BJSVNkDRCCWhPXuiRctEbUnp8cKC93YeTInXzUEB+ZvqNK9BDkm6nACHQO2wxw56ETlG9+4SnjTCI23M3hEaqaNWrwW0CKuLdYTOVlza847l6HCLCv8h1AnKGSl63AGNxscPu0Zm5m4QaetqD5aU8C3C2d24ME4UrGMOiRv1OoJcrQ+K4iTmOV8qMSx18D5Q0PeabMHY5r7Fx5Lmv4HU29YsiH3NLS+xRHT0jp2aPwMn4vTEu9nz8lm6KBS86uwGhChBJtXZ9TR5UpCCGBtdeElTYOWy9d4tdkfrCEQX0qsekp2ZAU2+iu2Gv2SW53kE0RPwo4NyqNoxG9KIFNfkaTZ9gwuLe00TlFcgS8LR1u7JR9Apw9jidncBCm3hW5Ohkud2OZ/Uv3S78Uiaxoc0EW/H73jdRtZT+Vj6turjl5U7GCvK3RurmiVjEu2f3JGNAXE3Zmmba8aXZCP7nMO/m/4//eH3rbvUzJiB3caq2UKBKWoCn4LHP/k+9lZdUCB663mV4ZWvqOmUyTS1SEuTJGlA0XJ8TTIINsQ+YFdfPDjJKD2dvmFOus/NKiN9kVcap9e8YZ/GoWj8Wzg=
  template:
    metadata:
      name: headscale-pg-user
      namespace: headscale
