---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-s3-secret
  namespace: headscale
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAgNZT+F9ES0zBBczKmSP5osFJMgGBDOdCF96kGxy1K/vgeYLHVEKHQoj0hKa6aAOJbdh5uVAhdk1jjbGeT/l5XdDcSiPJGqJ8SvKKadsrltcqpYvMcDstGHMcqUcGKMJzISgKwNCc/xb0MopqYZXRqrVjU4RIUeClLQb3XTBMv6KykMdqXj6kJ7KraNIxUo43NJ0R2AGc+9Z6nxsEmlw3AX9MlqpQxumDcWlvuFudLTPkAgQr+0COaBi6XQljbUGZBVH5Wmvl1Zqdxe/nOZB2aDIRJG2bZyXvomCrNLI9Z23DT6YKALM99mSttSvgA/fGh08kq44WniZCbTFmuukJnzO/xsON5jIuUxdlkTCFYQSebHcO1CouUMyFjrXexC5buudYykQ6wbdmCNCJMVWSFCcerERBgJnDqqOnXb3Vsqgt1t2NBme9fclekgTYIbqBm1ZDZLsQAMlihCCffXQOw6UrbPbK0ky+wl5uE7LCE0/qguQ59E4lV197sxDPMTHCxcqHj4Qg/RdNGGK2LI/YJMTjteLQyv1wBRvQIJWkNazBtSk4Y7MFD0IcPtD/zd0lfkpwOG4urLk/puQgzQK8IwCobSCFtVNjH+ldSe9btFpeFLBx8KUcIViTcsYXlUQ/v75/Rzjd6AVV1hvjNvY+LIqwnQ7pOhbDRaD/vyOO0Hu2Otpf1ir7w8hBPJcMybUB6M/SWTJwIKw54EzZFGYAJzluhwA==
    SECRET_ACCESS_KEY: AgBqBeW7UZyHfKajtbFOKiP4+qu2aE6C4x1ydrljTJrAh5uX1bXVT36VMY+WW57Hhf1A8HwO1qouNE98Nf/zMR++0lSwfb9UT2GaivtRIg0F0vHhVd0+70wKRinp9mHFD/JCPSWSbGYe9zd0s2Pnk42HHRGPEhUxhSTI6DfxVd6N5aKFvkjw1vhQFax8KR8wMJP421X3DGeGKuBjYapMdaSLNMXNiNFQwikwHs5e8Bfal0AGHShtj9YuqvOwXnCwKu0mXSgdF54p64e/iaF826SDLZAjfKIUFe5TRcCIlvDJrBx8ncJD5OuQ6RScWDwxiIjsLGDMK4Y8AmEMY3BZjpGmGWzRZwHCSQqdtyvjlNnGwfD/7hTPtwSE8vc2e85QUi0aFTP2OUOonA/TSkEZsfYFpM53e+yhO4yKB1TT4BNN9megNec7JG9PO6S436rHglQNDpZ+5aDHd3ksSDSeTfyk0ORfNzykycB2cvADP2ztmKH0iYjvn7z/1awAcRsfj/1vW5mD9XknQWAEtGS6Ln+ZMFso9Pc24Qc5mGGnvqZwt01oKKzrzP/ATLEVNosD6EZBJbiVIik/3LiKnVmafSXZNlcotuD7Cufj2v/6+4bD1sM/2Xco+DdvJIJcnxyxL0+k6tr1wpzV3SALNHPG/87BrRNHTCn2qzV68snL5PlqSmb5mOMjDH7PC1R6xv5d8lUYmdG3YXa95FJ/RtsU9imeD9VZ9MQjObrl7vQo++T9TFd3utKEQnCD
  template:
    metadata:
      name: headscale-s3-secret
      namespace: headscale
