---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guacamole-pg-user
  namespace: windows
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgCdEjFNuGm1yu75R+VNyuW5ieQys4syxl73cvUTNbkZKp+65FNmS1tI2VXtKigdOInsUfkh9iLISEtb1vDf6zxdJ1zeDlsOqYvJdLWbw2BviTlnewuLK7fNj/p0hPA1FlRjxJdh5SsS6HICUqnXgEe0wQAH/1sVVK9YXSB4KHgwW0ss4TEg1Q3VF1dUKSvXtSTFemfKiUGOAkxAltR4M1eSCZxsDoswlj6vvp0TYnmR0TzPhtYSKRNLxeSV3XtUe+83xi7fvbtJOt78XVblV7FcDvD/knZ2gfYRkcMTQxNaUhzffLp/QsosWVwuKupMSb2maZFNEw2ksM8FGBqF/hBauoX0sW0XnyJwjQsxT1FFd3NOrEqbiMu2wQqVah7J/Ih52//q/BieHT35NYo1UygIOdlxYNpI+cckmekBfaHwReXfmXbE/79YwPLRsbRNHlUgESxY6qcGtWEG/r/oBHeESk5+gJkJwzzv8/fYYk0JeXiqb4mNbbWgPpBpgudStc27TFg8eqRie54UoO+G33Wzt7XPR9JPqCAjhqb39kvTF8rSvYFextfrBR4zhRDLF/KXfpk/mzjp2/F2tNAPE2eSvby6v3GGKy9mSSvldNAR1N4xUD68ftb5o9xMVby74Hxz1iSdKXrnbMdUh9aGL+yi0E4PlN3gRdcpYQchp97Nj+p1yyGqYFTBdMKYVclb+e8O3GdM87HPIRpJWmUI4U5C/d80VcY63tDJKRV3TnHNx8fMuGtwWGInVKtmsz5EBa4=
    username: AgCmfXkU8hjN0YxnD0aoCD82cxQbXFa1x2KMfFnSoAwA/w5VtPT309yqTijpuK8/i2I7DWJPI0w4MO42naXvsIIbqAqW3TAePwJa6KqbvJECDzN12piHQUp8q8Vl/aZXNF6lTzlyHgs7J63wiseJPPxnEQ/DteMTPzi/0d4dSXJT4xSNnlDrg0DdTpa9uoiEkgVSpJ/KRlGKQX4yiS5TSe7sig+JPCahdocnqUhbf4lJLZUExcKMcGHO4B5EZiBBCKckVzjfNDgtTf/iNBH2MtRnl223tQihtUO2qR5ItV3aiMmF4eTakImn9YstLubEPDi2dOyS/KMSGuVB15FWXr9I2oTmOMqtjChAdpTkB+vs2d3bsC+gKXM578WG25xDb6HrMDnMBhUO/PofxXdK+DnfPvCg4d20DkcjxMIieWmlLc77HnPFvhF4+p8Ycb5uS5IvRsXGQG/eb0lmmB8a6MCxZlSBLU6N4VC9q5EuJQP2fSxogBAiCuvpaKuMa+8t5/t2kWS1IRRWI8VmdT6/7q1VgU0WAgBKQykEDB3aBsMrFwAMfKeBedvgLMmuCEimXiuGnWG2LWugNogfTwITBzopx1kjUFlhvYto6N/kZHeq5ZJF4f+5w/it1mvvoAleRlGmohMParM7YW8Cd9i4znkzUVxSCMjRRQiarpN+UFF1VjLUPFFxoiESiJTa+LHaQRNSz7lP55Z0d4KaxIVchA==
  template:
    metadata:
      name: guacamole-pg-user
      namespace: windows
