---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: gitlab-s3-secret
  namespace: gitlab
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBSRROiYTG0i4AOGk36+ehEuuKGiW/ckPiDttIYphrAI9CyvUlXYIqcVcxbotgvwyhRJreBkDqxi6VKXzIZHUT6jeQxYbGNPGySPcewhhxtYlirZoWCwYeCtHUMOHxYp8DvUGYFt5BYoAT9uu3TnMKEfxEQIIhZ4Ijr/fN7MxEXvKpeElNlYqCYeVkkk6CC8LQnQ2nLZXAj7FUpi8KeL/+mnlgNZXl8560ypp2ZTRxNY4H49Dsm0yyopm6LyBcgs/as4TG/Dh/UXSb+jgoCF9F1LJkz/AbophY86cxN+5X7N3vo+pEIunTK8TEnEvhhDmh5j82sPxlHMU2AZWz9oCgOQDA7xalIoDoJxQCFmct3Pbnvv1AQAwy3OSJAU+BDIsyd1dG1jjgiIraWxLpuk6lgvokCep2iI0UgaVrcx08e8fZAk94V0FaVi83Dr2gU+MHkjPQrxcY1mPRKx5aBXuiEk1pjVVfKtGLS426/ha4Q8aECCZhoIi2b28SWW0yyQZDRsM3YKlYabpxJMrXRKQhPjLFQbYKrFiPXID3XVF8dGpZjqw9WkjtUYs5YAv1VCoWanbMWKtVXOFJLWsYNG5UTa4oF4+1zqIt7bsBASyWif0oRFBwZ9dIs/ItotgcRuerdKNKLsfK+lb/8kahYtV1KjAMNdmiKUeuvndbis32pFQBDH4TL9wkAsBffJ2+vGz0QHb4c55StX52QAvB4VXU/YwHD/Q==
    SECRET_ACCESS_KEY: AgBFl8tm0lbTsuC/X3Z1QsOeWopyTO3xvFSRZbQONoom5DRMWqGCz9BclODBMCv8hD0DVhxyq5sBUTC4k9PJ8gRcHXHtnl5b8TIp3CoUdy1ByiLX9lCpcprFFjcE1QObqCM62PI5yf8Wz6hjrkLfgWOHybKA0LdKvstpvk0G4cDZd+8O3Z41MarJQWHeJ6oqNJn6qaxho3iPdwPsIqC12luzLbZ/OMjQ5O5h9xXewJFh4SlVuh0UD9No2ocyWKtGejmFRr1ZyskXIbB+hsWnIpcwSVGaih75qVe0SwXEYR0d8VolGpW4FrlDuS7V3nOPW2mguvsxuBENn8rAQXt+bO2sgOmXtG6UtFXYex1lL6OOL3vWZtT6EyMR5TdNaDFQEKEixo4AkX16xOqjcnoMjZq7B5T6wsrp7P8JUwdQH8X3d6CztKGenTaeImpLnyHn73GfXEaVH8pzQeyFrQikmD7HtpqsI6LpiBJnQEyG8GISKrJ+REaXzjJINtNm4ADkInlRKSAraYWUCiejwBmP5wBK8AtCgQ2wRDCQy6Tjasp6yeiaD/9Uj43oIfdx1OpyPuWeZSyrRoeOAWL59eiNkT/wvQAfnJ+bkxpYlGQdYVPvH0pS2BQUeY/EBSIy+2MecIIFQB/lxbF18TaHPaIfYBLroZ1IKz6dAK2mlBFqeWBD9cQDfDY9+xKYUCb7d00qf6kWXplI2EedP+zfRbxRB877+L8p9aryEXd9a+ki9VFUUIdqF7WFyLSX
  template:
    metadata:
      name: gitlab-s3-secret
      namespace: gitlab
