---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: ""
  template:
    metadata:
      name: gitlab-root-password
      namespace: gitlab
