---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jitsi-jwt
  namespace: jitsi
spec:
  encryptedData:
    JWT_APP_SECRET: AgAn+x306PtfHgEBIl4zAdmoGEN+gA2wyKvI+nI9L7U+27fPJKLxhQdBxUpqGEO1QHdR0WID3V8qOcLm3KDJoIhyFwDKNa8N0gbVqQ8s/aa9eLsn8e2NFeQ2hp++6cgjlhv9dszt2QutwMQ2D7rz20Do+xwpVsfgD3iUWfZ8hKFc6ao6P2aZnTnQSQNOQnYV4Deh/ZutqOu6pWaQGQuIJL7GJTxdVfcHybxuw8YJA8xIZguGLwxzhaiikYGClCwKz0jXP7TH3yB1NC6m5QE54bKU70Wja8XVMZyGAqVtjRJNZ0GquAKWeZxJICke2CSLh9laEHqfOzF8IXlom6nM5aP3uG2FKzO2YD2UjOWIWHH2NAyQP+S+tMys7u9/qz9pl6rsOzURq1N2s+Dvj2+7PZzCg9t7i1CtI1noNixd7rjOIQO4P+OVUQLAlUa5cC5z67x90aKymuF+gRhvl547KEzHsCgWSxnxQfNFLZ3VExsgHp6v8g7Vk75863uUATkfLVgWlOjlNQ5QhU32Mb6da8x8FH7fLt+EEm1Aigv+8RlGP7In5hv5X1TRngmJBvYNErdWzTBAcYjbrlilq6AZ4eIljbv4xwX2YnqURiSnz5+wnOaj8ScR7Mbm3ew9Z3aErAViPEwtEk2480YYBHwhGtbRM8h2Nf2vwgSG7zPfM8rvDJe4DukGkGIr5bTaLm8rVKGEQn5UlbQd/JjBza6jrORgj6Nrc2sBgQ+JwmVIDvep/P+Etc1CPXWafAWTY8o6EvQ8Z4xvxbfeukzN9A2mcqIk
  template:
    metadata:
      name: jitsi-jwt
      namespace: jitsi
