---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jitsi-oidc-client-secret
  namespace: jitsi
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCscmL0v9Nj7g+i0wS7kuNcjAl7JutKOc5aoCY2FbCAOqXb4Sl2BtyBYXjGeXuZWGcVpRSc5LDMQ/AsaRrwnA1TlfLrHOtOsTBaR0+ljBcAjbIihfqyN/bC02s5Nz/zFthW/436MXg9GjdlgtM2H8F2hfr6uRh3dxArLG6sciRqYdjl3W+PPlrOM4JXA8nx1s8FHFA3cNfegLNG3VrgFop6r23auw6/CAh8TWeUqqSlfSiwnLhLHYW2nhtFX3Y5+bGCmEemUzlnLk8KAcw419IxFGqdfVP181X5VT/8hXhNhmEo2hRmc6altQI8rsaOF4SoejveRzXhAUgqukVnSDsVnlmqq8udr9xqBaqyWgM1ETyufrISWjsU+6NimETSiW9hopoHn5CVZdHWP9j58D0Mumw7KgImfOtfNrzevbLcmLPXZY9fhi/s2QUN88Jfg0tOVF5pRiLIUoMxCSYJNuV4aKMOA29aVw51y5X4DrT3+QinIOg38TnXw0EVysy/TSQLZQzZa42HR0DAIjABfnR4qraO4LttILClmSszvo67JodNHTtyBfrJ4yLhdav2Ihm/GA1/NcH+2rFZpTLdzPIIoXE1hGWXFga8fUHsLVtqWTNRuhGLRZ77LMRAtpcvL77C8WG03Ro7vGO/X7ou8Scryir7qt95dXAYGJ4ubrbcH3lxLfXAsxFyUWHcus0KbHX2pcK93/n7JBroyaTZHRQwTXrKNc8h74G0AccK14rgqa+MWsJZtuR5xq7LtEZkUNDuMSOc/V0cUFv89T5C2pyX
  template:
    metadata:
      name: jitsi-oidc-client-secret
      namespace: jitsi
