---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  encryptedData:
    db-password: AgAcZgU5h0y737a+ZeytkU/Jk7dV2xCPqZ8EMIhWNv7SyrpDI42G87Y1Fi+N/5sWwdE11pp6XC7PUPDZQq/Lvj5i/a/I0nvI1c+6R7wV58DALmPJUSXR0zQwdyarl6gGfqNBcvLqARVrIKHFYka+4fj1KX+5r7NmO6jyphTXUOn5p+BsQ+DQ0YAXd8x5zLIavFgmWd+OgHcWf539BTY0/WgX7UOjHX/TPGo7ek+iG9NkwzlvE26q9MA5HolBIrJHXzptlodAwzq4Yfyf24DSQ8iN5h/Z9m8TPZ+TUGe8iCyUUDwavafThDug9YnkwERbboV78LwO7fEwLrWXa4YBKzq8mJY4ZBf4swqqe6WtCKOBSCxY9UCKaqs06m5g8sJ4PC6j3z0tlFVCg/XBWGx9HIB5Gm6+fksiDBS7QExu6AvqxtGAotzjZw2YjVnc7kfuQOi1OWetTdgPM3kKMfq7BNTbMGvimcmxIgEOVABi4FWrYzO+Au442nB/4csTRKVqjBomo5JIpaGD9kunPG7NiTKpmUYHCy7VQT2m+yPJ4i2BlaR7bYp8roFJiBEog7WnQc3OVxV97ljbgk7cnJA1GOMSUQn0BSio/IoJxKZAA27THfJDlU3NghjXgG6wBcrh7KK2L2ZRPqrCWFWgA28Krzp2zpw5nEhg/mEkckgRMbvBYFd9D/g/F0o/gjZD8M+MyKz5kX/N9vmvQXt8+pv+O4dZcMfNXx5Hh+Sz9Skzq8Fdu95YVG7GmftjzkLW4HB01ng=
    db-username: AgADxUPpK6iKkZ4qjGRUTVZC5N/cxsLrQ4p9Vl+/GFbkaN5Wsri93brNkEcliXUBoyWiDlDySyHNqoN78H90dS7NPcCqBEePcad+cSDcKKk6Q27U4rdSgdxuG/2cdMT2S5iPbcZtb2P5XvACL+kN98vpXiCqTP+DVDLyZRAsMFPuUZUBJaN5qnGxs2bRcRWmTzHKUvWerrR550VFkpk2tsK/QPcQza8ZqzMzSjs1fmtxn4S96ngnmcfK8PPVDjeB2etR5UiU2d9LQUbtlBIBCg0awp5/eKymOVaWZ1rG3HDhEbs0HNnnjaJQ1QL9EQKZnsyuZLF2Xz9FQTX8Ax8ABJOYxTboRev0gFI7zIAnOcTQNMLmX5RjW3iOLs+bRsDog8yzv24nq/DI6ZIlcR0NA9UAiEg2TdmLUhWgyGvBCaquiesQg56llbpTRluQOGT6y1CYln+TtFxKVhK+ExdOEmW4ahZZ15S6Dq0MiqHqYSBT0WPixsLYFNbDxblVayyk3DRVzxgwndNDSQeOgRbUA7TIy7g613qeUbbq7IQhhlIfv+JFC8BIiK2ck1fMghLS5LEJbUK0LngWbZwbTCgM4vz9Hslz8a4xPYVlYWjt+Ww8iB+DQR1Ox7Uin7tMQoKJb4t4pfIJXYMR2jTpuq7zyG++fJWYLRyvsRJJrIJxN4wyvZvptmTzCsFARETujHewBSfWAISM8hwSg2I=
  template:
    metadata:
      name: nextcloud-db
      namespace: nextcloud
