---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-pg-user
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBOt7YE4mQtUqXcFHNiApyy4YUv4f3FA4UUbeDLokmVJPgmuy1zKzusxdiRhNk15882/CBx2sKVQJRAjtMlzPfr6J+fbpAhrmLxrhi7iHWI7tAcY035QMZDCVbP/+b6k+HP8K2dZ3m+8LhlBC4yfguvFSukLQAXktIeKsKOX4DViJxlWwh4LD1HYIAzYQZFMJfV8kyDlgOXhafXE42R9PLsD8xjXLbzUO/dKtY/repcGMYsBFsYA3rodJt4l7YeGXRTk8dyxhHt80RVD8Ma3jVtlbW9CMkcqt9BTO2mwDxDWo10nKMW89t7ekbuZHdOz9BjsZvjwKRQCnZW5itiLM5c9CAOI/+NnACKe4yCPxgAuFEi0TKboZl4q8v/d4lFygpgdRy5AlQquN8nENGU4cTHvqx+yhQi9DAkOflS/ClNnqR2iruXqvy4/EeUZZk3JxS49jcEwUQKRefHWTlyQw6KCmCNdV6ARv96aIVs/8/00tbZwxL1zoUvaBC8saNaGYq+qsOz0bBpqqCxUdSYMRYXFiteixn2GpNFqPTtlP48VBhCYvSG09sLeIK17q4g/3rAlIDCyJ2zea3ORxN1aH2QorDJTo4eobsofHYoGUczp2q73+XKeLAiN0VEDZxU53XP9x5jQh8oK+5UJEw+4PCzKDi6BBjdR48WsY2/LS3FvejOmISzm6owXpAAAdkbBP+EetpGuGdlqkbvaHRR5bx9LW0LwKDtlreOSFwBlrC9pCke/i3QT6bit4fl3GjSWA0=
    username: AgAfdz6wHKVWWWWUMm7nR+E3UmkMKk5fJwQgMF0ubF83sm5uxgpkLkptnHj7N0YbIWKRWPBfx61PkNPvWqX3SWmdWP0EdlWdm9ej5MbJqb+wAHE0EqltvYBkPkWTt6l5kJzyZJVbidHYymzFxBIlTit+Ha4E5fT+a1hDnii1xkw9WXkR0HVnS1JVD65IMPPDz251K/zwZCHi+eR0/u0hZ0gtzx3VMJKjRw6MA+pswXRujz8/smk7EctDsdPWbrpM4BnWqcSuDh7CZxD2gXrwDZu56W26y8fRAHnQg2KzMBZ6K1hiXswpcMD6OMMmnQsR0Z5u2Ay9jt16IC1bOlRro7USD0ldyRNNi1KpHTTylqon+A8/ZY+vizmrDbuWbMQupWcvbEkNct+qchy7qDpJclemKkBO2OE7V9KgWogPaVT9Tf4TW+taKGR4ijIWa1aZLpENDB/1tZaX4yA697yvx+l/eiYK3psxthzKsqf910dfJAnLSca1qJF1hAtOGOGC1yQC+7XwQOjrftJpbwdid7UC5X+uSNy/H1tuEEl6HOImc+adjDY2Czf3EpKZsWJ7d6Cbk7qoheMyCiOgIzjJHx+RrDhClSrHRdACaysaWyNy4g2BfDpnOPmjm+TePdYm1c9mJ1Lfn7oUbEn7Q0EgOPNDiSx3yqpgPAdmM8ZEmDY6zMAmltnBMHBZsNcBxZNCf/oGnBbjMiEJPxw=
  template:
    metadata:
      name: nextcloud-pg-user
      namespace: nextcloud
