---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-oidc-client-secret
  namespace: nextcloud
spec:
  encryptedData:
    client-secret: AgA97RKFaB/pi4RGYS3UrcREKfqw5KlkyP9Cwreg/WxYlRGZ5rjPfuiqPdN72FhOXXcl7Sxv1N3eWiIhd9VLlbJ+14A1cu5OTi6WlWIjsEbRuuP++VJnY3GFvdkvrDS0tg91zn6lE0BhmkSGpQRQPpRl2/CnYBmuajHNCnFhhZ4iYiHnhmUGEqxk8gJvL5QM7NPKExxGw20abQOgzVLLXKzjvpavr3olGqkW3BDj3BL28OSe0i5faz6H37OV03pY7TY6QCGlpmZQTnY6XEio6W/iXBu4gklDbHV/QevHiLJdDOzN6np7BCtMMD3rTw3U3sQw4wiolAbFPlzITB0l3ztA2VdxhKcReuYcfaI/0tIOvv+jQubEoi3eswmWA3NeYHRSvOvt8juFhTt+owxWCTVN8Pm2zIR3Lzah0+dkydswHD+8VfBC9yz+YbwEYaDQSLcKucdnvV7KMJW9uoreYYQzzLbxP/Gla6jGHz7ZHACL8W/c8ggb5IaZPWfg7daBf48pOCRwvC1907XQAFwOdO3Qk8xjEf0ie99FAYjZ9jN4X48vsebCVKTCyqvccrfCti7sALmTEv9Dc3jn4UnS+VsummczTWm1SFcTCBbXubjlb3ifHKQQnO6rLGlrucgIhCE5yXxohELxQsMMpxq/pIIsV9RNKuIvfQAJZXwD3U/kz9qyVfsOWN8/FxWgp0jjw2ZOwz2hbanrTXMLWK9zKulxW+fE3LaxOJ+HKoRXcKK5rE1NQvCIsinPTqm4ewKijEMKkCSO85wAeCxt5HnkgvNx
  template:
    metadata:
      name: nextcloud-oidc-client-secret
      namespace: nextcloud
