---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgCuYjzDnwrqy/p1VHoK5WFn1QbPR5emQ0P73QuEWLmKYuIOicJpw9u8rsE6TxN/VQuBZvYb5pkiHM60Jv1DR/L5AnL1N5uJPpctotxIrNivXcrkFuCkY3BuAnlx2VPSHz79luSjUnjuo/ML7QBSob/Tn+ppmyRfae2XNrQ6kuhX6EqDc9pTDVGIq0nYpdiGukf9TvG9t0T3ecOWpb/4tbUwAQoUcD7zP82Mij2NwXH0nw4kES8dWpDChbX382QuXTKLT5bAMk8YASQyhmtURrBBwGSKLzAMzHQ6sG/ybE4mewobntCmztSHPluj6o7xEMP2EbitLldCafFPy2KiO4hQFOTbPAoQ32y0ufVXR4BCLIN0B5dUTwCHQqtEbuaro190q49/q3+btj79Bhzoqf9hCYNz5gvKJWKpbB+YPfcs5+wRRS0c8oigs+fXdoo+PCCA91SYNr87g9G4VJPFyJfXwaCLDfrxB1dUAZV768h2U2xV5/DmvBGfJ8cFBnJF987npTJ5ggkcEBDKj940/Yd0+R4MgNKgj228U5zRStElI0Q1TPE+ATEh6pyZP58ra2tOkK1djXG56GnPUmZ8oOt+ak40FhUViKc6q6o0cwRZdiTeotMYnEcTkCJ/AXWgjGGnqpYNfq0+xUXyEjBTZJQEsfyfznxidgxzCZT1FDr34hY2a1/azXi5Y2oCIiMCON4YW0CBMC/Cp6RaeNwYlUaHGgTCH68BBd7UFjdMXfqIWt4Fsn6SO7iOF130HTl8Ru/H7zv8yDE5TcB281zaZ34Ltlkcmtursae4pbxmP2F7+wGH3+qe4Is9e1YNwHYOBjBfCVJjnjiOIiLB8X+X7emCfCyDbXQtZSHVWeyGKxFOwVqu8n6UR0XBeTZogPqfBFDCISUJuhyw/7vk1q24aHalNuIxPoxylinqqjzl5gtuurNb5p7A+aoi6MX/xHKzc1UhAxd3HX1CyV05orER5dTJAOwORDHYnNCF4ija0eW2FmHo1jfnrOFwXG43do+wnFZi62i1LDRE7g==
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
