---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eda-pcb-agent-oidc-client-secret
  namespace: eda-pcb-agent
spec:
  encryptedData:
    client-secret: AgBWv7b0Z/6jHOewuyaOCb62p0Lfxc+M3kbFYAABXKGkE8ACiQYYC4Cu8PFHZRy90oexERpURutXpEqd1FZWmvdu6CafthHzBN4V29HvAmPfwK4lqswLv7XaP71oAstzLKcF2c22Iqc0jBKUT6JZ/Y40VvajCv0RZ4nWwCl7/fHiUVt16hzAEahe8sZr4gR9AzLAEYgip0fvZBH1uDuo7vXEli8yuC0BSFs7QmH/guKGsYtzo0t3ZlQkgQikFEaGJpH/AUeKb0t/3fG91psxuSaJSGshspRKsKlZT4dEMlGOELsmQMMi+CXxSs7Czz8TdSNMMEQSOGtbFsZPJGxKA6IcjxaTa6Mr0GaGlK0wTk3lhSSCnxf3MSBEUOYyHrWuGbXU83Mp+IoTb7ZE+JzAQkky746o9xwBODrQzBSS5zWMwNEqQlFEdSbPkR8i/jdTp5L1RiAgy4GyZ/Rv0FVeaY9vlcnMVRhjgEDHiSuBWAkQsJSESfxcGbGCDJhP99Ux30aM50+Y2urRcEL3yek3luAPnkNTfvdGPEDmu7GIr8wbX0zJNjgGNg0n8dMhLIjWiSz44TJsS6EH6xBoOazTz1eo5tnBpFn69yTTxKTABZIX73AoGH7rop7eP5EoNkpat54+NCb+pmq7YeAi/afPxpF4XXMzf9zAnspaP/9rUWa0RssTwUwkQaFzso8crPEacZqJCzS2FigS1geKcqDvxeYkFHzmzDXubs58mdhdg9fzQkj3Jq3OV43Tea0d0OnFE2mhZCm11nZRFS7T9yvk0XZ4
  template:
    metadata:
      name: eda-pcb-agent-oidc-client-secret
      namespace: eda-pcb-agent
