---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zammad-s3-secret
  namespace: zammad
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB4kDway3M9SOF/XEMMneyKayDfQ9Q5CbYgniyw8KR3liIS3o3ahfwzb4TaE+UYq5sd5Q9uPbx4LRb+tlI17iBI2DPEYAfBXY3yFh08glMY0FxYLpCR1/i4G/WuRFum/t4Xwh7DXPci3lzUSq1x9oF08YMFFDCKwjXfSBbWbdAqXMvXm/JiYAvnnVxm4GIUrLvpSW9FVN2djFiGTqCVAT0prW3jU1AbIrRcjXtXF0bicjvJtTjiXx9rH52AjGGh9kxcOVV34hxTFR2BX3krs55e1qQFf3assXRZQzaBsZ1QxVz83H2HQHJfFWGNUevffsWX6VsJVGOHxVLrnVLvR+04aZI2SonSZLUDCjZKUZR5YZssO18/Hs6eSurTtoqBeePCf5WnVbCCJdM+fGAh+diNV9ZKjMMmxTcNw66rLlPfluYDOkSK23SHKy9HHlo84Z1o1fIQeIUsDUb3MUn5CghH8LmVWMXo0V7xELNssUvPJP6SN4YCGXSAc4O0O5P8fB2j00u0+cnfluIqc9gylQDnre2TbGaMIvxD1vo/hr6d9YRmS9uDxe8UKgg4pO6U4J25GPGnQxxr6dkkY/ioDte/QSfLgeN6g7OMMClIDie8nZMegrhYS0JW8QBv93vUshg9cFDpla7KqfjW+Gry6PkP1LkmQY92HqwZE+PHAf59ihnzwDVZpvGKDhOh1FEc/tqaIGQlSE8e2rBCFrK1QUsB85xm1A==
    SECRET_ACCESS_KEY: ""
  template:
    metadata:
      name: zammad-s3-secret
      namespace: zammad
