---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: remote-desktop-bender-secrets
  namespace: remote-desktop-bender
spec:
  encryptedData:
    rdp-password: ""
  template:
    metadata:
      name: remote-desktop-bender-secrets
      namespace: remote-desktop-bender
