---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-admin
  namespace: truenas
spec:
  encryptedData:
    TRUENAS_ADMIN_PASSWORD: AgBFoyOH8GypClywc7HdYVhlQbbDLFznRqQCWC3p8HNC6FPDMl8HmNBP8/Nxa2eltee8sLKwZvVTXHr3mnr03QUh09kb75IHS1paRr5jT0o4nRUe1FCfKmsqVPX0T99R4ilx4VsgGPlo6eXgpDiJzVUDW/hcvnP7pkJnVDAjuxSSNcg5zhxx/HhSQXne0qDFYBcSGTucivO4+au53rnLea7Oe+Sn3E3amQO9M7fi07tgV4hGZ7MEMAOaG9Y/+Fg12epZnstTgnxpG2WpBYp39fOQV5Y78U7MvroYq8n9PvgovZKS74gzi74d/VRtariHulpNbCgoGA1EBQ98zz2kqc/9Idv9cmA57zNlawFLkG6ujonYxBVUFzJ045KiepZ7h9i/M9ExeO7V33IKjzbUOUIB4C4jfzCv/A5HE7qzGvmXADrh5YvyDQYFvV+4nCPS/q8I59lI3hJXr2cXipQRFpdl5/QivQNnURnfNhHY4+f4oN6MaBMurlbdxymxEN/xCBW+YAnlDdsvJJwTDhP0fb9AULvcG5So3aBu5GtkouPPvRpM1G9jjLC9059VKJmwiEhctnOPGzb81PjCREM/7YsXZhZQtrbZsmvzmIVVhxD84Y4w9Y9+Ngw+qNa0feUo6gy5baJ3l5lJ37fJ78ZlAxFuJqga/UV+21vaL4al+uHp37J7xXp2L5fQ4vbgApCyRa7ASLI96uim5DWKLlBb1MJ9DeM=
    TRUENAS_ADMIN_USER: AgBg2XuWkcEpDPQWu4cT3AoV8ICK9rE3snX6nJV8iG0KCc+KeXHtwZHjlxBJwtjIy64G2IGn/jSnr0ue3QxaJjqate0fGVCbxizLGvF9OJHD023S7kJ32iowa7xCaI+dSRHRT1S+y6na4H0s2PALLRsgB3zsqdpStIKOjn9Xiy9q9/RvaT0PVTR+/mowfDWg+71OOEhgkNbs/fcApVAdqf8sd6kAkJAxO77OTssPPfdUfMoZ8WQeMX+QqMRJAxItaZsc+f4u34XqdOlMRpSIb14gUfTI4SCHWIMgt85OP/d2aKkzpkylQXDN/2BEQH7ABWaOx0e9S8YPBkCeDAtEsbxlIQSSElPbnC2DixFj5Eq+89JkX1hvH7zP6oD2+XhQW8lzZS0mO2uVJj8ifuCbBxPTStHh42PGr8PsYTSDigiaatmd7USI4TiifcOQkiQSnkZjO4RbJXpMxSvQmS82pCF/s2VrmEqfuwjNHGJ8KRk8FuW9V6JnCaQdJsOf8K7BexUWlMid6OLabfLjq0OCYFH//F54OttAOwqrqsWB8gDc3gmZ/JAzzEk3rCPU86k+S2BoIJlqYymHTdJFcKiu16X0XbG1VHkScb4tjaImbsIrsh0qL6/u/dSeJ6qafaKLKLd1yccgN2uDObPoxfx5FysWWaWALv5Bdn1Z8zC5Y8fYwLRYfAjyvwckmy8jUJ7YIdISJjFekCjhXbutrgzU
  template:
    metadata:
      name: truenas-admin
      namespace: truenas
