---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-s3-admin
  namespace: samba-ad
spec:
  encryptedData:
    S3_ACCESS_KEY: AgCOI0XCg+XnlexcxptGnLAoyzu2FngYaIWrhEpC9MCICl8p4dYYAblliPbdn3sUtFqjMjAbskoF1qUUqmXKOcg/NtlxqmypZRD5AiyHd7ikUH2NUOGLx0um9zuJ2SwDzNvbmwwTjxhMU6UYFtID1GPWCbexR5a6hNfUWCaSuShH3OauCd/S6skvctCzGZWon66oBVrfHEOQ7MPbgNwYtAbDiP1w6H7zSu9DKITuw1P7F2NQ449lhMu7GTM7OeC8ZVDQXRSpngMBaBIX5yp4Mf2ALW6mq+xb6jTymgxmtz6PA4V8mMyFMEiqMaFHhtRefkNKBPGGlS+SUy2qA2xWwUZzD92MePwazfA/FGvaMX6SgSNXj2ifAyKqxp+jw7lqEm54ePvsMPRTTUeVNhC+Tha0bpBYXpaH5t+d0fnQSinEFrNvbAo59yltWE8kA1CeM6qAQROyizkgELF9C7MlmEEahxUGAVKXOT+kcLvoXVa7d3+jvzS9jApow0ivep7tj6W4deGSbrMZfajR+TP56QDMwvaR91fqyAG0OdwRr0Zq4r5pkFpeT5FNtMXQjawc45PXkhs3oVOsN24glmrZqkqt66pDNI8VEsMrOsXNsuSJL2v3ckycsLjg8pw2G5wAcfT6BlIJL2yhFQOt5+LGUL3ft/nARla/oN4qJbcwKqImsGQWOYgRsDGEwQi0TPyfwCQSKhDd2/ikUY5fjmpi0YpDxKC86A==
    S3_SECRET_KEY: AgCBI3FTzhnF4HhWBzePJ33goWdRq7lGRsQzeN7XaAoaYb6mXqreAGKQI+jDfCRRzPrpNhLU8GF7e08yqHmAG3DdUHOaHVsMaH8TJ8VaCvfuvO9Og6YcBTq6ytMu8PnswwIDaPNujFXAoHyRmGjcyo0l5qJa980KLX5scOuNm6tCzh7nDU3lQT1jnzpzY5IPPgyfCIeJBcNJFabVxJqP4ESQZa3UHuY/l1KU+Hd5Mu4uQ2y9XaS+aeo7lmGmXttSHiDPP8scbOgskGhragfz+ZAo4G0oLBFMPYVzBpYYDRqEfmQtTyCRGNQYkoxJUWuhRxVL7qYv9AbdbksCuLkh2KuYC66yUeopRsnhviU8ZGaZ3DDCyqoHCWeIfmCM6VKDkkZwq93rYTOjabN1BB5l+i/bZQlKCIS+SWEmecujw5Qb+7l83RbxxrbLifkCk9hRRMjcVBMIiO0qRxAqanQuP/nRfDfjWzh5VaoB6EH3HgodDyJkTaXkNUH7ALbE7zOxv6ok8VGhz0i1+zG1MA+smRRSkXV6Z8Scx/GM2RXXTFry4qWpQgyI1qmFTIcvMRjLS65D956q2ReWgmbiOaX5nlWZ5uYDReYPRIb+IYUuMaJu3zALk+nZw+voOs2uHo0CC2KWOjVgWjOqUpJp+7yEqF1XnJPU48aBds+LiIoUxo4NSIpRneN1MpkHaqM4urEXeTcQu5vK9xs2Rzl+5zXBcIcYfTFNJdjysCh8vrZDpv/b+M2HagIkX3Ba
  template:
    metadata:
      name: truenas-s3-admin
      namespace: samba-ad
