---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-admin
  namespace: samba-ad
spec:
  encryptedData:
    TRUENAS_ADMIN_PASSWORD: AgCSf4vVj/L/3Uan7VyEJ2yGvWhGSVWLKWVXh0cEJFpBREihL568yvzew07RKlbBf3lF1c/5OHQ4K6E3+tIEu6MJta5wdH0CZkolI+OePA7hLuna6lNQUWTjE9TEpbHyNmZuL6/NZPoB/XbuhoeyJgVPFfDyB6TSZbT+unEmKv+DA+jWcP0VQsDF5UUwNaroRE0BvkFLtpKvhPi0n6N6aThNitBq5YdiCn4nyFe7KQRSsgzkFhTe1uStY0xV41h8mwmH8KbSEImUMXX11LQ3woppOnSeU1yVAzGc6gejTvy21DCUgPFYy+za2NuNxviXAToe80w87i2qgdA66zGGDGF9sLCCcPaf2IAWqsy9ty3t3fVA0BbGnXo2u5V6Uboo0g5KRyYJ0MnN3SawmarNeWN1Bh21Vqyid4n3AdeaS6SRMAF9erXyXW8VgzcloKgICe0512febjzjWY6ZWu+e5nMSU8SmpNcPQK+dCXzjStn9y1Yy0b+AhTSPXYN1tnYmPlNwpdWADJLSMuY65rhHscFm1tgIep2JGLkYHBiLL6EEEwXGXrsdlnHpPZvi06sFm8dyS41jBTus+DwHLr3lFFeRpJNGHg8XuREfG2deLFos1WUeessudTgP0bFgxRo7sza+k/zpJ0N5uRV169DthD7LNHXPyM49/3R9SDgLP1ZjLTQ39ABZNPznlEu3Y7WpuSNx4KQMs50ZRwIMIfdOjI+ze+8=
    TRUENAS_ADMIN_USER: AgBCuDyu+cRjjZgc1cKanrsuBpeU24v/n8lbRbYxZEYSPNmV9NhlC1/mXUO25cuuPUHupY4RfVcrp6whRz3utVpZu1uzX8IkQ7F0wgE00cm8GKDck0/3B7ubMaOXwlIWAB7QMWAtc98dfGLZO/UQVEh2fziUONfDdjnaL/TsMjnAyMuUXbChckS5kdfvKpjtTGboO+jA3WHHUwjJjIwMz9x2/u1AiSvhWK/wb3koWAb0V+tu1Gl+3F7RYMS61395K3q+FUs+p2P5FRcdn+X7QKU964NUuFI14OiCqnlrobQ0yn/gQsIIbeo1D705oQWKNMITJ7JWSZpTt7KLX8fZhZ0t/lmriTWbxOHZ4tL0EMWHvezXnQ8DtNb2+cRQSx0W/56+SN3X3VQyHyiKpIhTD4Xll/UEADCdbCDXIj3yBX2F91+79TXh4Vw86RFCF2eT5n3zo93tsnO1Yg7KdqKXS8Vq+fq93Wff+oY4EKf1u0r4s1QV88heYRtiuG8SNgQLuCflD1XfZwfP4LPzkFcTg3RGDszeXn8gAjV/ltHl9YEbSXdDoZVTYrB5Q8dt8IVkeQQA3AMBX46YuDlqgYZ0OlwZ5qziURMwZGMSrNoUo2ACtEfiebe/E83tPij6ZU46V2M2bxTvaMHBsez2Lw47++qDhKfDK2QSekXB5idUD2z6qfWeULTGTbsBw0IK4gbaR839GJDu8dUqLFzK2Tg+
  template:
    metadata:
      name: truenas-admin
      namespace: samba-ad
