---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ryax-user-credentials
  namespace: ryaxns
spec:
  encryptedData:
    email: AgCNUSDpAEDoomj6YvjJgDW/oMRZ/PWRsP+09+4KM9LjwMVmVX99CqKFzYtxJIdGdoTA64xe30TS2VOF9fqwX0A/FOOhbWv/aL7/WZoWmLN0KVNsGqc0wr7uypsY+GpYp+2z7tGmg3LSm4J/Q/CSqFLWP6p9M7egeoo6P0R9YUlo9uD8o7MIwH0QAoGfM+Q9UJ3hYF7UdwVuoBBzqm7SOa48cV95QEvto2dh3AqZD4VZhBj5FH2K/RWvcseyp7w+GEm9nhu5HPmmZyVfdFPtONk+izfNhv7qtVDRbeZJhWqnAokG6yuNbzN5cNpEp/VH6dASdJA/5szlKlMJ42iA2QCVpTq69jHhwiZSJHeLayemW2QffatDL2I/WT8MaiNIM2tjFq2zCdHG91AwOTsPkVQBdseTksI6RvVlzdB5Rk7vM67JZ57NKEw+b/SXWKQBvG6+lIWuKqdaYJS+ccLTvt1TzcXTvVXG1OBrhluWkqydPNtP+d1m5rB5cYDvijrxNHK0ZM04hC4whtcK6zXunRW7zZdyf6PY1vdva4kroDxe0QnONyTzEoB4p5zHJ1hTOpOdTxO7pujkWbH+mHj5UfRBp+4I9EIeIx2+Jc+nluEVrUkEQ6XIw0sbl/0PWrTFsd1UD8eRP3rekX9eSC1km/Sy+yJZ/X3pHuN5U+Dzi6A8ptX7/nBjmn+rCagbXTO8Fnq/0vOxVAG1FzPv+l7gIRblrY2RQw==
    password: AgB8aZCffM0TqVThIvr2FbxmzpCU+3aPP/HhpyW9H8PNaqM1Uoir27WyNMaai0A7If9JRO3DPZgPl6470C4sNDC2NkxaQ9VazEuCuad/a7mlI0kgtOqTzrsABhsosXECbA89m0LbVAW9mI8WidKFzl7lyhJGQhRX3AYyX0YXNB75DAt1tLYxtxSbipZkhkJspWBx1bFJSvUAOEDEWDceKUhrohFABK9x+CWo2bsFTLGtgV7X3kLBTUejF1b/l5EhWYnE5ItF2a58DW7gBjP+5SoSamfnL0AWVtEaCtG2cOaunHb1yFHFHqXOXUQT9d7g4Dh2p3U84LzdIUDWQ2xSZO2ZiBV/ccaCavibcomHoD5+vsau1Ybw1sXIS5UktbcoNk207nzsyXelJMkeMDmd8o7XND4Jlf7PjXpaeFWIwdGUkRV1WQ2v897dUbK3L8pmy0ltQPqN6zQhXmbtta2HQ5IdbKd37RNtElpUYeBnNaLn3iJpVhDYPUWJ8tyU6c/EkSYQqnv/3AopUmaKHsi9AD6r1JfYuGQEvjvKROuoik3SOkxW2T8TC1h7lLOeEF+Ff9i6D1SpfgGSEm5tO83nZ4etj3IuDRPGlnBHpC9q+J1WM2nCfeZgptTt2l4LhdqKmJfcGWKzsDsY/fHpAB3ovH84bgOG7zyecKUtYKLZBGFogEtG1Z3L8UMzKk90ft0jSCdNEf/+
    username: ""
  template:
    metadata:
      name: ryax-user-credentials
      namespace: ryaxns
