---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ryax-admin-credentials
  namespace: ryaxns
spec:
  encryptedData:
    password: ""
    username: AgCFbIypKtrmRtgAO5Bsjazs8EHqrZZDoi21qkepXMguyenRbhrCP3PgFpTs6PGoBa01xoFuc0NHqh5jtKpGl3y4uJ7zFIdOBTvjaz+v9TIa86fBbUPgnIxp2za0dcBLA85zB52z4lnjyn893q4cQNo6hEQtiuYE8YalomtbiIOW34lEIUAvVNl/YC063DBw7VMtMgr6LPRGrp2v9vcyYsc5z5WXYXRmm8Q9qLhHzuUQlX/mrNFcD7YmE8IeAzheWtYWDEDkAfghsmzsHZewZr0fYZ2qoYtyPFI9gK2shAgZTVNSeoaPfsqYe9lPEFmGI8xEnL7hac4WybvpA17Sg5jV8vgG774in7Owgwg1qdOK0g8k3N/X81S1hRbqPaT2EjSm1I1AYtb0+6KQ5rjdfG/Yi2dRMdJFvTF4BaFQjo8wyh+ikWNUhp5s4iGvWVvxv9WE9uhhGy2Hm793MomwG2NhQHYr5Yb52An1bzLJGqaEJ6EZHNyklH2MPn7Xbi6u8ggXOco4R8jkPnwekNj0Lh0n5nV5zJD4PeQjmKmkUIFDEJsx3IqV6S5iaH6Uo6YBT1AsKy5ZN9R+ImsF7xheW9Q1UpT5r+5VEw+v+hN6mEfJk9fwWESe39F1YsA0hzwKPUkCG1u9LL8s1/AoI4LPvCR+WvB4p/wnYMM4NNG61xRacbBrU+9C/ZzceZWpRl7pwfllPUPLJg==
  template:
    metadata:
      name: ryax-admin-credentials
      namespace: ryaxns
