---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: longhorn-system
spec:
  encryptedData:
    host: AgBLtjrT8eW/wKozUjtP4JydLzYsyQ2gZ3FS6AKdN2ujLDnlbhNmXUk6fTtdz8r/CoZBN5zwSBuHKpX/AKsDAeqWNZw5C2hd3Twcistg2pyEtr7l9CGeLveQGUvLjdUJNoS5DxLlU92sFMzy8WSEOUtUysRHfMrK+SKEJZ1bufGZV7skm+NZOXTA0E7wMwuXWy/gkV92mYhoVEwT2OLtFxMmp5NZ15qa/R4zRQqJH0vsmUh7lwoJ4DRWkICrDRYPdwehCuCYDHcl1n6pj+bJRhh0fgb1xFHc3G7FYneU2IrLSfb1KvSC9rlbHLlDe9Trll5C0vvRhJWs8a4KQzmAiRsYGVwJS/5/wStAWuKb1gfwyO9SLGzMdOsAnxzyG88cxvWnBlQd8QLC0X2duQv1nyKOBb5gtxYcRbRn3v5jRTkIQ8Em48lQAFczphl8ZsgrZrZjgeqFiUOnsE/XGASfXQlBBP6TZpuJ6xNLI/7BwYn4bZG5lTu1h7nK/29L6OhxG6p5AbH3+a96ybsuzWwnw+tyzdXfRdRqrR1kRoxdY7DK5b5cxop2WK7+0XJMdUim+TOrJ3lY5uzy3x5rC11qE+oqfN1o2CV9jiwMKoMOaJW+j0pa+18GneQ0KzYvRUsyb5PeEP6qd8BG3BEifiK+V9ivcUjxc2Hi+3kP8zHeeN2Z2HgoJ9hHx8/fAJgP3XxxJCwWgYrt9zlvW73LSutJV58HBAbd
    password: AgBYjxL3h9CQRAYqzOEaJSymlPljh1N6i8mLbLif7i4oH5kubk0hH4EK/2IWwOvEjz1+2M1K1vxMQ1e0A7kWaYfyixaRp1WyMTx3YKwlcuya+z1TTn83cmefvtuy5KHUQG1gpPabOx8McG7nN3CkZEMrmZJbBQchmTt5+mSt2bHWnivEiB9Vq12ZG7oXb/GAwsj9SZhgVgavRmjNxM0OTV8xk3mb6TR8egiDEoqYgw7ascJwYYk1j6hsoGZc8M7Zu7Ov26Y9TDCnbau4VyT3AEuzpN7Tibk0itfr/Tei1/Z7L72wvOmkSNcsyry2xGo3AArEULnuQkh0fF06j2N3J6M0mdzcGQhy0YRy3D+5pTxF8PMDa8I2cJV+L5y1SUYizLUIuOcC7E9YwaBZClqwBGcyekxBpCCVG4Pq46Jy5HIxCJj7NRzTsQcvW8gzeAlV9dUwTfSlTd4gs8C6rK7neJjBPdrPdqNcVxVVDsJr8tw2ABkcSUYWEMO3JWPb1DW+hOu/4Mt1koggVIOP/jP2tODXXjibLpMlBuXrwdkMVOfhmFv+/Rpyvn+fD7unxScLSYa276UY/wuaw5WG5Uae6sbC3Au4XmYpeD5mGLVxzsF3dea7hEE8gI9L4c1Lo6iTZ3e8wkvGOKNy4howN5m+ydknZBFp0jXTr3fqIndnMu0I/EK0598hZcNezFc6rF/0Dm4InO/D8Nz2b0xFUOdJ
    port: ""
    recipient: ""
    username: ""
  template:
    metadata:
      name: smtp-credentials
      namespace: longhorn-system
