---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-git
  namespace: osxcar-sdv-switch
spec:
  encryptedData:
    token: ""
    url: ""
  template:
    metadata:
      name: external-git
      namespace: osxcar-sdv-switch
