---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd-infra
spec:
  encryptedData:
    oidc.clientSecret: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: "argocd"
      name: argocd-oidc-client-secret
      namespace: argocd-infra
