---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rallly-oidc-client-secret
  namespace: rallly
spec:
  encryptedData:
    client-secret: AgBKJE0JW7p2psi2Um4BuT9ylCeD6d3KIYXOxRvsWyLgDlKTw6Oc+lSLnxVYN+Ci0whJd+Hont1fec3E2bdb1RxmOrXIXTg/7ZRDYOLvptrb3fVx0PWeSQ8ZGjut5hDMHnJEQ5Zdj5i5dUB/sQDJQ1nUZCm0B96Y3R1QT822zhKBaDlzLAI3HdyISkWGINx9LG246XRARDY+XItXVHT9Lql7ZGlpdFuYAk8VlMG/mig/yr7gzITCBgPaya8gunkgqncf1Kgo953rME5YiCYWi6HvZ8r8JYrU5lYvszq7Ou17rW3+fyzVw4v5E4U1Ixc1MOZy0AXjdCTGC7Qx/mspJmr1sKnMr2zVrkRKNwIXU8tN1WcKVMm4ya/uFs3ClVkttp5VPqEcBHJNav7kdMOeLKNmaLbHVmhSXX/7fCyYoAaRZzWoVqSPDaMxIvKm7zZ3O0gcXgttqt45RtKWRdLI3WTQo+WR4WedD2PbRMNf733ciAVMxdLO3D+6s1S3YTu47aR3OmjphEir39eEx1E3RSfHY8OlSvdfBpSvf4RYkyKWqx43fXFkw1pTLfmQCRudmWob96QFJmMswtIe51NuUsyANeEqZuUlqerVqjJl8x61IUfJN0Hzpecvei6evI2Q47KTD84f/KSwnTcv6JQTDX6FXHcjRJtgTseofGAqDhbB2dv48CV+qLDMVfPLg/fahImWe35/zWS6n9QBmMHrs6EMz9rQqk1YvOAMu4w+bXcr357IvsOtJkyHHzTMDdNdJB/gTxmvgFXQ3FT5bxjXPQqu
  template:
    metadata:
      name: rallly-oidc-client-secret
      namespace: rallly
