---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rallly-s3-secret
  namespace: rallly
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: ""
    SECRET_ACCESS_KEY: AgB0HWHpnCgaRAD1FxqBu22nyniMUFxZTSg4sMVTWhN99LHpLh5G/K6x15f0f9E7V6Y+ULlSDa35q602Qe4Q6y+wAtaOAYDj+Vsm+6rGDipudyBIXxo9nPDqV3WijYtKLobcrwtqRH1nCAiNDlpyXEeHnyXLqcmfp6fPUhuYL+UPfLWbUTsnX+/GDEYgdzA+UDGusCNVUqI5pzYQbyKO6GFsukzG4vlo3R8f+XFL9EiR8SrzPDr+R95PRuY3DY0MJm61ebsoq297cDcEeUPht3r2Vk64X9+UDHDpCjHc3VHkMRo5KG3/JnMjOvKVd7e1AP1lxVC/Y+FW6Tjn+J5ZuIRkzYsuIksK0hhSKndhkcAo5nGgIP2SBaAjWrSp3wjS/ewdZTxsgF5rmWtwY9GQ8TRu2oWcPkS0lOspNpj5OCC+6NZtGex82DOgFZIr013j+jSPD0wiFIUunzFZnhM+8USubWdn9MXha/M6u1/NCHT7sPguYCbJTr9H2ul/Y55QXMUMoIUu1JFZQCpxb3omaPqkg40hRFeq+CF61xfFciR97nLfUMnBi9NU1x4wli84dAYbHAZkRj58DMWU5QFCG43q0BimoZ4URPRC1B3/uO9K6f7TMAKj/6ax8qyWJRaIo9oCnRfWBC0z2KrFs40xu9YVO4yriLCrk3Mn0QK/CcCoXH9gOZ6tn73Ow9zlsg/x2cFAizxdlwxJV3Xt3KT0nLivAo6dYMvjiyN8Rs3n/zoTyiwP8XdsFpXW
  template:
    metadata:
      name: rallly-s3-secret
      namespace: rallly
