---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rallly-secrets
  namespace: rallly
spec:
  encryptedData:
    db-password: AgCfCfOexqP/YIJEb3+i7JLVy2SakZbStBcfAbE6i3NjQLB/6sj5gXWVcJZsZ4Uvy0DvE28eycei5iuW+EZ3W4ltlD5J/pdmBKVUmANTklSjToGa+CkNmeRf9YOzRjA/s85/9y5hB55U3DuzzmqJHWytWx/vGemX1fz5gGsUjcbZteryXSQPaIS8kAOXiO+Cg86gMOBPlamxBWGeHmFTZ9bdb73BOgvCqKj1Mz+KA1vpQ6W7Vw4Ov8Pl05D8Sf4EKlEQOSkBOYLdHXL3wLRZZ4plVqk5ZSrKt0D4zZrSTGlDcsFZ0F1f/N8HorY2eCGwRsBoMgnXoJzdEpKJhZBoi1vdqUvLVq7NPZMI0ShB5vrBmvzS1NqnKx9ZrGdrH++6P4sUa7t3Cu86SUARmZxSKp4HptDIwZpAVwxLbWNHRS7Sml8HZg061uwMsW0dIDeQhxmcMqxtjC0giQpmd1DhIc0j6XdM3BeivgxIhn5KNbsUrRgeA9HhH5QIP18AEo4jMxoLyP/7tPS0l6TVCI4VEtdBJNi1GMnZSnSZZn92nHc+bdE98L5lMVPMC2TWM4VigEWloP+0zEBcIhFmDD4C7JycnsVmMYdyIO7aBgWnUPv9XG31JlfpUcAiKDTemBtjpa1sYOtNJMYwQJPeWKhxM8MQ/E+L2tVByvzqBk/YG+x5+gOCVSG+/cBo1uaTWS6eFgm8xbZj1OMWF/gKT14dZMAXRmpyqtsS3rLzCyMgv3bgRAlwple7gxgX4LhusCn5dBc=
    secret-password: ""
  template:
    metadata:
      name: rallly-secrets
      namespace: rallly
