#!/bin/bash
# Asserts truenas-admin-sealed.yaml still carries its PreSync hook annotations.
#
# WHY THIS CHECK EXISTS. The file is GENERATED by
# deployment/argocd-infra/truenas/sealSecrets.sh, and kubeseal emits a bare SealedSecret —
# so every re-seal overwrites the annotations unless that script re-applies them — and a
# stripped file can sit uncommitted in the working tree until the next recreate.
#
# Losing them is not cosmetic, it re-opens the bootstrap deadlock: provision-job.yaml's Job is
# a PreSync hook that reads secret/truenas-admin. As an ordinary Sync-phase resource the
# Secret does not exist yet when the Job runs, the Job exits 1, the failed hook aborts the
# sync, and that abort is what prevents the SealedSecret from ever being created. The
# namespace stays empty while the app reports Healthy — see the comment block in the file.
#
# Usage: ./check-sealed-hook.sh    exit 1 if an annotation is missing (precommit runs this)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEALED="$SCRIPT_DIR/truenas-admin-sealed.yaml"

[ -f "$SEALED" ] || { echo "ERROR: $SEALED missing" >&2; exit 1; }

fail=0
check() {
  grep -qF "$1" "$SEALED" || { echo "ERROR: $(basename "$SEALED") lost: $1" >&2; fail=1; }
}
check 'argocd.argoproj.io/hook: PreSync'
# ⚠ sync-wave, NOT hook-weight. `argocd.argoproj.io/hook-weight` is not an ArgoCD annotation
# — ordering is decided by gitops-engine's syncwaves.Wave(), which reads
# argocd.argoproj.io/sync-wave and falls back to helm.sh/hook-weight, never this one.
check 'argocd.argoproj.io/sync-wave: "-20"'

# The Secret must OUTLIVE the PreSync phase — the Job re-reads it on every sync until the
# scoped API key is cached, so a delete policy here would break later syncs.
if grep -q 'argocd.argoproj.io/hook-delete-policy' "$SEALED"; then
  echo "ERROR: $(basename "$SEALED") must NOT carry hook-delete-policy" >&2
  fail=1
fi

if [ "$fail" -ne 0 ]; then
  echo "" >&2
  echo "Re-apply them, or re-run deployment/argocd-infra/truenas/sealSecrets.sh which" >&2
  echo "restores them after kubeseal. See the comment block in the file for why." >&2
  exit 1
fi

echo "OK: truenas-admin-sealed.yaml carries its PreSync hook annotations"
