#!/usr/bin/env bash
# Regenerates ../branding-configmap.yaml from every file in this directory.
# Text files (svg, css, xml, txt, json, html) go into `data` as literal blocks.
# Everything else goes into `binaryData` as base64.
# Run from any directory: bash deployment/infrastructure/authentik/branding/generate-configmap.sh
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/../branding-configmap.yaml"

is_text() {
  case "${1##*.}" in
    svg|css|xml|txt|json|html) return 0 ;;
    *) return 1 ;;
  esac
}

text_files=()
binary_files=()
for f in "$DIR"/*; do
  [[ -f "$f" ]] || continue
  [[ "$f" == *.sh ]] && continue
  if is_text "$f"; then
    text_files+=("$f")
  else
    binary_files+=("$f")
  fi
done

{
  cat <<'HEADER'
# Auto-generated by branding/generate-configmap.sh — do not edit by hand.
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-branding
  namespace: authentik
HEADER

  if [[ ${#binary_files[@]} -gt 0 ]]; then
    echo "binaryData:"
    for f in "${binary_files[@]}"; do
      echo "  $(basename "$f"): $(base64 -w 0 "$f")"
    done
  fi

  if [[ ${#text_files[@]} -gt 0 ]]; then
    echo "data:"
    for f in "${text_files[@]}"; do
      echo "  $(basename "$f"): |"
      sed 's/^/    /' "$f"
    done
  fi
} > "$OUT"

echo "Written: $OUT"
