---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-s3-secret
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCmeaVhhdpKzAmeXfHJ9zwKkhdn0pMTA6gwAhiJBffNxFeNhmcA7zIihpTHGv/cTWssCJI1bae2B3bSMzxXG+nqSaFcwGrRRL1jEEdmPu/sv/xxrreXEpjj3+RdSfJ00EK18URnLE5HSaly8h3KLJbucSaFB3l0SuL9WszDMSFocuvs7yDiGJe0RFts/CtBY2TVHhPr0iAhETdZjPJc+4Dvtm9MYOM8pXbAVBcMgJqrlyLX4nxTLhmA+nnn8+V01PQznh1k8Q+t4nLOHnADsiEmK7T3vZpO+CpXyhUNmEz0wBxLcEoiyPTSRIv/L6AigiFMvKSsqADHDJ22FdWnMw52gQsBf8lIRYa8eJsUwOdx0InrT8DMbjynTVgi+mZNcfm2HuvDweNBnDZLbtz9r9Z7YHOk8vq7sgPOOdwdpXgJ7Oou+Y50hKIIvTfC81JNGs2BOeZTj3UmpOqOQNmF8IHYX1xGOjlfbfY2UijpfeBKqgiXhO4G475APA/sMl12Nc7h978ASdmNP+zp4fZ/KYl5hxHRv8iyoaoR9KGhso6IHsC4jkgVfg/32zpQiUA75g3HbsR3dlJrykffUz0oWEjidE5366HawZzj4/M5nWbJrgMhiUIfLhM0VDlbFAF9Zdc3Izxl8T6fvz3FSUCeSfdQ4iMuOQwkeKbttyDxYcwQ6DVC26FpYtwrLkdTCNoxZRCbe4grRkGUsUMQNQxtVFIqaTE7PQ==
    SECRET_ACCESS_KEY: AgCdAlzR/JSqT8FHwRLj+EQY3yoqBQD7GKVBcIFf/cU9TNlvauN1F/ICkt1ARqUYZenyLvIr3MLIn+QFIgOOOf999WYsBV4bqSQqVpKnmIFbcfdOSKRoh6gH4uzJpHfhYHD71RhMn+dM2P2/mNg4Evho08UzCo3zIWQc/tcDD5q0BU3nZ/z1rhkXsnV+M/LvgwsOZxxsvWyZcaFdb3to1IUCRfU/930zDzNXsopdUUPbfp/0BX3ib3+T/eQ84fRUhc3v/pDdITNE8Qz6GCTPuKmL8vI5ZIJb5YsYQBsCBlCgt5pfXHs8Fnf6zamTPtdWW5x4+ijedI/EzVihds9Mn8XCZHNv3ckyX1ExfTpw0+iS2xYx/l/bJXDZg+qlCDMG0w0fodWdRz7ZqI9ne5zQfHtvp1FE/dKIHCR3Vnz18BoQpFk8YGzx/j2kCTRMIidmT87mz1LdYuFFSRsTHbRJJXczG9zJXy39PAcqgIYXOqFcoUjT4ePw0oon7yST3jR5kuPqU0oR0NwtxOHcxbygsbE5XLQuB7ngAlK2EIjdKcN3fR5HXJTcrvNdNKd6x+TABPT/ADGQ8yVyxjf0k7zqtYTJMOCqMXyAYzRQjbL1t5fPjzH+7JLyjjLMKpOTaJ04ZPDOllhTj+ONtpAHI1GeRUgPCcNvTxfPpjsJ+AjesLbvef1Al699Z3Dg5SGqLQ3TSnDFTotSQ00ykG8uTfT4aV2bYf9yMlUKdjrJdzlVteaaDReeMYesAq/c
  template:
    metadata:
      name: authentik-s3-secret
      namespace: authentik
