---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-oidc-client-secret
  namespace: gitlab
spec:
  encryptedData:
    client-secret: AgBEEwYVA+sxUXyZpC49dVpZ58j7GY0exloS9y8UKbhl0lR3VYjcNRgiUqV+mhRceqwOE1FYZG8wm8GROsQIFEEzNQtgiERa1gb7P9pOLX2kufVtR5BqGsYH8IJTh2UvrLv+JeoQbB+QkT7kLpriaPUxbJlb7GrG6UyF1rbp7/H33Jh3TC1dgkoNtZK4ICc5mqEz59Bh8fGDOtnJ/quBw9Tsgd7iCynJQdvGaSIrxBzVw3Gs+YR4oNlxIacv+Cs0L3oUbk25b3K+g6OcmiLPTIsZo4L+HAtWAaCTKbuwXJOdTtsiKWMvoh0I766jgs6qxlNzpK9zG+G1PEXScSzesvVVcvIeTN4Fgd9ugAoxRVi3OFtdauQ3Lzo7qoffmHI7Q6FjNmEwPJ7LGk0aVJ9MrlOvlgR2kSo3GambBb8bZ8TsEyUd4Y5YpdwOmajgLjC5mjo4+smIfzOZmwJHxIfYD+CsHD99AT9LzlkC5tYbtkLtEfD2RV0R5eJfVWwMhay0XamCpcMPmtT53f7HW3t3emp/0QtDMvFcbZ7/rv8f12JaQBmdrWySSwcmQbZSBvAkPbA02chBEGo5qyQanHgVc8GOxEPT2xMuARQz52ditf/JH9QxgFXayjlMUgglKFH5zAGdTAhdAAUBXKUlPMmz5CbymB6PSV48qL/TophSweSCQuzz0MuD2Am3tt/d9BEZmq7HgM8R9qMO1wbkDA9e72CBdNriKe163YnyxLYwzjao4fnTAul32futWokzgAgk5pJaWQZQeKgS+oYagwx+CIBr
  template:
    metadata:
      name: gitlab-oidc-client-secret
      namespace: gitlab
