---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgBdDZtgwSpyRzihK0gYNZhVtHBnDak5ECl2FPR1qjPAVf+pSQWjgLcjjuF8oqQIoK5qGARdAGQOTjR6tgu5trBowfLTDHlKbDil7Q40oY/rWQ3PUjtd9fSORxt9e2Bg9tzHZK/dr/rvBNh92WPYanLnYgBqZZF0FYRIdt2S5s145TiU88xL3OPhfqLaEdiPTqfoBQjZvw++Ohmfka198HC75b1sBFqdLkJM2uBz6Z3qtAUAwm7aBQtWvTABLDw0TMEuvMSLC7FFs/fjudn3KQHi041kKEljLB3p+gQZUwsTEu7FR9SCP0IqRkjSaVlZOD0mD/Q+w47sQskCKRJWSCCSWD10tkkKEsfx+23u6Ip7eoiREGrWyCzR3Zp14ewiaM6Rd35+VAt9RvqMbo4F9xSsaSTrgUkLRYc+kYs55flhde4eZj43ixR7Q809337lUtnxikaltH+RnirPv22y1R7gyFrinLxtusg/FU8WsuwHNH/A2RBgEDUVV+fo757MHW8nUHo5p/wtNcpj76EM2M4xm4tMl6NuGUiY/IimiSoTGnlve5Mh7XK8kIZnauCiIuS4OWCyktQ6YaihJJC0XBb52RcyBCHfUrJ10EjXBQONTmwWyp5x/05AAcLJJSSKI3n/FDewLMUfFuF8ocKpDuhJWOIC0Sw2YV0Za5LZA1Y67kVEWFMd37EMFlBUw5w/XX8stQ7bBOZA6cAokVZOyzTnDSSen4pY5hDraX5YQOBZR/6HUOVFZsG4m6q2G1cafnCIShKTNkLqiyJcQ/vHxgU0ByDxrKAGcLXlZAEO43CJ3K/g7/7p1gkou8T6GUwTAF2QEPY8I44rKLEicqFL2RHRBGJNMhtPJdygqH3S8RRQWCj/j6bOPc4Vn97Jbi5Ef4f0WVnOp6TIgrWyHpJxz7OARViO5PYYsXyjLAvhV6bhSY98ZHC+KgRQ+aL4JgD3pvU+RPGF65OGuNt5RM/2k3B7NLXqVIuOzomz9eXGL6lb6jz493biJCvQArhCWRtiuPc=
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
