---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-s3-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgCBobvCJokIVa7cskO3OTe2/C1TVoT8fhb1mdavx6xfM94D88s/jXKAHORLjkzioqxqOYNvDzVhFEpxLjmptjAEhikwvGdfNJl2ZIJwIc51O08yvW02WOGUCoI25tR7zLviIoCRD/y9elNm0vq+0gCAPy7/LzmHVQ4tUEzxdwh9X33qFvF223ZAMG5kiIWd34Cz/qAftjfI6usW+hFUNClCetCjB1zfB7KInKvGyZOfpStlLFKF6EfkNettX3ys+YgaJWObu3Y8xUiq8h/vBAUUW/vVCcZluyAjqbPzzta0BMOU49TnGgDsEm5SgIc128elZ/001iB3ZFJDICJI7ogjHvCDidPk9gQHEKqJkz8CpQkx2cd847WCuK78yK5HTxMLn0Xv46fGMKOGmw8AHP/XtvDiXHTO3Lm9+Z16KgQAlO7FAQPIuqR1qxGMj2VZ2b3MM4SusuZwnO7gUE5mjFJ95M+vZEPnu3dkVOnMEogNRjpuPsdv1h0ntHp5m5poenyhDU9ygODnDvec1nKLX8fYLvaE5OiwaOGVRD7nUHPKJWSM4XNdZI2nu8cuOZwE5HMlrgrR/seS+pfpTRnebjk8WpjjBhneQ3dte5XDOXHK0NBoWm7vTk132F1TmXlo+MX/mJLrRliU8YcqtkCn+X+QWnQ1TIxg3nbBzWabd+/w+zOgkv30Ktzxp2N0AnCHbMV+VKLTDWdV1xk1OtaKlaom4JVU2Bg8heSsSilDuAw7HlBL3WlaBUZfzyISa3/IYL5aRABBD7DnXWLxNwZ7iJpKz8FZ1/gu5Cb4AnB7pvNEL+LzHXYekCunQ7YruPMYArlRyp+x5B98sfXBBpMFzYEBYcmzgK7OGWLqjxUcZ2qUqb2EnaP8SdAWFBZj35B1l7xPAK+guuRzFnfV61+0j07bULMzrgEBM7/3sbCSTzcLV56cQrl7X8bOVrisfKxiEOAiZV6qd9M=
  template:
    metadata:
      name: gitlab-s3-connection
      namespace: gitlab
