---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  encryptedData:
    email: AgBU2AHrcWies7bvOCv7fWeqWvi2xrczDpkqIYgAOZ6Zbo7JuCgPwrcTHetxBJpTIYh2jtAfbIQUINcHZlswFP48x66jUuuQyA8OmPqbM/bRuKdreBFqY4lQRQZmFWxyFwxrsboiUl5tqejX07e7+RMa61OrSEm6SOOkX2fLjxZB+FwBLvgLDNlRpFg7tfUjacpeH8pBdOSbYyr00IluQ3Tlhrxj9TPiJfVU7yGEuKZ97bfyxcieJcMLGWTYI2nomo9I4QOVE0aOzLhC+xdeYCh3Gg1DQqNqfMEvmRXyW2cFAg1OHLVCgvXL0MFYdWQRzpu8LHAnbBxpng3RoZHz2pfqj8FZMvDIauy/xKW2l/ZsNItzOSNu8qQeMEqQO9/pU8BS3t8SClXAUyLAPOBa05buBPWWHXCkYcJpdpzUT0GBYzAL//F6dYjkJEyr9qTQCruoTIKvb+3YPIcel6J7eaqbzUsL2nJWIPgjFm2Y1ZASyD/2JjurViGk1YqsqBqRCbCyZDfgu4THUgXdRC5pBzb03DQnFJlii2Yz69rKAKFkGR9o0tZOjZHB2OcQh/IPuKxqOVsd/JVeKyGpaX9opgtuqexDDKVA9r5LxeVQwn+k0KhtKf6vroFPaUcp6ZG6p00ivakQ+C87lOp767hudi3wFHpPuvzUaLKTQpeE5iDB6xJnvWRRPkyUaIO8DhLG4z6G38tCsLiHn29Wq5XIx2DZtTVhCA==
    password: AgAoDG8ijYCCW5waH61EaxFewnT0SZrCP0PrrobKjqzb9CYVFVMz0vhLJX3CX1C0f+ieYvmNrYvYzE3/+xNo3W98hxEvu5bnC1x0XpgRfUpB6NFKk5TiKrZadZ8GGk0ZLxMwIkMsYCea62VgdMhPZywufWhP6Dt3ZlsJDKz6d7gqsv4yayOof0g+6BATIMAI/IffHmrAv3dJC+raajwvaU8yPx/RvmsmCXNMxAwHHW9oO/QJAFZ0Ci41OJpYM0Jhfe3lg0pMFpz2P7OtJtK4TIGGRJI+7LFu6LBaEnbUAfpk8OVlvGQ92tut5cLoRvk5vG+62R8x6FEieDxJCEDgURwiYm0+lgV9mJqoi0OR/ePK4kyhc0HZiD1tFKxE1ChmoH/YWFe7n+S94vSN/EPISaATHSvLrDi0mNXd0yUCC0zwQD0w/EoPnmdgRyrxgwV5kO7wbhWuJ8q5D/WGlGTC8lRqH/WoAyJ11tddf91k2crLRA+PvUMNQj5h3qJq95NconS04bAmkFm/rWGTV5k04WELO7Pf56B73rBr89/i3NynpT62bI2vxcN0IxayYwkIAGA37VMK9PS/3E1YbjGrQ7ybznmBNSkhda79VqA37a/5RjWTpxasmOgyTb/Xy/XTqZyMmSYGo8pSplZSmdCo1NQorXGtJlEmNNhYpy4spl3JKBLERwA5Nk32vjIvfbbgWX8ZQRTRQEmd0H/YIB4kazXQ
  template:
    metadata:
      name: gitlab-root-password
      namespace: gitlab
