---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgAXgboVJjlJ500C2xaBF8Pe5FylSFNsSIJZ3j7NkkTGDtwEi9GJZFxZYjIMKsbx36ApsEVcKEXpJGRTpmH/7BUjA7IuCmT4Or2+SvZsyyrN8iRiSMkQ+/h9r6MvQkyNpNGouWxTNg7QKnDj2VsI9tUDycwBaoYtfTZPAM6EXAskYrQF8jbETl3obMHz3s9TU4wk7UJ7+7oDLXgSy5A6KfKp92KvWt4vjH/pg027iWApTQgzpr4ZcJXmi4CnRDkPbGtFJXtHHW01TtkSYi0tPRqGb9kF6ezAdTdmTur8+gYysMek0JopiLoSvYNLTyI0pucKSqrJJcm4Gt636ioRPS3jLp9r9K+6N1yvwJsElvP9fO5hvSirDJWkUPjNyE8ibYFMX3CcSPK+FxzrHSwPjQ796CuM1IfAEtEn8iUngDHY6H04pY2j4HQnHNU/uvwI2TJd9fGTkc8NfgcdxHoKti/CYwVAJodrI5Ep/YDjMZBzdJI/N0vneE4q/L/pKSelrHVmTCV3brASGbaMWZUa2pElquZediar+M391raAt1OCDC44W02WWnzXokOHKpzlKKaLar+q4oL1paPMZK8snuK4p+eBKGUyKOnoLstBhgCgJhbZ8BgIqMeOAmwHB6+sIsjqdIQYTIB0Ic7CVmUZfPEqnMsCofdkCvsmA2eDp1kwwdv2AHYJh2s7sV1O127wScm3liTRLTFst+F5RCXgVOnEan4BNUltVOA/ZS9X4LI0H8quiQ86cul+xQJ4oXR9BByST/u9FyCYBRHe6ECPfkqEyGCTQsl3qfBvrgGnWYEveaRNM317yhtRBqSXvh4sM0fGL6gN252uOH0B8yfD1648ZKuSnnIqVLaR/mqRzZTox2xT73Z1ypH9ad6L8k/qwk/8xqqd8EHA/MiesrH5KnNsi+wGNx4X8X1FHpbrkhFlLS4Dw+CXVXywIlQKu3DxerDQsGQSgMWrIltdcRScqGVJRoQhy0ciOfSeqSkHKJwumh2cBVtOdFx7xefAnzNPDDM=
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
