---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  encryptedData:
    email: AgCW5e6yj6AAVtDdxW8guuIKfwIpTY+cZSMu5xsyyp4kncxICz5eV+Vpu66cAMV/F8KtUfDjbMZqIMvr7A0VwVor2Ff5TZyqx41yh0K0HnXXGbna/lUjZIgnC4Ho764zTqCI6rx56clocQTGkxkN/w5US6PeRcYPZb6l7EbRAx+b4/MzhUGUhnraqzLHC7Qs5mkkOVOWidZPfkAnNCHX0KZv4yNRHlQgT1cGHwZdCGYPWwvxUqArb3QMAjljsfCTl2NhtDDCIl/E1VPbVrFbOu02L2sNdIBBkLEbYC+EQoro+phVQ70VOPR1o1eTwigjzcqUUtd33XcRP5CzH3oHqCb+pHns6+nPsX9ESd5vwWLWd7HW2CuEB7ZKGS0aWTUGMrnh7lX8hrusawyMGMJCT1MHoS6TN6YiQZmOh3vZJ3+a0nIwlDuEFi2UEC6yl//A303iaBzMTSCxPgCy3c+eShmi9DQwkwiGdxsgpM/zCM4lFHkCHcG6veUTPzhkQQQFH6IrxNVAayrsLrBH2KNZtj4JO4B8VH3VMG9bvjLwMfOSrLbVjWwMdflZkjMG1SiTX0ZMpiXttNEPePb8z9KW+BjycAQpa8s4ZHBNFuRaYMTQeucG5iPDSaaHzxaGMgndVM/BrF/hzcTgs8UAV1/eEF9A7OjqHkpPvmg4HT+IaOzPQ/9MKYaO+D83eUVrxYTbcD6k9NehIA3WuP+ddSZVesRwODNJMw==
    password: AgAxV33SvAvpVlCEXMg8ygvcshFxsW9foizVrPULKDn6WM15Dq7rqCNS7gnG3Bx9LQLecaNf69e8+urc8RGVj3IgmYaVn+kt9WuvHK6iEfwCfLjtJI3m6GtY+dU6huDjQtlrMWEe/40n3ln5pCSvBG1dgnLaWTWswbS5i76gCuWHO4Nx857x3gBosEX/nDZrM+dmSiE7f2grC2mkH735R/NrTYwIDaq95LptDvjxhsxF/2ND8JD8Uh8pN+ifUMx0WUxXMRQBgN4LZxJfWPDCwFvf0oKTKIgyRBUTfqbeKBsFPO7vXVbexQutGpwc/4WptqKr35jgFAuYQfTi5l+YX4X+o1LPICvBr61+sWSN5jYAEfHZH2zzNEHtpYR6Tvsir/qjwSeXiG9g8I6ytecB9BhERrYbSPG8ybLJWgbwESxSahwqQfi4hrSJsMjqczEFUkjqf9fxSRJFnPMK3CK9clkkpu6fXX9uYp2nOELr1RsBv9n7L9HbGWkg1Zb06TJr9bV3+zBmDS5uXvTEOa8/5fFPwqG5UsKYO6F0DBG7N799N9MQ5dw/kZPbCm0kI5t8JBjLq0Xbu7FmJ+OWXM/Ac54/+WPk93TbQLBwaB01JzSKQF0USzAb2lr+UttDsoY36KwpxMzagFm8XeFJ8qThL05LJyH6wjtEqwmk6djqp51iJofJL9quf6To8LFNLAGLWu4z7FYlrlWTtmgUIs0UVBkN
  template:
    metadata:
      name: gitlab-root-password
      namespace: gitlab
