---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.clientSecret: AgCJC/le0gJ9giJq/G2eUdM7iyg5XLAUj0GUpG2p9JDyqdrW8ypDpa5Qcu8AA8j/WINXAP9eVK0aWYwXwfaHncI8Var4B2LKDnOoP36mXdx7kfT4++qWX7FkTlrmhQI6Rg2XvyvooaZ/uar1f1gW+4ROy/5X76JZ7Kv+Pg9ZfL5/XSpjwGU9Axt/49r2Uzr+VYvOqQ7wvN9JlH1PTpC3GgW4Og5hHjT3jdlqCVdHKFxO9xJYUvVuYBbb+aN0/0Y07BPlil28/i2jY7i0rayac2zG09au/x2k8OpsdEpTGsul4KoNr6BiGFtaps1ZKQLNm+dG7JrFsCG/GnVKyqLsys2o2m7sO+F1Ikv8DM1v7qFVqdUkqQkViJEwpAuvLkDxWvpy47PYmeWN/nDwyGsWV5UiObrqr1Th0QSUCAtIOB8lELRH24nQmJeJriFCHK7f0hBI5Ek2MvtF+mNIm3pJlKjabOq2qNsw4uH4iyJ+RlP7wzTlz399PnhJgsWtCkJr3UVlnAWomftXHnZYiLdJQIWiP74oeWsVU+bMq2Nc65aEqPI2iiu6kfrDYIci1f3P8XLtZYKXJv/fJwh4iZwulgDJYE9I1WGhbLqXv5Do6xEJXS/qFI36JjrQygZl0w2dUZNBRoPTWfxiovo4yWil10CUK30+oHkR47BgraQ0/XKQv7GVPhF2Yg/OCr6LsJyvJUKjuf5IoJ0NJmsGLKvZptHWFE87ajLvJs71WVTp9WXAhJw3xOfYDphEo4vK945j/kmSDZ0xTeyoVc1jfVEuWQYi
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-client-secret
      namespace: argocd
