---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: prometheus
spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: ""
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: prometheus
