---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-rabbitmq-auth
  namespace: zulip
spec:
  encryptedData:
    rabbitmq-password: AgBIL5/LqigEsIG3y2kdcoCYaf1Kg7elY75ujcvSk9ES4G0e3Py8lSDrEr6quxbVdqJWMILa1yjvq0fRbJG8tX3T3Bbgui3tao751/j79SuUykBKfbx576Em4QR1l2/4dGGuNUf86yruj35D2k/WH7hUFsBO2ty1D0BdeSd7Y4K5SLuEbbdOErHovsD0N7FPPkZzyTm8fI7sFkXsi7KP1vuM+W5tUzQeVMr26gCBzw8QA4wSztkhoEKDUwjsG+NgCYzlDbmjT+gtsC3vjann1WSfA68ThoDAsOxnwE/x9FFtk0Vr4C3waJjJU8q8vnhM1eqt8NJAunQ0gIdfkUltbBBchp2wzWOhCwXW1/Hswxjk23xkizmsFgaAQXSYHiSjUNJbUL/lcMFYSoXbhO+3ZpMwcwi/CIqRHKrgWSu9APplMDyI+pNHiXr2B+zd/jOBkwGBk/kxuyAw6UxCuP8RRfJ0/ggqMfUv8uSHj1SrXR16xb5ywPgr/i2YOWv+qhr1ZmDOs8ooZ1d7mBKMxNKwiQch+rtuwKbVDYXIefFapHEqT7oLACyjpBg8w8Wlu40M/fwhYzblWgfwP4G0NO+Rj4tfROWMdlLbubwsyFey5UmoZ05mSHOO3/iaRAzmOfXLn98raIjLLp4uvkxrpEKoHgB2TvQ+oDZn/brR1KX6ZzYMlvsvZfW0H69yXlB0P0EEvdNYWJq52RwZqZVJyoQyGMtMgXxYB6TP8mthi2Sy3AjmpA40xR4Xttqhh1g4fNjYSnI=
  template:
    metadata:
      name: zulip-rabbitmq-auth
      namespace: zulip
