---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-s3
  namespace: zulip
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    access-key: AgBZSvmkSDfpPjFf3LIirZ9sbA4LGSLtooNU3x/JoDAN/Ipwj3pAToYorkvnkKuw0ReIGHDl5iMdoooZwCfOaqDPY+2EG3A5A0X1zPwcCvhKM5MoXR6Sa5P37c4J0jvaHB4iBP9TA6itVEaR6p9oNTH780MXr3oAufWGXNzLNvbpWR84uHHIUEInfrpA8q3vCEaNm2HPnr3gvb4c6ujPyddRAys6AP7Melei5UWDZlEWZy/ENaFWKke/L6nF/997OE49xNgN5wkgTAFYJulfRLovkT1BNpGrvD1h2BRmqSSV15nV3YIczWnpZoRgm3j7JUdKiWPpH20zQGnNj8ac/tOZJqVOLG1ScQt/4RxPydJ3rE1Wd8QMx/nrwjJobBfGQXIStRnto9tLnjTSDiHMGfFXGsPR5IH971nkrAlaD2959oN+1uSSKVjtlZjJzwbqcMhBgIzMRYJTdxrZSTxgliY3tX8MfmGPLyN6QoMZxxPIORg+msIkTiwad7Www/DKXCDP+hqbauUpacPAHVzI+SgnbkPqUBMjP6syRF3vvNxvA3N/L84dZSPmR5tmt+rF5P9s+OlF0JDvVFjNmeU+N4GAUoeqsAlVjjYFK2iFOne6OGhEB7l6q7kw+uKC718xy3hoiLzD/d2lJ3wWAnIGhOcGVpgzgIajdPPfkZcpMMIRl7wBlkfEtG2D34dmOnE3ESxEUAXrOE/j3HXT+BP9c043ZFRuhw==
    secret-key: AgA34RYxa24DjDTxBWSjKTe+3/z1yCU8samgdOVD/nKxAzHLQI+A/uq69ofjO6bpQDiIDcgYjIJDAS8leQeB2YpwGsL3lQ7PVXugvQKb92wHnWh8KlSH5f0O3ArsNhdbnd80PaDBqfRNSOR+Mms/pAn44E5tl9Rur2zf7egEvp6tOCAXfTHYqspxq8eC4gv5VHnGzaZWHH/1HMuOJFpqZCvKlOtaA4Z36PoQfYW9jL3q616cr2G8UndQybAD4DRgz3bG0ShXCPptpJPkNX4qnohH//Tn5tLfFRknPy5OlsXTb624sDZMAIvebEFS72R2btwiUMaVvhCO7+6rpmOuu4EdhLP/ZjNlN3C+k0UTSj1wEuS21jow4KCDxnDHe99mjCo9lFtIO0C/QQhf0oXvDKAOE8mmprxlBP9PxMpD9sXusg7xJW4gvNZXh9V+V5ewFbec4nAMmkP86wFiI8RuW1z42NfJq80mQnwz1EL0Vkw6x7rsWOGDkrzu2kOuS+2u9pFIuOwe2XQY6Rdpy+us4bYpfd3LnJwez+NndP5c4PkVBZoXAEeHqmWDnnRv53yzPwV3tEAts5P18XRpMRT12zrZHtFeAHx1DpHj23cpUzgP+ZIROhTNH/6q9HYafLSmc8Oty6OThcJprE2Cq4u/K/WDDvMHMog0LqDJQ07vvFu8ANldlp1HT4Bcb0k38GNWmsVvsiORE7oWLEy3Vn/20jHsYSVBoOiERrrio6JSQ90NOBxyhqwOfl2O
  template:
    metadata:
      name: zulip-s3
      namespace: zulip
