---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-redis-auth
  namespace: zulip
spec:
  encryptedData:
    redis-password: AgAhIzkgeQ4DDIX1myUnVAURtqoGSjPLOXjVPQRmxIHIZZKE7iT+QDclInGFSGep8P3/RB5DyyC2MzlxwnKvj+9IaMzwv3t62wTJtWOne+ptKI3cY9aHscLhao/M6l77++mhOTGgy+jU3vCh4u6D8Rygc4mP75IJccKII2JXtlrIpjvckcrofJh/wbYW4C/Ow9HZTFoNVIHxO/QXg7aH2qAhxYnQv/eyY1SSmIvg+edZbn01dIEi4QavItjoweU96JBD59OydkkPpQHXR9ZpvFktqFuPKuxtDgDKQrTNE0hyaRml4pYaQWhpWq8LFyy0g4KC9l97yVZ38BMHJkA/HTHQuZIiwZ8HRuiF5VQ3QSzr1z9eSsBtjjVClelghI7BDSNczNQSAaThVGJo/0HktvbFbPBVGxAsMREmOEr6f0giGeIQFgtJQIgVrTwVXhIbn2ML2DXdMpVqW/JSBbpYbm0JSNxcZy8uV4RBaMu9CCgjtkRfx8ixEOVm8/PHV+6s1dTYwKmVD7VtaETtvyPBGuPb/2CVk01dwRKuscMcncRMQX7Ce4OF3O+D0es/YwyrwA7ULEi8vdwXPLMZE8k2Sfy0gjUmaT2rvzAVBdaxdst95ykws17VCWdRJ1jALzsRkDKJs/rE3EwhiJ6q+xKOK9SsAaV3E37CgK9aDFhuSFQRQkcb2Mb+LbERgJHCP/tdZqaAFXMtqYyNV3hw
  template:
    metadata:
      name: zulip-redis-auth
      namespace: zulip
