---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-s3-secret
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBfPkjk913ft2i1G0uAepTDXUiNmfO8tT6jzcLLzHWZWxrbtBGQ2XWRqm3T9Rjs9dL+Izi26EkoItA/E0maPhE86irLYRKoFBkKv/Z9b1fLix/1pkjMFcvQf47HoIGlHs3ulSD967O2rTDZX+Y/vzSg/O6Wf9p4ZbPrn6G7viBzO8n4JTFERS8ARO5TpKRvPF+/yBDGfgv8juuRWv1g24Cfl5n1/7+npve9QjfOlxkcthX3V+kB6he/xM1nEl/JGMc7WlNf6Hry0GuZl4XuUQKk0hkOg01sq9yTuJr/LlBpdwAI1qCkIMmV8xREuunt7AcitKY4hMbpfqT+BZ/YKmjHl/CQY/kCkFLdY3sZkwJeV19om4FNlJK8rct2fsIJar3NPXzwO/7vhK1sRN8Uhs4IMAPB8oigE3Et0V49rHE1VQoXpr+Y5ULtNa/zdYbLeJdpZAQFWWCV2hYgfmswf99IXUpoh3Z7M/Q2dplYftlAeg4WUYPHiwUSmNl63o7cfaknGsO5yfMKdeiu4//84VdRGtmURD2sYl2aJs84ej4ywLP7P3+HOx2lk0akVYs6PgChGqiSMxrb363JBx6lz5WCCR5r3UaNdfHUVyit5dVQwoNBGTElsUEsjzHwi4S+4t1Xv6BQInWEep4j0hHBEWDP5q4sjZ/qr+tlngdWbTNipj0CP1SSr4UAJFlCNn4lYb121t3nv+4P3/OyHt21KABOZJqmbw==
    SECRET_ACCESS_KEY: ""
  template:
    metadata:
      name: authentik-s3-secret
      namespace: authentik
