---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-pg-user
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgCdzOiUuvlsQXlZM1u2XbuW25FNuHaPGNroPDj6AOKa9Axauw+bmJeNynmPL+OSVEFHAuWI/urpXrV58NrZEG+wn2grxKrF6o2i16dzvqSHDdRPqdYvCOZYVNmP4d1zMX+278j5W2wwHVZwt1eGD+hFFPGsRoNTc39Q8vTAxw7vuWU4tqXs1oSk99OAEhBM1tcVph4X79oMCkqgFaZDVt6efnvd2nRnblqpeafcZMTNJ+4216W9Adi23Sj80zL2zG+U9SGZWZ6lnFgS7W7yc5peYFL/bWg1nyf98isBPOEaAkqqqBzkz/U9tZAx1o4PGrmwjexKFMdDow+q+4h//0jrvB78vPGAb3ZCreYfkbT+uXnKF7sbdRLf8moI+oa6O89LTD4E2VGIwa2dSPoM+GU8Es4dG/SbVKtHf7SkxeJssSPk+4GAAqrCJHFygBzN3t0NIZfcVHewjDZQr7Lwhrh4W6VGSkIKCXAt4KtSyo7/vKHWBDpdg3naccaI8aE8vghaKsf4hxEGHV8z3JQ1wnbGMDnvFQRQUtmYNHEETNnfc1iudet6k839Myjay8TPAZ79hUmcf476tU4jFNAHHCLenE8Lw8Kb7/KEmbxkYk2oXpdSjsANNUw2zm14N0R1AVbyatwQkZlqEkgSKwk+20xIq/+49gJ8j86ss+E4ADzH9fad0W9HR4a0xmu1fzwzCIR518wHCMrnQvnJSTu/P75pn7bfrWe40zlxkcj7I/9JSJaavOZDgaHZJHwT8lSu2zs=
    username: AgCCCWnqxJLjC2+Cwj0l1R4l/SIKcjXm3t8SEO1awI5j3qL16FjQAPp+daEOe6zg7hsn8mBTOjKuT06R6fOZWduYJ5xXp2Dx8W1lowJ9Y5QDVJRa9fDGYvxEOJmhzE8ErSqBVnYI4M+p+5M7R5Sn+XwhllIBp54ZvVLsXrnmcbXmVkKNIkRx3yl5acySqTSbTQnFAXcQW/qQsaskWyZ4DOYPsXVSDPuBoAP6QJ4WoxENN8UHslEZKr5E04NeOxhQJIOjV9SXYtNB6NjTbcKa2UJ9KvHvhEMiOAUPq0jzPXlS1UgnO8m6BfUrnq6kI6sMyIbdt7RB651Nhl5b5afEw3MHBx1YCbK6Yp3sIx4csM5joVUKuo2m0QphbX674kaYuq9jTcu2pKDe81YlUsOW8cph93H47yAtYfQD5RpH8GcFxHsGcZ6JZj7J2GWirnSKA/SfWX1fMavOZ3kfdQoKQYYiKq8AiWMBBG9y2LziJ1BmpP3gYsIMRAz1iJdzJYmc5sPvONWx/EzF7PV2Tev299agRZa7yh8mvvhqDgIcChF9MvgVDrrO0pckMD2Ysb4dDGtuPFVpWlsRdIlKxLIZg92YCFft3anWDW+xCLpDl+FD7Ges3LMvceS6F126wuTiOckDXr2y0KRAeCdKaDc7E7+rudySS19MZmNY7YmDjxmvDog5sLEMKQv5EfM1H6GLmK1sNz55KFs/B4M=
  template:
    metadata:
      name: authentik-pg-user
      namespace: authentik
