#!/usr/bin/env bash
# Seal a Kubernetes secret for use with the sealed-secrets controller.
#
# Usage (direct):
#   ./manageSealedSecrets.sh <namespace> <secret-name> <output-yaml> [--from-literal=key=value ...]
#
# Usage (sourced — provides ask_and_commit_sealed_files):
#   source ./manageSealedSecrets.sh
#   ask_and_commit_sealed_files "Seal foo secrets" /abs/path/file1.yaml /abs/path/file2.yaml
#
# Examples:
#   ./manageSealedSecrets.sh wireguard wireguard-ui-secret wireguard-ui/ui-secret-sealed.yaml \
#       --from-literal=ui-password=mypassword
#
#   ./manageSealedSecrets.sh myapp myapp-credentials myapp/credentials-sealed.yaml \
#       --from-literal=db-user=admin --from-literal=db-pass=secret123
#
# If no --from-literal args are given, the script prompts interactively for key=value pairs.
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared function: store a secret in the Pulumi stack if not already present.
# Idempotent — existing values are kept; never rotates a live credential.
#
# Usage: ensure_secret <pulumi-key> <generated-value>
# SCRIPT_DIR must be set by the caller (used to locate the Pulumi project root).
# ---------------------------------------------------------------------------
ensure_secret() {
  local key="$1" gen="$2"
  if (cd "$SCRIPT_DIR" && pulumi config get "$key" &>/dev/null); then
    echo "  $key — already set, keeping."
  else
    (cd "$SCRIPT_DIR" && pulumi config set --secret "$key" "$gen")
    echo "  $key — generated."
  fi
}

# ---------------------------------------------------------------------------
# Recover a key from an existing sealed file, or generate a fresh random value.
# Idempotent — preserves existing secrets across runs.
#
# Usage: recover_or_generate <sealed-file> <key-name> [--regenerate]
# SCRIPT_DIR must be set by the caller.
# ---------------------------------------------------------------------------
recover_or_generate() {
  local sealed_file="$1" key="$2" regenerate="${3:-}" length="${4:-24}"
  if [[ "$regenerate" != "--regenerate" ]] && [[ -f "$sealed_file" ]]; then
    local privkey
    if ! privkey=$(cd "$SCRIPT_DIR" && pulumi config get sealedSecretsTlsKey 2>/dev/null) || [[ -z "$privkey" ]]; then
      echo "ERROR: sealedSecretsTlsKey unreadable — Pulumi stack not loaded?" >&2
      echo "  Run: source ./scripts/pulumi/initPulumiStack.sh" >&2
      exit 1
    fi
    local val
    val=$(kubeseal --recovery-unseal \
        --recovery-private-key <(echo "$privkey") \
        < "$sealed_file" -o json 2>/dev/null \
      | jq -r --arg k "$key" '.data[$k] // empty' \
      | base64 -d 2>/dev/null)
    if [[ -n "$val" ]]; then
      echo "  $key — recovered from sealed file." >&2
      echo "$val"; return
    fi
    echo "  $key — key not found in sealed file, generating new value." >&2
  fi
  openssl rand -hex "$length"
}

# ---------------------------------------------------------------------------
# Recover a key from an existing sealed file; fail if not found.
# Use for secrets that must match a value set elsewhere (e.g. OIDC secrets
# generated by authentik/sealSecrets.sh).
#
# Usage: recover_from_sealed <sealed-file> <key-name>
# SCRIPT_DIR must be set by the caller.
# ---------------------------------------------------------------------------
recover_from_sealed() {
  local sealed_file="$1" key="$2"
  if [[ ! -f "$sealed_file" ]]; then
    echo "ERROR: $sealed_file not found. Run deployment/authentik/sealSecrets.sh first." >&2
    exit 1
  fi
  local privkey
  if ! privkey=$(cd "$SCRIPT_DIR" && pulumi config get sealedSecretsTlsKey 2>/dev/null) || [[ -z "$privkey" ]]; then
    echo "ERROR: sealedSecretsTlsKey unreadable — Pulumi stack not loaded?" >&2
    echo "  Run: source ./scripts/pulumi/initPulumiStack.sh" >&2
    exit 1
  fi
  local val
  val=$(kubeseal --recovery-unseal \
      --recovery-private-key <(echo "$privkey") \
      < "$sealed_file" -o json 2>/dev/null \
    | jq -r --arg k "$key" '.data[$k] // empty' \
    | base64 -d 2>/dev/null)
  if [[ -z "$val" ]]; then
    echo "ERROR: key '$key' not found in $sealed_file. Run deployment/authentik/sealSecrets.sh first." >&2
    exit 1
  fi
  echo "$val"
}

# ---------------------------------------------------------------------------
# Shared function: seal a Kubernetes secret using the cert from Pulumi config.
# Does NOT require a live cluster — works fully offline before cluster creation.
#
# Usage: seal_secret <namespace> <secret_name> <output_file> [--from-literal=k=v ...]
#   output_file is relative to the caller's SCRIPT_DIR (must be set by caller).
# ---------------------------------------------------------------------------
seal_secret() {
  local namespace=$1
  local secret_name=$2
  local output_file=$3
  shift 3

  local repo_dir abs_out
  repo_dir="$(cd "${SCRIPT_DIR}/../.." && pwd)"
  abs_out="${SCRIPT_DIR}/${output_file}"

  local privkey
  if ! privkey=$(cd "$repo_dir" && pulumi config get sealedSecretsTlsKey 2>/dev/null) || [[ -z "$privkey" ]]; then
    echo "ERROR: sealedSecretsTlsKey unreadable — Pulumi stack not loaded?" >&2
    echo "  Run: source ./scripts/pulumi/initPulumiStack.sh" >&2
    exit 1
  fi

  # Offline idempotency: compare intended values with the decrypted sealed file.
  # Skip resealing if they already match — no live cluster needed.
  local intended
  intended=$(kubectl create secret generic "$secret_name" --namespace "$namespace" "$@" \
    --dry-run=client -o go-template='{{range $k,$v := .data}}{{$k}}={{$v}}{{"\n"}}{{end}}' 2>/dev/null | sort)

  if [[ -f "$abs_out" ]]; then
    local sealed_current
    sealed_current=$(kubeseal --recovery-unseal \
        --recovery-private-key <(echo "$privkey") \
        < "$abs_out" -o json 2>/dev/null \
      | jq -r '.data // {} | to_entries[] | "\(.key)=\(.value)"' 2>/dev/null | sort) || true
    if [[ -n "$sealed_current" ]] && [[ "$intended" = "$sealed_current" ]]; then
      echo "Unchanged: ${namespace}/${secret_name}"
      return 0
    fi
  fi

  local cert
  if ! cert=$(cd "$repo_dir" && pulumi config get sealedSecretsTlsCrt 2>/dev/null) || [[ -z "$cert" ]]; then
    echo "ERROR: sealedSecretsTlsCrt unreadable — Pulumi stack not loaded?" >&2
    echo "  Run: source ./scripts/pulumi/initPulumiStack.sh" >&2
    exit 1
  fi

  local tmp_out
  tmp_out=$(mktemp)
  if ! kubectl create secret generic "$secret_name" --namespace "$namespace" "$@" \
      --dry-run=client -o yaml \
    | kubeseal \
        --controller-name=sealed-secrets-controller \
        --controller-namespace=kube-system \
        --cert <(echo "$cert") \
        --format yaml > "$tmp_out"; then
    echo "ERROR: kubeseal failed for $secret_name" >&2
    rm -f "$tmp_out"
    exit 1
  fi
  mv "$tmp_out" "$abs_out"
  echo "Written: ${output_file}"
}

# ---------------------------------------------------------------------------
# Interactive prompt: keep existing [k] / enter new [e] / generate [g].
# Sets global KEG_CHOICE = "keep" | "enter" | "generate".
#
# Usage: prompt_keg <label> <has_existing> [allow_generate=true]
#   has_existing: "true" if a current sealed value was found, else "false"
#   allow_generate: "true" to offer the [g] option (default), "false" to omit it
# ---------------------------------------------------------------------------
prompt_keg() {
  local label="$1" has_existing="$2" allow_generate="${3:-true}"
  KEG_CHOICE=""
  while true; do
    local choice
    if [[ "$has_existing" == "true" ]]; then
      if [[ "$allow_generate" == "true" ]]; then
        read -rp "  $label — keep [k] / enter new [e] / generate [g]: " choice
        [[ "$choice" =~ ^[KkEeGg]$ ]] && break
      else
        read -rp "  $label — keep [k] / enter new [e]: " choice
        [[ "$choice" =~ ^[KkEe]$ ]] && break
      fi
    else
      if [[ "$allow_generate" == "true" ]]; then
        read -rp "  $label — enter [e] / generate [g]: " choice
        [[ "$choice" =~ ^[EeGg]$ ]] && break
      else
        read -rp "  $label — enter [e]: " choice
        [[ "$choice" =~ ^[Ee]$ ]] && break
      fi
    fi
  done
  case "$choice" in
    [Kk]) KEG_CHOICE="keep" ;;
    [Ee]) KEG_CHOICE="enter" ;;
    [Gg]) KEG_CHOICE="generate" ;;
  esac
}

# ---------------------------------------------------------------------------
# Try to recover a key from a sealed file; returns empty string on any failure.
# Never exits. Safe to use with [[ -n ... ]] checks.
#
# Usage: val=$(try_recover <sealed-file> <key-name>)
# ---------------------------------------------------------------------------
try_recover() {
  local sealed_file="$1" key="$2"
  [[ -f "$sealed_file" ]] || { echo ""; return; }
  local privkey
  privkey=$(cd "$SCRIPT_DIR" && pulumi config get sealedSecretsTlsKey 2>/dev/null) || { echo ""; return; }
  [[ -n "$privkey" ]] || { echo ""; return; }
  kubeseal --recovery-unseal \
      --recovery-private-key <(echo "$privkey") \
      < "$sealed_file" -o json 2>/dev/null \
    | jq -r --arg k "$key" '.data[$k] // empty' \
    | base64 -d 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Shared function: git add / commit / push a list of sealed-secret files.
# Usage: ask_and_commit_sealed_files <commit_msg> <file1> [file2 ...]
# ---------------------------------------------------------------------------
ask_and_commit_sealed_files() {
    local commit_msg="$1"
    shift
    local files=("$@")

    if [ ${#files[@]} -eq 0 ]; then
        return 0
    fi

    # Only commit files that actually changed (seal_secret skips unchanged ones)
    local changed=()
    for f in "${files[@]}"; do
        if ! git diff --quiet -- "$f" 2>/dev/null || ! git ls-files --error-unmatch "$f" &>/dev/null; then
            changed+=("$f")
        fi
    done

    if [ ${#changed[@]} -eq 0 ]; then
        echo "No sealed files changed — nothing to commit."
        return 0
    fi

    echo ""
    echo "Files to commit:"
    for f in "${changed[@]}"; do
        echo "  - $f"
    done
    echo ""
    echo "Commit message: $commit_msg"
    read -rp "Push to git? [y/N]: " choice
    if [[ "$choice" =~ ^[Yy] ]]; then
        git add "${changed[@]}" && \
        git commit -m "$commit_msg" && \
        git push
        echo "Sealed secret committed and pushed to git."
    fi
}

# Only execute sealing logic when run directly (not sourced).
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then

export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
CONTROLLER_NAME="sealed-secrets-controller"
CONTROLLER_NS="kube-system"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ $# -lt 3 ]; then
    echo "Usage: $0 <namespace> <secret-name> <output-yaml> [--from-literal=key=value ...]"
    echo ""
    echo "Examples:"
    echo "  $0 wireguard wireguard-ui-secret wireguard-ui/ui-secret-sealed.yaml --from-literal=ui-password=mypass"
    echo "  $0 myapp db-creds myapp/db-sealed.yaml  (interactive mode)"
    exit 1
fi

NS="$1"
SECRET_NAME="$2"
OUTPUT_FILE="$3"
shift 3

# Resolve output path relative to script directory
if [[ "$OUTPUT_FILE" != /* ]]; then
    OUTPUT_FILE="$SCRIPT_DIR/$OUTPUT_FILE"
fi

# Verify Pulumi cert is available
if ! (cd "$REPO_DIR" && pulumi config get sealedSecretsTlsCrt &>/dev/null); then
    echo "ERROR: Could not extract sealedSecretsTlsCrt from Pulumi config."
    echo "Run setAllSecrets.sh to configure the sealed-secrets keypair first."
    exit 1
fi

# Collect --from-literal args
LITERAL_ARGS=("$@")

# Interactive mode if no --from-literal args provided
if [ ${#LITERAL_ARGS[@]} -eq 0 ]; then
    echo ""
    echo "No --from-literal args provided. Enter key=value pairs interactively."
    echo ""
    while true; do
        read -rp "  Key name (or Ctrl+D to finish): " key_name || break
        [ -z "$key_name" ] && continue
        read -rsp "  Value for '$key_name': " key_value
        echo ""
        LITERAL_ARGS+=("--from-literal=${key_name}=${key_value}")
    done
    echo ""

    if [ ${#LITERAL_ARGS[@]} -eq 0 ]; then
        echo "ERROR: No key=value pairs provided."
        exit 1
    fi
fi

# Seal the secret using the certificate from Pulumi (no file on disk)
mkdir -p "$(dirname "$OUTPUT_FILE")"
kubectl create secret generic "$SECRET_NAME" \
    --namespace "$NS" \
    "${LITERAL_ARGS[@]}" \
    --dry-run=client -o yaml | \
    kubeseal \
        --controller-name="$CONTROLLER_NAME" \
        --controller-namespace="$CONTROLLER_NS" \
        --cert <(cd "$REPO_DIR" && pulumi config get sealedSecretsTlsCrt) \
        --format yaml > "$OUTPUT_FILE"

echo ""
echo "Secret $SECRET_NAME sealed to: $OUTPUT_FILE"

# Check if cluster is reachable and offer deployment options
echo ""
if kubectl cluster-info &>/dev/null; then
    read -rp "Cluster is online. Apply the sealed secret directly? [y/N]: " apply_choice
    if [[ "$apply_choice" =~ ^[Yy] ]]; then
        if ! kubectl get namespace "$NS" &>/dev/null; then
            echo "Namespace '$NS' does not exist. Creating it..."
            kubectl create namespace "$NS"
        fi
        kubectl apply -f "$OUTPUT_FILE"
    fi
fi

fi # end BASH_SOURCE guard
