---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ryax-admin-credentials
  namespace: ryaxns
spec:
  encryptedData:
    password: AgBEUr/ecBgv8jC80m2zilyak5lnlCNBy6oyjmIw6jgSztFAjsgNgu7XH1+oqEhokZiYBh5kWYdSRVarJoFPz1ulVrMdVZ1v4QF30COdHJEOi6d4r25zTQsey93VCGpRhrHrKZooviIZeFDjE4jbPIv9aBEaLR5DJyrFr5mQ3/2upn8n+d3mVMl0fLI8Z/UWARGZcR9eCDwGrDvAoPviM+/rEETxG4RKOM1qWNoPDFeQqy3MS8ZRPAMj2pM0MJPEgAMgNUgllVrT0D0Z3iE5M5TxK05qQhwakmu+/JG+JzVeq1pzZV0/STIQMGbpnLKdpjHbQFlCMJwpqpeQ55GcNpt284WUR1t6WmyAwxK8dh1FqjjslbSgwX4qWIZLRBg0XEx0xqM4pu5pmIk3ouKkKQA7jQGH3RlFFMGGE1yagJpZntab4IkbtY+T+nZBoX0ox5aip/L6I7sW3N8ZyGzXRcoKfCMfbn/6J1PIIah4CIvOlpeBIQB5zyjH0+7nOV86Qkrf+l1pQdPkP3KjGFClgqgMKV2pjqeHNgZgWxWz/6L/dw5jgrW43C9GSomeeM1+xL1O3WEe/K92RVeZC64G9Ggzy3CdIKmAcBFBgLG9J5tbSKjt+GHphHKUIdXLEEL9vCzvT9adUfuWx43owHNxooqzfst2aUAHfMSXkdLC4SMPHpLb8IV91D8tguk03faxi+smeqONLg==
    username: AgB0o2SVks5Hx1E4uYRh0hjyza0lCWcqNFtogTOjKVNg9vDZ8oJSUHIInsauW/4X979NC0FtWBmPR52vLSjkecjz+768NCv+IpYjgDKPLaE211hE5tfmtDQA/dji48fFV8j0iuiAPizQ0CQ190GCVmxRviXQ7b3m2eRdXaLZ4I1duNPZag0UW53cUjmtf+qzKWL6PdwQehMHIJVsLxupTvyz/DUVchFmlyOtO7Bz/G+Ud4R0JBgHO0MKTCeu5yl9jdREyIM+l+/OKNX37wI0gdZdG6fg/feGi2ZGgGLCCGwUaB38k9LNoexibMhaIArQKL2/pTnk7iS36xb4kgO7n95WG8IBH7F12xAHPSbmbIfMeb8moEH7hIkpBf48DjS3Es++D2rmXA8Uwe8aVPwokRKla62xqayA5y9JVVrVyE8HPDGL9nfEDY1FxA/7/RHsqymhcsqVCwSDi5EsyNuGJNLeLtrMRpAtso6bwtXvXbofAsC1OF5uAFdSaXZHnNcDiHICHMdnxoaNxDzt0ttZo3T4WoECezYmGVOVs7W7lAv7SR/IEp3lu5RNnsBLUdmjCFTxa8EbeSlZEB5y6Mj5Y6bdwsBQcUbUSVeycaDgmTeryqiT7KjoJOmLER0sYAJyyDwQzOX2+/kt+z5NkNgaPMh5dBXN3m6BUK746hkhEt3wpdbhCNd0cQDRGitv8DSKxpnPUCA2oQ==
  template:
    metadata:
      name: ryax-admin-credentials
      namespace: ryaxns
