---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: xwiki-s3-secret
  namespace: xwiki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCX6+bg6EV/IhTaKsvmkt5XHeYH8RyPwVM+enqXCaNVTYh6EBIQWLCHU9LA8GpwPyZ1qo8poPGD6+krnqTouF64OlZqICslKMKLuMQexX9RE9TKWvjVRK7Hghct4rmIj/bZ9YJSBXb9Wdy9lZDltGFyG2oBp+/cZg6fWRr8ThtBqDEOeXs7KWzvBjZve4J5lot3d65fhRwbdk0D7uGExCcQ3dYlOdzXeqBpq9CYHS9X+ukXnwrbMTN4Zsa/O3AeeMUL6EPwdUM5DKpP+xmZ7K4ft8ldOW4+EpXJmbHVnDopSWDB3Uh3i9f6wfrxEE/ytBEeYHlZGcvwMAPdVAjfaDkk0Muz/WHnTUFclJkOM1Tr/psE6Xtnw9kcqlv7Jverup5p9nQqFA3y1e7qlOfA7GN2nFNgMSh3Y5oPwrhc9Rh6bxokY3fe2zPsHPce3tgyMyJTgp5+1r0h/IhOVcdzpoK/x9sjoIXnUjEQqE3HkURo4n+loG9dFlmV6RhsmcHV/Fx5X08QgyPlqa9NReMKhCC/QTT64vzEtR8kBzcr5dJpT5KAAivhmeD98hTVHX6uz3H26PVLLjpOs8Gal+eXdMUNGNAI/zhitPk5Eh2L8lell2YCTFFePnQPZb6eqzR1xC6KmD51m+ZtES+UcArsHepsdXup7ZmxO2LafrodiTgWXxLmKdq6QOqRVzm11CWeB5yF8Yx2OOZJDVhHYWB3frBQH3bn8Q==
    SECRET_ACCESS_KEY: ""
  template:
    metadata:
      name: xwiki-s3-secret
      namespace: xwiki
