---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-s3
  namespace: mattermost
spec:
  encryptedData:
    access-key: AgB20w+ZEDP7Pxu9kwbNi7axOam3yJP1+dwlmOOlCqBo9aUIP4vo51sO+nydH3rZ+HXD+QOshPedUtMntVgPX+VcBI46C3LqC5Mqad64ALC2gGfLYIhrbK9dSgBY9XWPJie9NJ+QgvzbkQqOCf3ACL1kvZ37jE4k9H+c7cnJNJqi2SARhB2FpIRqWS4V9os61L4y5xH+JiT6s0RJyYba9em966206Nzi5yxK1V4TlbmA7mzyhO+4qhjfWskvzocpRM/Nrfv5i97g1cVQAMKTw+LjISI9tleczQqMmwCl4vAxmu9bc9uafVyzFugdldBn5g3OqFLIpkloBzwVO8/vyi0XL4AumB2Y9/FOS1ygWnmGAs1KpMo3p9CWqt/jZV+NS5U1ysspxN2kS3Cb0CVX0jDE4rQgIi3sxfEzmZuoM6jgLehuEp6jMgSNjRPNlQ9+QFHVLMHp7D7zbT6QWV/+y/z5ZQWmXc3HMpwus0wVOHH7qL2Lc4TN9hfhTjg17Hff8qvYFj9bs/0RG5fVcAAVllJKxf5cCaaDBmU4s2ir2Vp4Pphnz5ALvCbjFFNfpj6uQwnt54HKERIthQG1oOW9XJ8YMjd956Xrr4cdt4w+KU2lwJkt5S8ntfIi2bKLRbbxeJ58OOBZxf8WWq7x57OXdfS3sqGuoMMD6nggh7uWALuM1Npj/kBNBGtSD1u67xu6zx3+6KaVwqzwAItbQj+PzZpRMaEO6w==
    secret-key: AgCJPU0BxDvf/0M2i2qp+qUnHR/ugl7iE1GPnEW74Kt7CzF23jOVlkPszHM3WzR/2rRvSl6JCAPJpslmr3neHISPBUHwmQE51Qg+6hHXNCUaVZrne9pInaezx9HIR0NT+/xmQJ4umCgXucCIie7ig+cmMsJn3efctW7dbLRokT1fW+V9EWhPLpVVkWiu+ZjjxZs1lilcfArxr1X61TVVmbxW6BP9UptB0rVd12CuKYo6XzcELZPVyUPVx4F/vL39zCpxYxKaZCrW98BUt4SfhaAxUIKIurrNJNTUUAOttMXbma0Id1ZGCWEzSKYjEv65k65aFlDEASH4G4cyFWpX8yHthQyB+IyHe22LJtCTndHXFbQgaJLzpJALC6EKbRs31fkDdj8PPZuXFlf8EWd0b+N57Di6w+TJm3Dle2dq1mJCCf/DdrOwRAN4Ze2B2MKRrHvWcn8kWE4k6YInxRJK0NmGi1zaHwDek6fRlAbhLnbcsYc+SbN+BMreh7xmoeNH4eCN+P2654jTbWvJZj7967JYt38qxSLXU2vQCMKPVUB2C3Ku/c2G0gMXjUVEYQnzS544Ja3kkOg3uNGxh+64xnwZbvNy1JM2X65aA9Nuty3d89CN9ADK+snPWudFqsahLlWBmcgYtrcOxnhO+SxC+j4byp9/lGbqSxVcupML0pbaYIYlC1Dqb1BjUzDXpoj3WofLCdUFxo3J6+LVqmewLRj7/JRKmJDvbh1QEwIxrMFTNdUTldFisuJX
  template:
    metadata:
      name: mattermost-s3
      namespace: mattermost
