---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgCYdbzFJpdOCJHP0TLYgtTs/lAlccPgjht9/i4psQ+iMG+GwxCFsgSXzGkRRM5hZi4GBVXhISIGFbQN8W0AVpGjZeRh03xgEI4zMy8avZUvTDHamAuIchpCgXvnxb0v6C2vhdxbRdqusbyBdKEjJCZtsR4HjXYQMvYNlWUvqz4wg+Ly4L9X37KFkUEQzM6+v64TTaifgs4Am21bVPRsvSGZkYBaDQG/FDBF4ohqGjbMzr4761M699k3Mtb6Da/n0tjJlPCQhalrf2+UfGTynhzlR34f+y35Lov8vQckTpQzsHwgwqdbWR1CfhXFIEnNIURTMEcsFE4J5tgZ/qFZ39+KcyWchPJX4AR/OyXIhelbGesergNZB7P2rp8OSaf5zxvjZD4+c5RjOFgin4xUCG8kApY9IJ1Uok+shB/KNsKL4BwxvnbWAdpx0+kp0RVvKAjLCwfYnS7h7KhqqsUx7pybjB8kAHf8dM56TWDx4gEeGMVbX+9dtGiFMs1VZFs0g8Yz8R09gtdqnZCIUee92QgnlYLuq5UYUub3CwHiBoIxz1ZCwZs0NI7/Wl0i+KUV2C2XwSiotOgfXk3luro+3ALxS8MrJPwAsZzamwFDLzf1OzUtAdAcf8eNAhOAfsYCT2rYt5XnuNdRH+6mT7iubEzVHmgpt272uoxShXdFnRqU2jNUfhEtYtbN8/hyi5MkzhgPDjdnqODILMLNdT0WPyb79SvOADpchOlPC+r9vFB0g7pUl2CanI33FG+APRZKwaU=
    admin-user: AgCqzEQj+XjRnXuknFRaXmih8fdXLe+oo2H4aBSJif0Y/8+iKQlJRiCQaNqhgnYLuc0kQ/gI9IJ8as3kDvHoJbaY/5ImEoqxVe3Adzy85NPsE1uAt8u6BBv3Ti/prmPsjUQTS2gPVYdmf9nrll+o0yUz4X1jzExk3VbrZJBETmtUXeOzhFrpcHxcxqOopS3LwsENG/987M3jkI3gJFajMiHnxT6NkPlfljnhd5Ih2GSoaQdKx4Qvr87BLfNREwiJoxIzmcOXsUj6QiVNo7+TTYfaH5m0tvLz/f6KdvhJEKYJEe8hDviG89y5g/arg52KlhYOKegZ5jDsxYix2c/VO8OUVwV1zkBGLUzzKkAH6A2q50+QS48MJyfIWQs7GpkXYdrXrw+bkw/ay+tB6mTMKyqsU6M/CQjyZRgVpAs4LNTD4EpWb3RsEzLc4aJbQrvkFTohDWdVI9XvFXxtySHXort3x178I1+FgZWJJCqwlWcNDgkhGeSx55OvSElu07nK1jx1TpYDBT5vUiU8/9NKh48AJvo0ovmx8/IHTA1R3WfTHQcuzTw8BiWgHuFDzBfExq5l30vWJH/yv1YhL+XTspw7btE03j8Z3ANMtAd35kiGxZBh6YZCIkeZC4y4TbWBqSImzLQiuvXhcpO+Zwx6p/I2Jtbkkvn8WtkkcxnUhP6hFJmKDTgkHpUa61kRruXez18Uoz/Bog==
  template:
    metadata:
      name: kube-prometheus-stack-grafana
      namespace: prometheus
