---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rocketchat-oidc-client-secret
  namespace: rocketchat
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: ""
  template:
    metadata:
      name: rocketchat-oidc-client-secret
      namespace: rocketchat
