---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windows-secrets
  namespace: windows
spec:
  encryptedData:
    WINDOWS_PASSWORD: AgBIL6URWbWJBue5o1o5w3eWMk7EzhRFeU5TAUalPKmn2kyhFtXODRiu083lSaQrlA0inQ/EhiD4cEBTtfbwBsBE67RRUtWDUJPShDhsqAqcSTy12l/CgypgaHfqIZngOFe5SG2aNKUF4sN+jt7iTH2rlQcjCTkIBylCqpFGxOtNQwHRwESpZwQkXGaNMhL27UZpbS4GIigzBC3qaYateoeOMFVXStFDcSX9Vdq/WwoCnELeeT0W4tvBv8NT1e+52YQWoqtk98yZIZSRlxsL4eMLd9Ig6Dn2FI8cDQpT83nfzURLET368tJ4EiJOqpJhk2Am31LdbsoogsSrvWQ3vB+kh/8Q0bS3CX+KG6UJ+pdyQuAz4bZSEeCf9iaIVuPft539p61KjK04uCKSGRUuPYYoUqdGp8a2OyazAlU16HtLoXkH1oOe0UXX3glkxCr8ebmtRGvvPA8A1Vl5n7QhutNkb4A56z3ssK0rg62vohmIe5YvbNhjUCOZrW94qdZOAlL8Z8YbGqbDkw6HVpeqQ53rKBRKRoNtAq5dN0lxpHdSqwgTfwKb9eCFP9dXY5wEkUEo38sQIsSxb9aaiaMVAl/qrYyuOwLe99aivOxVkAjpdPRUYy7G36ge9C3zgPqvXotK0Z98jCzD7yq022fPsYQxYLj6nIXsk715wDuO4kdVTIrqsUsBFEA2fhnQxGls0mtj7LV2qmYh+BdmvITqHiFo9DwDpg29ZDP16bMJkLdCLgGMBpULTXXWleo+18zupKU=
    WINDOWS_USERNAME: AgBDGq6QHpZjRg3kT+opt/TbctQDiTnyt7XcOcvbrYOASHltvTDuozZlD21v/fx1SkoEHooZ3DBnOmrCqDOHGCBe7EtrTFFkCWntrUIDmXs1C3kD1wjLI/DECJ1kx4Sfkplb4/Ei8Fp3+dy7+OYaEDafzYUpdEh3ngJgma7rQRTh3ANrPrNZorCMRZG+H7plCQypexFOmMBDHQ92MhmAcjl4ekGcpHXz790MCdIbhCzu4Xpodfrx7mjuUTPzSiTFWt9cVx2kTJApeZjbHcnL6e7ryI/fmyenM6qOxXOg5olA7bHNCDmAI8HN2WpHc/ZWBfVBs6KCjlwMfkPLLyc+hpUZrJYpnciRDR3uatX2442Qot77SQzFKFSBWqVaoB4xPQF4z1J78KR+KIsDam0Rj3+Novph5RH48NWOBj4M7wAu9BSkJsPDGbkiMQGdzg8pJMaWBLh2CvNkC93FccI1oJ4/TXjUcqwb2k7vZBDX6tiGwXdIwmhylbsYPKb2XEM4oldp/8Te+Paka+DIZDlFQmno8MTlLmsWarvuDyVXz2chxyMbzekUVcyzYylrGGuwKAAqr4UvUAbqocIXO4ckalCgy52HTc5BYsOSpDur6oASLhWrA3TNbjDRPZWBWHhCXmQtTuhut5EEsXI3ZrafmnwFehUALHBkr4YDFez1I9VIzbHI1iCoaH63ws9X5lVuviG7ytoQBKgu4Q==
  template:
    metadata:
      name: windows-secrets
      namespace: windows
