---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-oidc-client-secret
  namespace: zulip
spec:
  encryptedData:
    SECRET_social_auth_oidc_secret: ""
  template:
    metadata:
      name: zulip-oidc-client-secret
      namespace: zulip
