---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-secret-key
  namespace: zulip
spec:
  encryptedData:
    email-password: ""
    secret-key: AgBn/oYfD38k1hWTXTBKTyGraykh70vgKAmNaioOw20hzGEqbVTBgyzpGBjzTyWMObpu2R7DLyqPP4fR194niYwI4QCy/Asbt/sc/WwUIfKXELw7CUFk5tezMD31kXiobKZHhR/ObWyUvvUvp8rq7oZTc3Ule2hmGLi/jmdihOzrBvg5WlHse7sigdJiAUSeSjwkd3OTucTP6UxhqRt+QRd2SOv/VkfZgvZA1JM1zJlWEGa3qqooBBU3unfrOZg4aNUCRXwhrFa2n+O/uBLP+Wu1G5dYq23YpfAiDZgIqbFvvMdIqnJb0YTZrZTYXKyz3Wkl/EOsUvo3ZVxAoMfGt42UXAWmrwp6aVpUAlAdsY4dmwwzJttiOBjV1bs0TIFgjkusQR5lXpWN++Ih/K8dQ6EWO4MQ/FgXQo02rzkRxZhkTAFXF+rSJ6tYlaOgwb/XWeTlM5wxp7heBsKrs1Q1dw043Sf2aXtlauc/RJTa3CrokKLAcuFYJZJ2X3bB8OUTcSZXv3vCq0GSaF+kDWVS6bndoCtVl1FLXjPsBFVxqFqMmqNSyBEHnSvWADqURDEEeTz8HWpVS094EtA/vdxUwwlQW8AVrZAXddBlKqrNnUHchUjuz8oXH5V3eDMKf5DB8ZE3fVZmU0WDEmZl83olmD/uALo96nX98K9LGwa4xHquQ214EW6JwH+y33F2bEI7xFrPCbL5HN0N1pG85A1+DWxsmb/8Nl2dV+w2vHzAiHRKgjRAMBFC+zPX6Ww5GYS7IaWncguxFveky7qBg83uDR6gHl6Nv1MdKo17Y8UX1pQDz+GPqYKob/qxQJc95f6tRYp4SX15/0+6PQHMj18QeQhk4xaxwDBlVINovspfpQaD7A==
  template:
    metadata:
      name: zulip-secret-key
      namespace: zulip
