---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-pg-user
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBeOE7wLPiqK+eQeXPtIgeyVqUHDailQ5Rgp7p2gmYRvSKz3dEC5qhLeJWGlEAP3/T3Hk5OOZZ8E6A+OhkOHJ2fBLdaGWe8e51xAVxQBT/aRtlzDxH54Zi52i1dheVZ6bACGGEiXzu2mfqrFNdDMJmKIElPKdAJ2mS+dE1umhCz1TJSukgzdcFNZOZ/2qamD/RT6zjHXGCsAkHrBt3GR+s5HrGZy++2HiBQKbJUe1b4jOT+0vpuUqmglIXTqefErB/pq5lByr/DPktJxE2HBZcTEoSFNrcEq8BAnnC69J6rVmUNV/tyZSEmLfmZ/0clpx+lUBGsrkRBszg8cSFAUlENPOEazboXmK/2TaGyfsXKUDNlD5YNdc/L7lPpHaEdoaAzVDkU/UrogTxsQ/aZ5Vflm2+x/Fy3kFdiRz1ur0Rhr67C81gk6EKqSe+U96WP4jV7O4XgyooGSodCJVlF1kJe+77qIkAOtg2UvCvW1Qlj82rnmS3rHjh8Rei2sCe3HpVwTy9/SkjqU07qaoRyjTuKFWqQwky4RWlqQ5XvVxgkS4DIjp9O/f8XDBXdRJxymyYjBmrjFipDyBJEEHu4piX9Ka3VW85RxX/ezPlHeOBt3eRTYaOpZ86xrw76kj6gyj2k3K5rtjTTobpM7FB+JZFDGZhkgWXq/NhxY+2O+HftI9q4A7c4hOPLMnnRafT35K3D8hYNhM1/U8YB6T2sg2ZFjnRFI5kzNqMDCCHfYrp4u2kjOeAPLRFx49xS6kcYrSo=
    username: AgCQ4mAFKgPPGd4/7N3D28Jqrz0FZYkVDCPmBt1RwI5PiAUykttnRRTkzuqiBCdqXOkwXZbLTldG6T1XPzgOIfChmb49ERZwHzc7+urO7YYPuKEOLVuQD9BkR7kpXXMkSnhZP31cNp2rnXMrhnNB4EWVRq2UD/Z5SNb2r7sW/JJYYgNAULibdrkPgsZ3EueaOKFqzy6P6SN+L1F23qCPZMF8z5X+ZYGLuHWcbi3QpDyKAsSAO8y+gDeMWOAFSmo/rwOEp9Mxg6PTb3nWynhgvwI7ptolmJNREdFKUm3y7Xz8UrnHm+7u/YygQsXfpWwnNK9Xmj8tDz5o7rFNNjyEy+LV+Xyip7H235SByWsaBYntrFcqbbp4qP4IcfpWQuL2ntaHtoZKzfIsgewJfPVopN5TEfy6BcGTTIdo7btinLQOfMxKAlbuLKpkJHAjZAxZCbkYM4MtytCkTcBSwwE5GXhVfdHVPOQ0OGv6bCsxHFjQHywN93pERK7UHgBG6BwlK87TsC3eNin8AYAiIOB9Wh/uVh5HvR0tFXi0KOJbt/3kEsnLly5x3hXcbSaf+g28prr4q81fGYkM0nu0kZuECKv5GK3edTRTVvHIgDKsUc0JbMTo5Czx1rGIQZ6p4CoPjB8BlSprp8OkFjvbBCIja7jVzeo+MH3dfD6I0W82EQPGrLNGdpztBxJvJKwUTb62llO3XkVoQ0o1rqM=
  template:
    metadata:
      name: nextcloud-pg-user
      namespace: nextcloud
