---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  encryptedData:
    db-password: AgBfDLya2ClMHpz6i2IGDi+OJ0eZAk6il3J1ZXuXopN7ApbD8OIH/ac5VrQKRCG+X+4n6O9BRXImc92jzBIyPo+9fahHqIEfnzwSkpDSbkiHs5IcpfWy1dByJs1qbCFBHKm4NFnoN2E0/TFm/j5X+1fChS3x0XOT6KdcRlUWLpWzpKFemxMrkLGSM48WOllE5vuCDJgr8EvmPAa2p1qSS6j29/OTA00OK0DECH4RK9ojNPFysU/Gxmon/YpL5o4tRyY6LaslFpvEEXdLtDbCabyoBh6Db0/NaOOHe0nm9vxNIuZuu3a/NRZOIdapIP7zMKr65rrMc9EDCTRO+MslQTK91EN2H52/ThcBjFRahi4vQNQgJD869YrfSplWQJmA6kGifBeeNm0Y51vbqjZdnW/vRisUuaDUs0iQDpTcjx/5yqWet4I3WCQtWrd+wXAXJ2f/PYMqbUnFYLmlR3KiTSLoc5QqKg1C8/715xBsbkemNdT01kaMDp+E1bhSxLS+VZrKpydluyHWH3seI+S7NifwRW57blOpW7ENF0aNSc6aSOxqdXSkFMIgeYT6ngw5vJ0q/ZIf3RBZA+2Lathk4Pot7DMdNgYGgEU9dTb28TEmXs3P6Ohbaajm/8VN8aG1HA5iASIVwSOaaSb+SKmOyzj3w7d0oi/xbqwYfsI+8rwi3jGmasrqMQUuYmVS403peWdPxRPagKL5Oe5qemQwxFBwm4X0DMoAgdVJGyS2SJe9yX4cCAtNg0Lh+CFtlIRzXfM=
    db-username: AgCFM7Xh17Fe8peubS1+tqd4CSFja5euJwax9CjCMJD3xTqvD0yVX0qURfiacAWsYSAT4qqoEkxdHD/U2zK2IUAq+X90lc+Qo7Z3/RpPZBkRA2VtJ4VBhfRDfvCVDA7q/JEAvW7a5hnZ1TlDq1O6Xt34A0fz07C3eQSvGoFyQTEoYjqm+uJyWakw4MFi5T9O5AGgMeF4XnTDdE189ZXUg5ZHzDgIc5c02SSBnvMhlghgzPrGfi9+hwy66zzYPQNIX1yMxgwgzfO1rwWMmsIUsRvaKp6xvyM6NnVXGEMa+CgVKwF9TmN6YNHZw3tlwBs4DcoTjgDNGsCHYFDehUBuRyZNN7rcYixdt+JAFFS+gku60yYfqGXx55Gnk1FEaYDQBUR8YNYm+fd+spmfNb82ofYxpulrf+/CJW7p16wTtvnO5hO4c6Sd770NVLufHWcAnzhK9TK8lz7/NfB+BY+UAMzV3TmCYI25PJkacz3bm9WG4vajnRHCGdsrmmBPx9RQeEj/IQZw07TIuxEALdXc91DKOwLxjKQew3e+Qpv3kS2D135qL2NcAALP1Xf7d0JB1PHmUsunKsmY1QqMUaN8Hq66VJAJ9ouFVwaL40GCCeioO//jzGdrwEtP2kcwbyoa2BrPxKtPp8sI83xXM0o26cSZTEHmh3FZN3qdcUPD5vQlQImZNX1ebo2pECr9YeTRQxWbLput2azoGUE=
  template:
    metadata:
      name: nextcloud-db
      namespace: nextcloud
