---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: nextcloud-s3
  namespace: nextcloud
spec:
  encryptedData:
    accessKey: AgBuCV7kUJw2bp5TCLNmTEop+MO9bc4eYAoDJm8GWwd1olo1bG3B8zrx8T62CKN+0Oww7ASfllkQA4EcZP7TWUKq3/3uqoCqLMRUXozfBdQkrFxhD0G59LVGBOqZXWI/lvSiDuTvKd+lIpKic5jEt5ftgUXmzJxU+IAZrc3ZINOQdQtTMaxsg+xgLa8TW/TghojXm6YJ7+Kwaoox2s0AE5pEbsDEhmbkLfQtg5HQv88rsEnxW0utNIsSBKTX54HXaObT+YrIhPtkdzOFxAYQG++ataS0pvC1Hlypcbhi1ZZlSxW2hQYbmZnYUEF0IvIc0oTl0ybzVuhwvn2nmz8RREx3LTT+KYRupRkKQq6SP7CYDb+GcGIr56lhNWy1JatMMDYr88rVFrCMq0b9OZxdOoCnqDobv/sBOS5hV5kY5hwiprW8Y5y2Qp3Si/LsHP/BqBxeQbpi/3GvjudiyDpxx9B5uhmy1zUit9p1bd6jMm2vbmAmX4IWhOXhuZ9l4YOPokKcIYQJj1kkh9bwJu+Yw58bJUlQaUDiPujL8yP7dIyjnC1AttFXFQkoWu7P/IguZMORbL3ytEq4/og4AKy5dxFnKafT4SKQC/Lbjgs+mN9PgWKMqJ0PzF8mhTD8t2x+w5/F8Orh3yP4BJDCB5obz7UH/MzBaJXpDIVLhdhm6EltITE7fDUuJACO5H7vFzHD7U6bHUlOzIN0s5ISMyTu6Q9mw5QoIQ==
    secretKey: AgBjBUB6oRDizU5AucgzYUZSXzfHVrxkSYuUkSrqvDvhKvT/Q4OJUKoodmMmN1lmtHD7OQ9A0mlxZ4nytTvXdD/o1soSAKdjWz+kJBAapBZNzp+IPb9gI+QsacCqoZMsW0776uSdWnPU+Nz3gaJhKALbYPXIPrmStH9g3aCNFADBLsyb3jfrf55Aw9vsrwroR+kAPHK0EIC3G6Rr5G5KhqlJoAQTICSeN9PXykHpSXbQcDjC2ZFgs0WurM+n6gTWeQ56he1fpHCe22njndcqvAHx62HZchaIyY/BACp2/Voy1UjU9WRuSsjQ0ImLvxWV89G/xBQddbo+BSMq4qwN5+9+VbwVtjKBQle/WK/cp5hxMaIu0FAT0PCtbWvc7C85yjBtzijySpIbA4/3OU/p8HTuilszutABnZm8WhaTcIXuomZYgQBEY9Xi056ytocZip+WGAm8sETU6NjHpEQYb+qK5CtF0650hvvwKe1cPFG54ZwIx0RRbB8bbKT7SY12a/3m/nJ/YLIETpfCJYAQzcGVUxQBezxLaU7jdrdGJxrRku6MtNLcrfQq3NTKBuEK+hcFTd5kdZF077vLA+O1TCPjSUvQVu5FsTdsiBRiE3ye4tKXow2VKWIkVku0KVo9+9KwG8nIbL066IuvMGCyrVUec6iL9duDu9D3i6x4hNQCO2q7AprZMAcZhD4bAv6ORdkci+ajaKA1ICqCpH+TtaiKVuhp92KANVsDwBldxpDI8I//hA96Xlor
  template:
    metadata:
      name: nextcloud-s3
      namespace: nextcloud
