---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-oidc-client-secret
  namespace: nextcloud
spec:
  encryptedData:
    client-secret: ""
  template:
    metadata:
      name: nextcloud-oidc-client-secret
      namespace: nextcloud
