#!/bin/bash
set -euo pipefail

# Build-files ConfigMaps embed a copy of the Dockerfile/.gitlab-ci.yml that the ArgoCD
# directory source EXCLUDES, so the embedded copy is what actually reaches the build.
# Editing only the source file fails silently: ArgoCD stays green and the build trigger
# reads stale content. Fail the commit instead.
# Checked only for the app whose files are STAGED, so an unrelated pre-existing drift
# elsewhere does not block an unrelated commit.
# NB: `|| true` on the grep is required — under `set -o pipefail` a no-match grep exits 1
# and kills the whole script, blocking every commit that touches none of these file types.
STAGED_DIRS=$(git diff --cached --name-only --diff-filter=ACMR \
    | { grep -E '(Dockerfile|\.gitlab-ci\.yml|module\.yaml|install_config\.txt|.*\.sh|build-files-configmap\.yaml)$' || true; } \
    | xargs -r -n1 dirname | sort -u)
for d in $STAGED_DIRS; do
    cm="$d/build-files-configmap.yaml"
    [ -f "$cm" ] || continue
    python3 scripts/environment/checkBuildFilesConfigMapDrift.py "$cm" >/dev/null || {
        python3 scripts/environment/checkBuildFilesConfigMapDrift.py "$cm" || true
        exit 1
    }
done

# Generated-artifact checks, same reasoning as the build-files ConfigMaps above: a source
# edit that does not reach its generated copy fails SILENTLY (ArgoCD green, stale content
# live). Each script's --check is cheap and only runs when a relevant file is staged.
#
#   open-webui tools    : the .py sources are excluded from ArgoCD, so tools-configmap.yaml
#                         is what the installer actually applies.
STAGED_ALL=$(git diff --cached --name-only --diff-filter=ACMR)
run_gen_check() {
    # $1 = script, $2..= path patterns that make it relevant
    local script="$1"; shift
    [ -x "$script" ] || return 0
    local f
    for f in "$@"; do
        if printf '%s\n' "$STAGED_ALL" | grep -qE "$f"; then
            bash "$script" --check || exit 1
            return 0
        fi
    done
}
run_gen_check deployment/argocd-apps/open-webui/sync-tools.sh \
    '^deployment/argocd-apps/ollama-turing/tools/.*\.py$' \
    '^deployment/argocd-apps/open-webui/tools-configmap\.yaml$'

#   project settings    : the direct test for "a manifest drifted from project_settings.ts".
#                         --check writes nothing and names the file that no longer matches.
#                         Watches the settings AND the manifests: an edit to either side can
#                         break the agreement, and a hand-edited anchored value is exactly the
#                         silent no-op the anchors exist to catch.
run_gen_check scripts/environment/updateConfigFromProjectSettings.sh \
    '^project_settings\.ts$' \
    '^deployment/.*\.(yaml|yml|sh|template|disable)$' \
    '^src/provisioning-scripts/.*\.sh$'

# Contract checks — same silent-failure reasoning, but these scripts CHECK by default and
# take no --check flag (there is nothing to generate; a "fix" would have to rewrite the very
# files that define the contract).
#
#   eda tnclient : a ConfigMap cannot cross namespaces, so eda/fileserver carries a verbatim
#                  copy of argocd-infra/truenas's tnclient.py. Drift between them is silent.
#   eda subdirs  : the per-module archive subdir is derived in three unlinked places
#                  (broker.sh restores, each app's CI writes, eda/fileserver creates). If
#                  they disagree, restore finds nothing and every cluster recreate rebuilds
#                  from installer media for HOURS, with no error anywhere. Also asserts
#                  every NFS share: line (4 EDA PVs + the 2 homes consumers) matches
#                  project_settings — none of them carries an anchor.
run_contract_check() {
    local script="$1"; shift
    [ -x "$script" ] || return 0
    local f
    for f in "$@"; do
        if printf '%s\n' "$STAGED_ALL" | grep -qE "$f"; then
            bash "$script" || exit 1
            return 0
        fi
    done
}
run_contract_check deployment/argocd-apps/eda/fileserver/check-tnclient.sh \
    '^deployment/argocd-(apps/eda/fileserver/provision-job|infra/truenas/configure-job)\.yaml$'
#   sealed hook  : truenas-admin-sealed.yaml is GENERATED by truenas/sealSecrets.sh, and
#                  kubeseal emits a bare SealedSecret — so a re-seal silently strips the
#                  PreSync annotations that keep it ahead of the Job consuming it. That
#                  re-opens the bootstrap deadlock (empty namespace, app reports Healthy),
#                  and a stripped file can sit uncommitted until the next recreate.
run_contract_check deployment/argocd-apps/eda/fileserver/check-sealed-hook.sh \
    '^deployment/argocd-apps/eda/fileserver/truenas-admin-sealed\.yaml$' \
    '^deployment/argocd-infra/truenas/sealSecrets\.sh$'
#   eda ci shell : a shell script embedded in YAML is never syntax-checked by anything that
#                  handles YAML, so a broken one ships GREEN and fails at run time, after the
#                  runner has pulled an image and cloned the repo — e.g. an edit that
#                  removes a branch AND the `fi` closing the enclosing `if`, across several
#                  apps at once.
#                  Covers remote-desktop/ci-base.yml too: it is MIRRORED into GitLab as
#                  .gitlab-ci.yml and runs on the same [eda] runner, so it fails the same
#                  way — but it lives outside eda/ and under a different name, so the glob
#                  above would silently skip it.
run_contract_check deployment/argocd-apps/eda/fileserver/check-ci-shell.sh \
    '^deployment/argocd-apps/(eda/)?[^/]+/\.gitlab-ci\.yml$' \
    '^deployment/argocd-apps/remote-desktop/ci-base\.yml$'
#   image invariants : the archive's cache key is IMAGE_TAG and the gate that consults it
#                  needs its CA file written FIRST. Every way these break is silent — CI
#                  succeeds and merely rebuilds from installer media for hours, or serves a
#                  different image under a tag believed good. See the script's header for
#                  the three commits that shipped exactly these slips.
run_contract_check deployment/argocd-apps/remote-desktop/check-image-invariants.sh \
    '^deployment/argocd-apps/(eda/[^/]+|[^/]+)/\.gitlab-ci\.yml$' \
    '^deployment/argocd-apps/remote-desktop/(ci-base\.yml|Dockerfile\.base|desktop-gvisor\.yaml)$' \
    '^deployment/argocd-apps/remote-desktop/(broker|module-cli|module-podman)\.sh$' \
    '^deployment/argocd-apps/remote-desktop-bender/desktop-bender\.yaml$' \
    '^deployment/argocd-apps/app-of-apps/gitlab-runner-eda-run\.yaml$' \
    '^deployment/argocd-apps/hermes/statefulset\.yaml$' \
    '^deployment/argocd-apps/(eda/[^/]+|[^/]+)/build-files-configmap\.yaml$'
#   ci artifacts : `artifacts:` looks like the obvious way to move a build output between
#                  jobs, and it is the expensive one here. The runner PUTs to the API and
#                  WORKHORSE performs the object-storage write — Workhorse is in the cloud
#                  and the artifacts bucket is on the appliance, so a lab-built 30 GB output
#                  goes lab->cloud at 4.9 MB/s and back down at 20 MB/s to land 200 m from
#                  where it was built. Nothing uses `artifacts:` today; this keeps that true
#                  by decision rather than by luck.
#   truenas include: the truenas app applies an ALLOW-LIST of filenames, so a new manifest
#                  there is silently ignored while the app reports Synced and Healthy. That
#                  cost a three-hour GitLab outage on the ecc193 recreate: s3-app-job.yaml
#                  was not in the list, so the CA it publishes never appeared and every
#                  GitLab pod hung on the custom-ca-certificates mount.
#   reseal       : a seal script's output lives in its *-sealed.yaml files and nothing
#                  regenerates them for you. The running cluster keeps working from the OLD
#                  sealed values, so editing the generator without re-running it only breaks
#                  on the NEXT RECREATE. That happened twice on 2026-09-02: image-registry
#                  deployed an htpasswd with neither of its two new accounts, and the
#                  container registry crash-looped on a bucket the same change had removed.
#                  Comment-only edits are exempt.
run_contract_check deployment/check-reseal.sh \
    '^deployment/.*/(sealSecrets|sealToken|sealRunnerToken)\.sh$'
#   seal coverage: an app missing from its area's sealAllSecrets.sh is not skipped visibly —
#                  the run prints "All secrets sealed" and exits 0, and the cluster keeps
#                  working from sealed values already in git. It surfaces on the next
#                  RECREATE as a pod stuck on a Secret nobody generated (hermes sat in
#                  Init:CreateContainerConfigError for 2+ days that way). A `run <app>` whose
#                  directory was renamed is worse: the area run aborts there, so every app
#                  after it in the list seals nothing either. The list stays hand-ordered
#                  because the order is load-bearing (authentik first, vllm->litellm->...).
run_contract_check deployment/check-seal-coverage.sh \
    '^deployment/(argocd-infra|argocd-apps)/sealAllSecrets\.sh$' \
    '^deployment/.*/sealSecrets\.sh$'
run_contract_check deployment/argocd-infra/truenas/check-include-list.sh \
    '^deployment/argocd-infra/truenas/.*\.yaml$' \
    '^deployment/argocd-infra/app-of-apps/wave16-truenas\.yaml$'
run_contract_check deployment/argocd-apps/gitlab/check-ci-artifacts.sh \
    '^deployment/argocd-apps/(eda/[^/]+|[^/]+)/\.gitlab-ci\.yml$' \
    '^deployment/argocd-apps/remote-desktop/ci-base\.yml$' \
    '^deployment/argocd-apps/(eda/[^/]+|[^/]+)/build-files-configmap\.yaml$'
run_contract_check deployment/argocd-apps/eda/fileserver/check-subdirs.sh \
    '^deployment/argocd-apps/eda/fileserver/provision-job\.yaml$' \
    '^deployment/argocd-apps/remote-desktop/broker\.sh$' \
    '^deployment/argocd-apps/eda/[^/]+/\.gitlab-ci\.yml$' \
    '^deployment/argocd-apps/(gitlab-runner-eda|remote-desktop|remote-desktop-bender|image-registry|eda-pcb-agent|hermes)/.*-pv\.yaml$' \
    '^deployment/argocd-apps/eda/fileserver/.*-pv\.yaml$' \
    '^deployment/argocd-infra/csi-driver-nfs/storageclass\.yaml$' \
    '^project_settings\.ts$'
# The `module load` fragment is duplicated per consumer (it is a pod-spec fragment, not a
# resource — see module-runtime/README.md for why a chart cannot share it), so this is what
# stops the copies drifting. Watches the consumers AND the contract itself.
# The pipeline config is embedded in a ConfigMap (the PreSync hook seeds it into GitLab from
# there), so the copy under ci/ and the embedded one must not drift.
# ⚠ The CI job body is one single-quoted `runuser ... bash -lc '...'` argument. An
# apostrophe inside it — a possessive in a COMMENT is enough — closes the string and the
# rest runs as root in the outer shell, with no error. Cost job 25.
run_contract_check deployment/argocd-apps/osxcar-sdv-switch/check-ci-quoting.sh \
    '^deployment/argocd-apps/osxcar-sdv-switch/ci/osxcar-sdv-switch\.yml$'
run_contract_check deployment/argocd-apps/osxcar-sdv-switch/sync-ci-config.sh \
    '^deployment/argocd-apps/osxcar-sdv-switch/ci/.*\.yml$' \
    '^deployment/argocd-apps/osxcar-sdv-switch/ci-config-configmap\.yaml$'
# ⚠ The runner and module-podman.sh are watched too: the check asserts that BOTH consumers
# name the same per-node podman graphroot, and that the pull lock is taken inside it. A path
# that drifts costs a needless 42.8 GB re-pull and nothing else complains.
# ⚠ The module LAUNCHER is generated by a python f-string inside module-cli.sh, so the text
# that actually runs is never reviewed directly. Two regressions shipped in one afternoon
# (an executed comment in r56, broken line-continuations in r57), both invisible in the
# source and both caught by one `bash -n` of the generated output.
run_contract_check deployment/argocd-apps/remote-desktop/check-module-shim.sh \
    '^deployment/argocd-apps/remote-desktop/module-cli\.sh$'
run_contract_check deployment/argocd-apps/module-runtime/check-module-runtime.sh \
    '^deployment/argocd-apps/remote-desktop/desktop-gvisor\.yaml$' \
    '^deployment/argocd-apps/remote-desktop-bender/desktop-bender\.yaml$' \
    '^deployment/argocd-apps/remote-desktop/module-podman\.sh$' \
    '^deployment/argocd-apps/app-of-apps/gitlab-runner-eda-run\.yaml$' \
    '^deployment/argocd-apps/module-runtime/check-module-runtime\.sh$'
#   startup drift: the two desktops run the SAME desktop-startup.sh from two ConfigMaps (a
#                  ConfigMap cannot cross namespaces). A fix applied to one and not the other
#                  is invisible until a user cannot log in to the one that was missed, and
#                  the symptom — a 2/2 Running pod refusing every AD credential — reads as an
#                  sssd fault rather than a stale file.
run_contract_check deployment/argocd-apps/remote-desktop-bender/check-startup-drift.sh \
    '^deployment/argocd-apps/(remote-desktop|remote-desktop-bender)/startup-configmap\.yaml$' \
    '^deployment/argocd-apps/hermes/desktop-startup-configmap\.yaml$' \
    '^deployment/argocd-apps/remote-desktop-bender/check-startup-drift\.sh$'

#   hardcoded ip : `make check` runs checkHardcodedIps.py, but nothing ran it at commit time,
#                  and it only scans deployment/ + src/provisioning-scripts — i.e. exactly the
#                  files whose commits used to skip every check here (the TS block below is
#                  TypeScript-only). So a YAML or shell commit could leave `make check` red for
#                  whoever ran it next, with no hint of which change did it.
if printf '%s\n' "$STAGED_ALL" \
    | grep -qE '^(deployment/.*\.(yaml|yml|sh)|src/provisioning-scripts/.*\.sh)$'; then
    python3 scripts/environment/checkHardcodedIps.py || exit 1
    # domain anchor : same contract, other half. An unanchored cluster hostname keeps working
    #                 until the subdomain changes, then collapses to the bare apex with no way
    #                 back (only the anchor marks a hostname as the cluster's).
    python3 scripts/environment/checkDomainAnchors.py || exit 1
    python3 scripts/environment/checkSiteAnchors.py || exit 1
    # rwo strategy : `strategy` is optional and defaults to RollingUpdate, so the DEADLOCKING
    #                shape is the one you get by writing nothing. A Deployment on a RWO volume
    #                ships green for months and detonates on an ordinary image bump, when the
    #                replacement pod lands on another node and blocks on FailedAttachVolume
    #                while the old pod waits for it — no timeout breaks it. Measured
    #                2026-09-04 on open-webui v0.11.1 -> v0.11.3.
    python3 scripts/environment/checkRwoRolloutStrategy.py || exit 1
    # dns egress  : a NetworkPolicy allowing port 53 only to k8s-app=kube-dns drops EVERY
    #               query here. Cilium's LocalRedirectPolicy rewrites the kube-dns ClusterIP
    #               to the node-local-dns pod BEFORE policy is evaluated, and that pod is an
    #               ordinary one (hostNetwork: false is forced by kubeProxyReplacement), so
    #               policy really is enforced against it. The kube-dns-only rule is what
    #               every upstream example writes, and the symptom never mentions DNS — it
    #               reads as an sssd/identity or tailscale/VPN fault. Measured on ecc214
    #               2026-09-17 on both eda-pcb-agent and hermes.
    python3 scripts/environment/checkDnsEgressPeers.py || exit 1
    # ⚠ A CI `script:` entry that parses as a dict (an unquoted scalar containing ": ")
    # fails the pipeline at CONFIG time — before any job runs, so there is no build log to
    # diagnose it from, only a config_error on the pipeline object. Cheap to check, and
    # invisible without it.
    python3 scripts/environment/checkCiScriptStrings.py || exit 1

    # ⚠ A ONE-SHOT `FORCE_REBUILD: "1"` left enabled rebuilds an EDA module image from
    # installer media on EVERY ArgoCD sync (12-30 min, hours for Xilinx) while looking like
    # a normal sync. The EDA module tags are the user-facing module version and cannot be
    # bumped, so the flag is the only way to republish a Dockerfile fix — and its reset is
    # the half that gets forgotten. Enforced rather than documented for that reason.
    python3 scripts/environment/checkForceRebuildReset.py || exit 1
fi

STAGED_TS=$(git diff --cached --name-only --diff-filter=ACMR -- '*.ts')
if [ -z "$STAGED_TS" ]; then
    echo "No staged TypeScript files. Skipping TS pre-commit checks."
    exit 0
fi

echo "Running TS pre-commit checks for:"
echo "$STAGED_TS"
echo "$STAGED_TS" | xargs npx prettier --write
echo "$STAGED_TS" | xargs git add
npx tsc --noEmit 2>&1
