apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-upgrade-plans
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: git@github.com:orga/repo.git
    targetRevision: main
    path: deployment/k3s-upgrade-plans
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
