# ArgoCD Application: hello-world (plain manifests)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:paraXent/infra.git
    targetRevision: main
    path: deployment/hello-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
