---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    secret-key: ""
  template:
    metadata:
      name: searxng-secrets
      namespace: searxng
