---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-s3
  namespace: zulip
spec:
  encryptedData:
    access-key: AgCMUf/jVdTZpqmQ9soyT+9xFFdqgXsKSnP7e41Zqbplth8IlZqo6ADwFZyo7uxMquXmLYQEp7RVVSbwuwcogVBjZRqJTL3cKVkh6D2gqRdQQngr6Baskhzf1vJTCenfrMGjpaX0CAJDnI93fp8BvokLZrcyhDZ9rEDYf1AYc/MOZ5kD25OUjURjgB2g1ThEDDPofOtJEWiAhFqpZOIys/ox2PkYbZCUPGGMGKSzLStj7FWqWz5xS1GFJgaR3/IGTWkFGmvOfC4l/i4OUGlvL0hltp+lb3Av5sNQzaC44aMGnSBunNffbv2ZWiTxpFuhscJKR3o/Aee1zScBzi8QlMSXpHAWijDzgmV8CHfEKxKnjvGU9zuyyNkbrYqjksAaQN67aOagx9TnyR9PwONnhf36p6WVil8xbgP5H+dlftrRZzOcKFxa1uu8J9rMAgKTel1eJ5g5pcHhGqswLy0E9NPa8DnAvdQotk/nylpKh4SCJGlFanoYqXec2eFOA6Ke5z09DxEr4Qq+BSkH/fS/3hQqoZtQBIfLvdUd+Xz469yQdcvphfZLQPv3JyYTsLLugIuYlZTelyPV5AzqI93ZT3dbs99sfe0a1hCB0KqizRQCYCGr4Mz7O9NCU0ySuF+dy2zUCoRE3SELqWWjPDlpIig09c3bWb3bKE0uhb51O1/fYK+Xt4ghZCb+me4RnHIUvTfODOfXlQqmlE+4ic6SrzUfp/xJhQ==
    secret-key: AgCdpo6DLZiYKEEddCVSELlQAkhkZNQINl43hYv20m3NpaT5/kydUxUJZzTe9VpbquyONJmaMRVbzs9ZKX+4naGMfrpV54+j62kmnAnZU9nnsPg2764uFtuBgq2pUS/JK2G8z0CfkYIa0t599Q2AmXWXI5sZesy7voKiOCjDA0vJEgtjvBmnT/HTECoGh8ElhoCVaQ25P6RC99E6Hq4HH4KqZ1SMP0n97w+xF8dPdSDaWaq2+8I2IHAz7Ipf1+XjxC8nrEHKeYemLxf9PDrFjBGChzKygj/oKsQiAmlZr9QyfyNsv7+UQJ4Jvlq2W7RYmsEvxNORB7TlB1x3+c4hCrGjIjQLxkx48kjmdLGkno8UMRPAZ/A8fAJe8h3CiTDfsgcF+xGNPYLAmYyle//J9cJsgGbL2DmROR4bNxFB6Yc2ho+lo9QtXi9eqSZPlZjO2kZBqlOY8jiTYXSjx/erDNbL/rHMQFEt70v0Y85xJ/0gjgzuF45tTGnc1l+kBnfC4DfmZwVfsUyDGTYXs+oWJsBBqFF7AlX8um4jUbMJ0pjetYVS7x78Ghz7JhSRIp+6xfmOwoMsdS1PvD/V+8WVoxqwJ2L3zPr+SUXBgXW0Db+s0C5QKYEij1h2x22yn45EuJtKuRGCHWKhQ9cDq0QIoTJX5hjT9HXJ40azxUMJqql1of2ffesmB1ut4/N92J7s3eG6skd3L9OfnxDkhgRuWPrs3el51dgtaNAf/d8BbvFdCgDXPxHp+uSn
  template:
    metadata:
      name: zulip-s3
      namespace: zulip
