---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zulip-secret-key
  namespace: zulip
spec:
  encryptedData:
    secret-key: AgAEKYkc1PzbE9nIRlWuvOQyqpoYWTmMB9jg/ZjMiKZyAB9c3w0E9xXfnFzj46GU2YUIxpuoM9HtRHs+3T3jfxkshWENnZ8YSEZy1wDOQWjfcZ3lwXwmP5jOK4TdPZFJg3OeQKJ0bNCSkg+cLf0b1ofS55+1L0C6YM8ctJFxKcLvKPUVn7h2gDnXuSu9m4GuD1AVmQopJ0/MUpD4ddLGnP+3dsnGYnmXRAaZ4VQmLspOzjGlBFuetUwzkWWZKJYwFL/0Xnj6GMItdZ6iQpJ1Z0f/RYx+Om3cg/HRYlfbQ2RLyYlqXD3fPPso3p6RqJh4R2Pn4sSzXoinfnJTcoqtWcub5uRdN+QoABKguaC9QBjq5P6QulhjyPlzWZMeZCVs3k191MuQoEYGhAQXfggaUIIw1b2La8KFVrGNomHzI96joe7k+65qIym73HfzqY7HFeQxxP8AQvAI1Tnex4KcesD7zfz1iYwFnwo5RTclqP12Nw/VtbV+PMu076onHuveQMZQEnbHmwV8zjHpfKeEDdIzHK8vq7Pfx8UtoMuI/2+IJhaQOXlJ1Fu7OsQNl+IPf6wmU4t3k7yGLhB2rjDeh1rXmgbQrv0ABFLz/5MHzazKWhySDdJ2TTHSAShAIGk3L24Rz1FqHVq2+pSnus7NFiysfnQwpqztWEqXFc+8EvEiYh195x7D1r9JZ0oxwF0bIJf6H4ucjo8HIrG2RYzSwW1WbxJ4VewahAdoF7GYgygzYcEj5TbM53ebs2aUkcKK7w4zy5j0g00QgBgISvn/o4dL54KVdFuog5jyucKWc/hK3kBKrg67samXD6R8e69We51siC1clObAqXdXvgUJ5gePdS66QVp5TJ1dmzQwQcpAaw==
  template:
    metadata:
      name: zulip-secret-key
      namespace: zulip
