---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd-apps
spec:
  encryptedData:
    oidc.clientSecret: AgBSqvO94iZ0cP6OO9zQMzz7L7FdsPP6Vmvvs55hsMBqYJSp/5gwwDE57mEptgYQ1jSxZURegIa+uN7AFUK3eaBIwWfNJgUmAcSGpbRq4gQo2F6q/1lOn+8hHXZPeqSInI9QgeW/Zlg5kKCjNvm21+Vou7dZWHkhdfqQ+IOcved2O+jx2zhwVaGFUjOdspd+8VCSa7bzFHocXlN0Sc8WWMpT/fQp5n7OhHP76F9UaNwgBDfiaRhBTBJfJZDfCKh/0924PchuV3X+ceHnTlRCEnyTC2ZdBaCZwdtBoxFUp8q65VWxeWtfd74+lAPPwi47wJEvlBdGHcrh28r1jN2u3/EDMSvMF8x27f8aKXF6awiy2E3wZGhhWRpdJ9XIWfiWiIJtCZQN7iGyopWpyMNHdACbGSMjDK0mUKQIsOsiivL1Z86bkQoTMEqcQAeyHg5CWzdxP+5jrpEqlbsR+e9BlLeSnT4yD38iIT8wzwaMtqCy1jYFQ0bRXB3MfxF+j2V+9cSSOV9RYzCSq6z/43MEQJnjUzHXdpmnraZmEHgkyI+vbj5ikitV0g1K7+mVEexO9CQDYafzZ+TN4HldZdhpmKCLlrX/7An0OYdd/z0Cj+/VnSBwVSdz9DUzkD8sz08cullpN6svWojFJsmaX4bM6Xj/yOPsg6o7HwrlMtStDJgwLqszXTds5vafp2E5HVeNI5hwOIIjN7rPPpGiUOz8E6AMHcKvwhyJo8edPM4q6qscs0/zNYXdjgKyqaBKr4pQTzgb0hSeMwemLMBSyasRWT/f
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: "argocd"
      name: argocd-oidc-client-secret
      namespace: argocd-apps
