---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jitsi-oidc-client-secret
  namespace: jitsi
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgBC2/+xFh4RlYlg+G1GKxvN33buBcRfSUcBnB2XV4xssT0udJBENQIlEUf5PnIcyO4AHHopSWunBwpPEDr22A808HRNbEi66eSikQi68PDV81BTiv1AoeaIxuBDZ6K/WWGXFSFxyzndLM3PY62MM1MHrn3KghI+TzEa43meQc2SLCSTW9TfRiALVcKHfoZzNPWI8WQ9m+i/h+NslI/mvvetoK4OUKgKzZG/lcSb3YXXjdx2j41DqaJOUvhQ0ouRpiuHRSdBSkrQYoTp+DnqyFM5wStrrBkvG5kXgjsssXS7wlHnHB7RDzrhJhhODKc49ubBr7hvnMdfZsfJ0GyfhuMxQpwc71711GdMtgj9p5U8TIJBJ4xgakHIHs8TLRD2rBPgTKpq3i0/IByUBG5yT4tZ0dZz0Hcu5dZl/QaQb4MTcyfpb0oO+VK3SUxrsPxuMcvzbszYOogz6fW0IrUl5bSBEsG+KT7bxpz4TSezp7//hnoBee3yFC6PVJEtnjRmqOOwc8eFLj1F5xrVOCEslpiROeJ96L71SXpHoCNPsewcew9/O/WKY0TezVwTDv0I99twMQ5VQtIKyYyc4EW6Lc6I+WDi77qMx/LFoiUA64WToDkTxRPEn49kppHsj9hJaCoJNlNxLNcsScQyNdS06lZA+PulFaLUpU9+W1kWGgEuSTyBoOAjRgTItBUjOJuqcHR9BpYix0h6EFrA/MJ6EIjoFEzsTs0eMlP21WHh5HyHbYj/aDoVAdLDT2oP+vPoD4/mEukWuskY8NswRtwW3/2t
  template:
    metadata:
      name: jitsi-oidc-client-secret
      namespace: jitsi
