#!/usr/bin/env bash
# hermes-setup — install the Hermes coding agent into the calling user's home and
# authorize it against the LiteLLM gateway. Run once per user; re-run to upgrade.
#
#   /shared/tools/hermes-setup
#
# WHY PER-USER AND NOT THE BASE IMAGE: a base bump takes the whole desktop down for
# the build (strategy: Recreate) — see build-files-configmap.yaml r30. Hermes releases
# often, and an agent upgrade must not be an outage for everyone. A venv under
# ~/.local keeps the agent per-user, so each user upgrades independently, gets their
# own version, and nobody else notices.
#
# WHY THE KEY IS MINTED, NOT SHARED: the in-cluster Hermes presents LiteLLM's MASTER
# key. That is correct for one trusted service and wrong for people — it carries no
# per-user budget, no attribution and no revocation. Instead this mints a VIRTUAL key
# through an OIDC device-code flow, so the master key never leaves the cluster and a
# key can be revoked for one person without touching anyone else.
set -euo pipefail

LITELLM_URL="https://llm.subdomain1.your-domain.tld"        # automatically updated from project-settings:{general.subdomain,general.domain}
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"

die() { echo "ERROR: $*" >&2; exit 1; }
note() { echo "  $*"; }

[ "$(id -u)" -ne 0 ] || die "run as your own user, not root — this installs into \$HOME."

echo "==> Checking prerequisites"
# Hermes needs >=3.11,<3.14 (pyproject.toml requires-python). Pick the newest
# interpreter in that band rather than whatever `python3` happens to be, so a base
# image that later ships 3.14 as default does not silently break the install.
PY=""
for c in python3.13 python3.12 python3.11 python3; do
  command -v "$c" >/dev/null 2>&1 || continue
  "$c" -c 'import sys; sys.exit(0 if (3,11) <= sys.version_info < (3,14) else 1)' 2>/dev/null || continue
  PY="$c"; break
done
[ -n "$PY" ] || die "no Python in [3.11,3.14) found — Hermes cannot be installed here."
note "python: $PY ($("$PY" --version 2>&1))"

# A private venv rather than pipx: one less dependency, and the whole agent lives in
# one directory the user owns and can delete. base-r35 ships python3-pip and
# python3-venv, so `venv` seeds pip itself — no get-pip.py bootstrap needed.
VENV="$HOME/.local/share/hermes-venv"

echo "==> Installing hermes-agent (this takes a few minutes)"
if [ ! -x "$VENV/bin/pip" ]; then
  note "creating $VENV"
  "$PY" -m venv "$VENV" || die "could not create the venv (is python3-venv installed? needs base-r35+)"
fi

# --upgrade makes a re-run an upgrade, which is the documented way to update Hermes.
"$VENV/bin/pip" install --quiet --upgrade hermes-agent || die "pip install hermes-agent failed"

# A launcher on PATH rather than asking the user to type the venv path. Written every
# run so a moved venv self-heals.
mkdir -p "$HOME/.local/bin"
cat > "$HOME/.local/bin/hermes" <<LAUNCHER
#!/bin/sh
# Generated by hermes-setup. Re-run it to update.
exec "$VENV/bin/hermes" "\$@"
LAUNCHER
chmod 0755 "$HOME/.local/bin/hermes"

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) note "NOTE: add \$HOME/.local/bin to your PATH to run 'hermes' directly" ;;
esac

# ---------------------------------------------------------------------------
# Credential. Skipped entirely when a key is already present, so re-running to
# upgrade never re-prompts and never mints a duplicate key.
# ---------------------------------------------------------------------------
mkdir -p "$HERMES_HOME"
chmod 700 "$HERMES_HOME"
ENV_FILE="$HERMES_HOME/.env"

if [ -f "$ENV_FILE" ] && grep -q '^HERMES_LITELLM_KEY=sk-' "$ENV_FILE" 2>/dev/null; then
  echo "==> Existing LiteLLM key found — keeping it"
else
  # ⚠ WHY THIS IS A PASTE AND NOT AN AUTOMATED MINT. The obvious design — authorize
  # over the OIDC device-code flow, then exchange that token for a virtual key — does
  # NOT work on this deployment: LiteLLM gates JWT auth behind a PAID licence and
  # refuses every JWT request with "JWT Auth is an enterprise only feature"
  # (user_api_key_auth.py:1354, measured 2026-08-27). The remaining options were
  # a shared MASTER key (no per-user budget, attribution or revocation) or this.
  #
  # The UI mint is the SAME credential the automated path would have produced: a
  # per-user virtual key with its own budget, expiry and revocation, minted by the
  # user's own SSO session. Only the transport is manual.
  echo "==> Authorize this machine"
  cat <<EOF

    1. Open  ${LITELLM_URL}/ui   (sign in with your usual account)
    2. Go to "Virtual Keys" -> "+ Create New Key"
    3. Copy the key it shows you (starts with sk-)

EOF
  printf "    Paste your key: "
  read -r LLM_KEY
  case "$LLM_KEY" in
    sk-*) ;;
    *) die "that does not look like a LiteLLM key (expected it to start with sk-)" ;;
  esac

  # Verify BEFORE storing, so a mistyped key fails here rather than at first use with
  # an error that looks like a broken agent.
  # ⚠ Distinguish a TLS failure from a bad key. curl writes 000 when it never got an
  # HTTP response at all, and reporting that as "rejected that key" sent a real
  # investigation down the wrong path (2026-08-27: the key was fine; the desktop did
  # not trust the LE staging CA).
  code=$(curl -sS -o /dev/null -w '%{http_code}' "${LITELLM_URL}/v1/models" \
    -H "Authorization: Bearer ${LLM_KEY}" 2>/dev/null || echo 000)
  case "$code" in
    200) ;;
    000) die "could not reach ${LITELLM_URL} at all (TLS or network). Your key was
       not the problem. On letsencrypt-staging the desktop must trust the staging
       CA — desktop-startup.sh installs it; check that it logged
       'LE staging CA added to the system trust store'." ;;
    401|403) die "LiteLLM rejected that key (HTTP $code) — is it a valid, unexpired key?" ;;
    *)   die "unexpected response from LiteLLM (HTTP $code)." ;;
  esac
  note "key verified against ${LITELLM_URL}"

  # 0600 BEFORE the write, not after: between creating a world-readable file and
  # chmod'ing it, the key is readable by every user on this shared desktop.
  ( umask 077; printf 'HERMES_LITELLM_KEY=%s\n' "$LLM_KEY" > "$ENV_FILE" )
  note "key stored in $ENV_FILE (0600)"
fi

echo "==> Verifying"
export PATH="$HOME/.local/bin:$PATH"
"$VENV/bin/hermes" acp --check || die "hermes acp --check failed"

cat <<EOF

Done. To use Hermes as your VSCode coding agent, point its ACP client at:

    command: hermes
    args:    ["acp"]

Re-run this script any time to upgrade Hermes; your key is left untouched.
Scratch space shared with other users: /shared/tmp
EOF
