#!/usr/bin/env bash
# Regenerate shared-tools-configmap.yaml from the scripts next to it.
#
# The ConfigMap is what ArgoCD ships and therefore the real source; the .sh files are
# what humans edit. Run this after editing any of them, and commit BOTH — editing only
# the .sh is a silent no-op.
#
# Unlike the build-files mirror (which carries a HARDCODED file list that has silently
# drifted before — [[build-mirror-cp-gitadd-drift]]), this globs TOOLS_DIR, so a new
# script cannot be forgotten: adding the file is all it takes.
set -euo pipefail
cd "$(dirname "$0")"
OUT=shared-tools-configmap.yaml

{
  cat <<'HEADER'
# GENERATED by sync-shared-tools.sh — DO NOT EDIT BY HAND.
# Edit the .sh files in this directory and re-run that script.
#
# Published to /shared/tools on the fileserver by postsync-shared-tools.yaml, so users
# can run them from any desktop session without a base-image rebuild.
apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-desktop-shared-tools-files
  namespace: remote-desktop
data:
HEADER
  for f in hermes-setup.sh; do
    [ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
    # Published without the .sh suffix: users type `hermes-setup`, not `hermes-setup.sh`.
    echo "  $(basename "$f" .sh): |"
    sed 's/^/    /' "$f"
  done
} > "$OUT"

echo "wrote $OUT"
