import * as pulumi from "@pulumi/pulumi";
import * as command from "@pulumi/command";
import { project_settings } from "../project_settings";

const longhornBucket = project_settings.storage.objectStorage.buckets.find(
    (b) => b.key === "longhornBackup",
)!;
const BACKUP_BUCKET = longhornBucket.name;
const BACKUP_REGION = longhornBucket.location;
const LONGHORN_PORT = 8091;

// Runs during `pulumi up` when restoreClusterFromS3Backup=true.
// Port-forwards the Longhorn API, waits for the backup target, then restores
// every volume that has a backup in S3 but no healthy replicas on the new cluster.
export class LonghornRestoreComponent extends pulumi.ComponentResource {
    constructor(name: string, opts?: pulumi.ComponentResourceOptions) {
        super("edgecloudinfra:index:LonghornRestore", name, {}, opts);

        new command.local.Command(
            "longhorn-restore-volumes",
            {
                create: [
                    `LONGHORN_PORT=${LONGHORN_PORT}`,
                    `BACKUP_BUCKET="${BACKUP_BUCKET}"`,
                    `BACKUP_REGION="${BACKUP_REGION}"`,
                    ``,
                    `cleanup() { [ -n "\${PF_PID:-}" ] && kill "\$PF_PID" 2>/dev/null || true; }`,
                    `trap cleanup EXIT`,
                    ``,
                    `echo "=== Longhorn restore from S3 ==="`,
                    `kubectl port-forward svc/longhorn-frontend -n longhorn-system \\`,
                    `    "\${LONGHORN_PORT}:80" --address=127.0.0.1 &>/tmp/longhorn-restore-pf.log &`,
                    `PF_PID=$!`,
                    ``,
                    `echo "Waiting for Longhorn API (up to 5 min)..."`,
                    `for i in $(seq 1 60); do`,
                    `    if curl -sf "http://localhost:\${LONGHORN_PORT}/v1/volumes" >/dev/null 2>&1; then`,
                    `        echo "  Longhorn API ready."`,
                    `        break`,
                    `    fi`,
                    `    [ "$i" = "60" ] && { echo "ERROR: Longhorn API not ready"; exit 1; }`,
                    `    sleep 5`,
                    `done`,
                    ``,
                    `echo "Waiting for backup target (up to 5 min)..."`,
                    `for i in $(seq 1 60); do`,
                    `    AVAIL=$(curl -sf "http://localhost:\${LONGHORN_PORT}/v1/backuptargets/default" \\`,
                    `        | python3 -c "import sys,json; print(json.load(sys.stdin).get('available',False))" 2>/dev/null || echo "False")`,
                    `    if [ "$AVAIL" = "True" ]; then`,
                    `        echo "  Backup target available."`,
                    `        break`,
                    `    fi`,
                    `    [ "$i" = "60" ] && { echo "ERROR: Backup target not available"; exit 1; }`,
                    `    sleep 5`,
                    `done`,
                    ``,
                    `python3 - "\${LONGHORN_PORT}" "\${BACKUP_BUCKET}" "\${BACKUP_REGION}" << 'PYEOF'`,
                    `import sys, urllib.request, json, time`,
                    ``,
                    `port, bucket, region = sys.argv[1], sys.argv[2], sys.argv[3]`,
                    `base = f"http://localhost:{port}/v1"`,
                    ``,
                    `def api_get(path):`,
                    `    with urllib.request.urlopen(urllib.request.Request(f"{base}{path}"), timeout=30) as r:`,
                    `        return json.load(r)`,
                    ``,
                    `def api_post(path, body):`,
                    `    data = json.dumps(body).encode()`,
                    `    req = urllib.request.Request(f"{base}{path}", data=data,`,
                    `                                  headers={"Content-Type": "application/json"})`,
                    `    with urllib.request.urlopen(req, timeout=60) as r:`,
                    `        return json.load(r)`,
                    ``,
                    `def api_delete(path):`,
                    `    req = urllib.request.Request(f"{base}{path}", method="DELETE")`,
                    `    with urllib.request.urlopen(req, timeout=30) as r:`,
                    `        return r.read()`,
                    ``,
                    `existing = {v["name"]: v for v in api_get("/volumes?limit=200")["data"]}`,
                    `bvols    = api_get("/backupvolumes?limit=200")["data"]`,
                    `print(f"Existing Longhorn volumes: {len(existing)}")`,
                    `print(f"Backup volumes in S3:      {len(bvols)}")`,
                    ``,
                    `if not bvols:`,
                    `    print("No backups found in S3 — bucket is empty. Skipping restore.")`,
                    `    sys.exit(0)`,
                    ``,
                    `restored, skipped, failed = [], [], []`,
                    ``,
                    `for bv in bvols:`,
                    `    vol_name = bv["volumeName"]`,
                    `    last_bk  = bv.get("lastBackupName", "")`,
                    `    vol_size = str(bv.get("size", "0"))`,
                    ``,
                    `    if not last_bk:`,
                    `        print(f"  SKIP  {vol_name}: no backups in S3")`,
                    `        skipped.append(vol_name)`,
                    `        continue`,
                    ``,
                    `    backup_url = (f"s3://{bucket}@{region}/backupstore"`,
                    `                  f"/volumes/{vol_name}/backups/{last_bk}")`,
                    ``,
                    `    if vol_name in existing:`,
                    `        v = existing[vol_name]`,
                    `        running = [r for r in v.get("replicas", []) if r.get("running") and r.get("mode") == "RW"]`,
                    `        if running:`,
                    `            print(f"  SKIP  {vol_name}: {len(running)} healthy replica(s)")`,
                    `            skipped.append(vol_name)`,
                    `            continue`,
                    `        print(f"  DEL   {vol_name}: no healthy replicas")`,
                    `        try:`,
                    `            if v.get("state") == "attached":`,
                    `                api_post(f"/volumes/{vol_name}?action=detach", {"hostId": ""})`,
                    `                time.sleep(5)`,
                    `            api_delete(f"/volumes/{vol_name}")`,
                    `            time.sleep(2)`,
                    `        except Exception as e:`,
                    `            print(f"    WARNING: delete failed: {e}")`,
                    ``,
                    `    print(f"  RESTORE {vol_name}  (backup: {last_bk})")`,
                    `    try:`,
                    `        api_post("/volumes", {`,
                    `            "name":             vol_name,`,
                    `            "fromBackup":       backup_url,`,
                    `            "numberOfReplicas": 2,`,
                    `            "size":             vol_size,`,
                    `        })`,
                    `        restored.append(vol_name)`,
                    `    except urllib.error.HTTPError as e:`,
                    `        msg = e.read().decode()`,
                    `        print(f"    FAIL {e.code}: {msg[:200]}")`,
                    `        failed.append(vol_name)`,
                    ``,
                    `print(f"\\nRestored: {len(restored)}  Skipped: {len(skipped)}  Failed: {len(failed)}")`,
                    `if failed:`,
                    `    print(f"Failed volumes: {failed}")`,
                    `    sys.exit(1)`,
                    ``,
                    `if not restored:`,
                    `    print("Nothing to restore — all volumes already healthy.")`,
                    `    sys.exit(0)`,
                    ``,
                    `print("\\nWaiting for volumes to finish restoring (up to 30 min)...")`,
                    `deadline = time.time() + 1800`,
                    `pending  = set(restored)`,
                    `while pending and time.time() < deadline:`,
                    `    still = set()`,
                    `    for v in api_get("/volumes?limit=200")["data"]:`,
                    `        if v["name"] not in pending:`,
                    `            continue`,
                    `        restoring = any(`,
                    `            rs.get("isRestoring") or`,
                    `            (rs.get("progress", 100) < 100 and rs.get("state") not in ("", "complete"))`,
                    `            for rs in v.get("restoreStatus", [])`,
                    `        )`,
                    `        if restoring or v.get("state") == "restoring":`,
                    `            still.add(v["name"])`,
                    `        else:`,
                    `            print(f"  DONE  {v['name']}  state={v['state']}  robustness={v.get('robustness','?')}")`,
                    `    if still:`,
                    `        print(f"  ... {len(still)} volume(s) still restoring")`,
                    `        time.sleep(15)`,
                    `    pending = still`,
                    ``,
                    `if pending:`,
                    `    print(f"WARNING: {len(pending)} volume(s) did not finish in 30 min: {pending}")`,
                    `else:`,
                    `    print("\\nAll volumes restored successfully.")`,
                    `PYEOF`,
                ].join("\n"),
                delete: "true",
            },
            { parent: this, customTimeouts: { create: "40m" } },
        );

        this.registerOutputs({});
    }
}
