---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rocketchat-oidc-client-secret
  namespace: rocketchat
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgBnxBph22b4uE5ednD/uiJYtlHrDsWXdBStogg6rhv1RoKF10pzWnWhmpBKzZmbp+aWuaHiG0KHXb1REtH7lKlhpajbnQra+GW4RK+O0n3PtoDyEatwUDfe89y5Nrmc25yl/6MGM7xC0wuvNk6ktRu0wnOBPLOjmBEfhYG/3XySbgrEZpnCSJNkNrqlzwYm31Aww0Ry8DUvsKX0xKvpNG6yRso5th8gVv7mmWvZjHElrA30FnkMhYGQ203MBlsWOb1lIC/X5sjw++zPqk/a7FOljk10YVDfkI46EPj+3uP9+YUphnFQp7jHgHV8tMgaZuu+UVbcSEKAQWngjubqinskDmCwcMSf7Cq2TIPwSkUQeh4R902M47JL7Qle+nQIhNKNgGviDjDcL3CrpzAgJVLwo8FfPaCgFx0MLpSswvoUBnq07ccJDtJ256dFQyWEGrCp4YlMNmtpy9CgAFzKI/AIxonCs7hcxAuTQepoRngdvahwfQ62udsA9Ki3V6awtB7EwP7zLD7C4jtKLM3TztyJtYJxS3Zu/fPYCdFuS5+gEl1jJilvCUDnsF1S9lzLCci48siOcBSB1JInQjet6H7EbKwSiGxXsq/N8M1gCiyiZ/UvSgJlNG2pqaSceERwNHhXhNnue3Emuivq2ZswagblpXB6rG3eil+L1p1eNvrPwNMTkawxGY9HcgsKWkvN4U/+LuygxxDdfSI5nVqRIx7LFz6aUgZS4O26AoetcHqAS1GCESxQ56SDKjpPmQBI8Y23WRhYcRHvMkBL9dVCCB2l
  template:
    metadata:
      name: rocketchat-oidc-client-secret
      namespace: rocketchat
