---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.clientSecret: AgBgisLEWSTNyn12xxY+zFmhhEUpt0d+sRU/RD+92gKdagf9mIzqKhYI+iEEvx52QaT7TLTeJC0nlJAUJ3LNaG1uK2LKmXgo0+8IduML/4iRlOIIzhVgX7Sk0dqsPin4uZ3Cybmja7I6dOVg3mMc8wn1dNZrc0zBKplSDQD4GOQp937cpJbx/L0/So92IP3Boob1vEZ9oy4a/T5D3kSmYKcATpY9hrrkcl7BKAnbW4kQaC4g6SKRkahItgByIjiZXsbA9Gp1jzgd9GYXT2v/g91+XMGoGzHF21dPcKtcTyb+rY1rAKNoTdfIFpWW7THS37lEtumMN1zFvLIUQ7IFNq7tVnKCpQcuBgMB+xPLWmIzZxxmMtXq7QG/IbCuhIaIxYCARjaXfzr1jmJNvOAKhP5PH8m3PwaynynmVhbMcARwK1+bL2zy9X2TGPU/seYm5O6PATv77HoFAo7b3RQUBHuHfHaCZgZOp3c0VjTS7wd0X5rX2o3E3WyWWUn1X+5Whd8BiBUJ6s1Dpr7pbaAs7uRoPDE9MNmIw3myKQ4shzwOsVfH0Z3ut0SDjtxkIQAJAw4IGmcHlVj1opUQC11K/DAD7oVHSEsjAOgcUbGoW6O7zXKHFHaPfL15dBnENHmaR5/8rWypG0HEheMECCGBkre5lLwHN7ZuizziRqC5OcqaxYhiP012CoRV3aQu4S8OwZCnU5BW9QBjzvjv91CHLCO0ogT1nYh4VsJbihmyg4ekOZJEO1WD00ZsS93ARGM/Gq4IH4sGmc3lsGnh7ETNgaOg
  template:
    metadata:
      name: argocd-oidc-client-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
