---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: xwiki-db
  namespace: xwiki
spec:
  encryptedData:
    db-password: AgBLSfVPxnf0ylkA/XreB6S9Owdld3XJxxXuBVEW0Xit+asv+m9xTLUZU2wC3h7BYcNRwDfYIS9a5yXQ47McYz5ur/TMLjHLiosBgyeTVkRThmWN3zgm6/XQ+Ee341oT4q4bJH5fjlTz5hJ1Dwfymkf9KS1mU9ZkcFceD5BKbq/uANuaR5xQ30ckijRdJuZbDEVa+yIWSnYFrsklZUT2ataPwGmBnaJk+Kr2vF0RbTVXOHlQEhmYQWKK+BpE0uDHSC/5rGTd7yVEMImhNxz2bzrQHybN5QnqhOk3vin9yR1FETzLYN794Ab36j6uEgdvQR3LAjW3AK9Mmlhwz3RV9l8I24ItuxJdTmydZtFy/2oRurtaUJaUjKB29FOCs86LzBXS8DDIvu+UCr5TR7Y+pnmzIGUMqPHCGqmNOi5VmpYO4MPivMT9xTqKk03rDL+RC4B4MJTZHYgnKljBdzXbPlekAUr9sx+KFxmPHdeKMikzRCHvmGrFmLl2RgLFVRSAG1VH/WXIK8yixhYL0g5lKOu2wTfJgVRL2rL0Mhqm9LHQJkC3XzJK9F+DxjkqjkoStO/428NXHjsCf63az2+oPNx3JWC3vq6z/w0tVwoZmZYbyzkoQu5VioaZDtjBoKsQGzm2fG9CvT/zm7eBF0zAPAi7zG1gO1Zt+ANZV71hPvgAh0ezN+n+Hyt4hPqdFvpMshzlHgFnE2+YVw2I/lylsBktUXF7MaTjmadGKCEbtXUzrrBJmkZraAQ4+Qu9B4/EZpo=
    superadmin-password: AgAXWJYvdUh10vdB5u2kclsr1ua6pbnRStcnLEFugTuQfucfuF9xS1FE+w+b1m4NSI0Bu7C51qAjCLoCVql6niwOsi5Othg7MHaaHZAXqCv9FHOTU8bXa6qGpOt7Wh96ACtqdEI+aac5Zt7MyYeC6O3tg3b3yz0Zax51b35irRqlnawRfF3Asro4Ej/9AO0lQZ7mNuI3RPXclKl4GLLzTajzixmRmb5ip0bgakmwN4miXdhKVaF9YFMBNmeFTNlwqVdsi9/+/NvJJaRIdoAfI15HlPh15bguXu1wWJTsv1AgPkqosO7jgIrx9FezGVHlrzOgKWFnxWrb0T/RobAAYMUKVrm4p8fIHALk+4FmGhKFIR77ztKn/BEvEx9pG1qIJU1X6GRhRG4xZ01HIJIAsrOK7ekfyuHd/6i250rASNHbVc4RL0BCHi2j578mTjS/M7hJWOFDMpn9AguxJwdOAXB3Hnlb+pqnf+PuVOKlUX+wpYtXR59hQULdyqj2Y8Jd7Tq7HoFTboYrsqbFJEjehBDfQx2LViVX4adtUPNL7WTFYgB64DOGUeMjSaO7vDDtL3pSs8KbZLsfTueu8US7znTV+mQNdYkFoxrCzdxm4Y8r7IQshihTcPSIlf+dMu7WwN6oszvnJ2AKG/TXkXfUveLeX0qMULlD7eOGeEVIFRDsE3hCBHQVOVVX1R49He9a0Is2Tf9mnLSL6JMTsqW0JNWHAULfEbfQpIYdcLupN1VER8x/UEIDpf5tCGnQxmKTCKI=
  template:
    metadata:
      name: xwiki-db
      namespace: xwiki
