---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-secret
  namespace: loki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBtZ0LWW8k7Q1OQU0FdmdOD+2lTmGnGZ5V2Aifh88eBk+fLyIT2snOTTLq59Yx0CJGZwNr4M86chcctHHjhCfA6j+C+fnHkSPlIZIhibDfoii6xqoukKaQl9wSwRn9ZrQaAsmAx7ItjdZxzDG0wfQZZYoK7Z/Y1nkPJgNFwSw2vM2bkqkNF60UDKxP2fDWHAyl1V4dk9lzOA4oO2mDbBuS9soCDcNH8c4HpXIIGQ9XEDR2uPBSbeear2ddCTvOG/H06jypN0JlkkVHxueoMCHllifbwW//FDN/v40xi7KJGAIips49YVxfsBTqZtpOwLOCVoL1yLZEVptv0sLqAcVIRSxrUvhDJrZvabq1Iz7l1RjwDVXia6XNFYrxU43qMcd9PwiRXQsl/+MyrJN+CyvubacN1wot4Z84A1uIACxQ/eMwSMkkLWwopizz6c1UjGrri+PyTH9RrPjb+fpJOJYDXIJ+uBZMq9Abm9+WQWt+D4OTALe8lXkOlqU3jUliOXFFQoxqGBeNOZdk8Q417JA37SaWp6ZcQtgIjgASOKeuPBDoKJACw+f4xwrDAFi/9Y8OuQGMeS4LR/CiyWwc3Ec4DMLlK2q2Yk0Y191/urCdRKqRDBfDpV3Rcd/TxecFxTtETn666kBYtvEIpFA3p25Eh4cytdqdz8WzNzRw4Yyzfit4M6asHjI4WAA3nEbCfeUJQWOTd1nDxtCOwcT2VVz/x4CvAOQ==
    SECRET_ACCESS_KEY: AgB2Ga8rrSQ6pNyxYUW5/YWuOIWcIKWGr2nd537O07IsX5vGZ+dLZ2w6Kw+eWXLJMti1ejmXeWutaeFuyDUTCfdoxOkckf1PZHHI70CuI5q1oO8IkHX2XTWm7yM23oHrCNs6M0otDNJ0sTj8uHPcK5WdM2VVoKoZuBuWIIMNVI4VrqMM4MvQbx6leNMDhBEZx+jJP2oCu9P775XJW1LlAwfb0F5MWY1Sgo9iHfftfo2sLOe7ikL3legxEE0JzgfkxPA+6Gwuci57GuIpjVDhex8tVy4akpnNiYSB5YdOW49VI3DIeMSuGfmevX5juOGCS1xDvpYVFo8kCF26sMKknkl0h82XxsEQtStjvN4FNADrri6QIrkjj2BnLYFCg20SX/Pzy3f54a2XdPAXZKNP4Kro/vYrLukui4aVyjtBGlhVnZCkrzPfARycUkmpF0GBrV0WWr4f7d5TouyVtyfUN2G4pUNiJdr/C4iukb2DLjMG5hCBbY/WeUQ/tQEDNtGyZG04sCQBis36DKEsdQpcDNi8L7vPt5tdH9yDv63JnTXQN03wGlVlscf6qlLGhiGWJQMgwpF5G0Rd6NHkTrV2mJ17RN/uCpBVjkfox/5SBW1vKFxXswHZyLkTa/HbgeTfn20PYjjShS6KpxwDV1iMpBk1tzMbuKwcdD+Wireyz49ylHmSnLiukm7i7KVpDWWLneMTcs14w283D2DH/56xNqfV1mCLpknRkzYifwdBszbYP6qEd7IbYRpS
  template:
    metadata:
      name: loki-s3-secret
      namespace: loki
