---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rallly-oidc-client-secret
  namespace: rallly
spec:
  encryptedData:
    client-secret: AgA1fXx0bZwiOciioYhYHmap3ztMYrmQNG3iPETep+E4iPAnWC3CfpHBy92GHAY119tQ+PG6ktk+5id18jYLkw5eZhIu5d7jVTgzbEdeDKPwDmUVoIbJhSxCVhUjpTWV4GkLw3O8N8WzaX/ifwMrRj1us7Tv1/cC80dQVYSdLTaWpw31LGI+xSrY/yJaLxSVuVlKF7+zKLae9o8UKkSH87ajrtBMLm+CmIPQqQTR5LSNyNtUo5SQMpo2FActXZcf2rWKpP+yn4UBRpC/5kq8xASeMrckuPDWiDNd7adzynUv47+/F3fY5tsP2DCeIj/wqN2uZYOKcZwGJEWZy9PeUJidMAiKfcMaSQ9FKMgkWlW/CrLs10zgdwS3ZC5Q1NDBQE52eAULpE6502eCXJSj9wN0rn4DcpdAJ+zxJumEuTEl6orFkVNA7tLqUWJ/C7NjHozShfaLfd/4+QNz3B96AflhyXVBSL8kc7kFjl6hYqYw5hN0ZicyNEIS7LvwM6o2NuRFUNSJFvy/rY9WTk4L3YsAA3a5LVhc3eJyEDwkI7yI+WIQiDF5jIu5umV6GIFpU3wDGXq0dvVdcSFfVeqO7ZAJTrtsRm1zMWxS1NEI0V2GCjqTDd0b+VRIxcSunFr6Cy6GuYGPDfZBDk7Uql/AYtvT+KNCrvKIfdqP6f2CK0hwixrgcsB8bI8fnJRUnVCwKDP46f7GQZk0u1a8YPzC3PPNcvBsyXoeZmxp+5GBqOeXBt0dqi4IQDdAMHfw0D03NfF50++4DfdVPBXNsCiqoCyX
  template:
    metadata:
      name: rallly-oidc-client-secret
      namespace: rallly
