---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rallly-pg-user
  namespace: rallly
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgCDMJh+YrAyv4nlkHR6w2gJTpOQUefqCQgWJZ9zfzgj4oqWKglC7OKFCh4tNBxHPXiTGi9T9d0sdDXRnqY5MBJapoYpeFEC+5xUb3QTye46knkg5AAfyk+2TSKRxsoynIsEz7y8l4MHhPiazx9MHZOcgoESfEC5bQOH51Vcl0kEscA8PqL1DEqHn/Nx9OjtZi83EL/xHh45NKNvz0X4kCPOtLUHnnYt+KO2hzMrIezoqtkFuok5AyCwjRWZytKEFQPaeBjg9Vm+0NdqJqrPQlYsH44TYXq+Pid6H+Z1ZNpwS32gs4rCkNEej+Clhx8Iq0CZ9wMxwRb3vKIwE0yK2KQa/nisX/JtVeVRp7T8Oliek6UnGrtKZxseX5wykObi0rTMJcPnRb+MUOVbEVskm7fqtjHaOA3N5f+I7wvfhcS5Ry/fSklbrRSW/syES60MrpDs+5Y3Nj0MLfoI38tUKRmSULwTJnE1Ae+vju9mm38XdD3R3/WFl73xF43RV58yAM9bkBOnykfP/FMMq3vt0VOVxLH2zhzoco0A3LHfkneTxADIRD9KimwsY5V1uSf1Mz3AgwtwGvqrys8TdsUh0I7Jq/SbKWyOJJttfASt/vVK0EXVWwBhN9Yo4Xhkcd24NF0HTmmec3w+YMzrB8Dm9ODgAsihINgLaAQLDHIHV3VAcSYylZ4BYOkoRLca0w7tRw1X7AiByDkWLBLYS30O+jsW/CGgqGAd6irnRsvTEJfKGUKGVLLdDgmhCSlIpy9GY4Q=
    username: AgAHjYfs++G/qpozkW6zQYaVqigeY8axqWoKaJhqGYWvGnHnVdbJ+DZ173rihlTN7VCBJzA7R4AFsQ1DnsFCo9Yv+a6qNzRE3EY5Qlaj3Rlb8JA97GX+ozdFbWEK7bbU+TY3mCySgmNJFrdgO9AyXkBFL9brpNWuTiQcCRAXhgpJEZdn1nDSg8C3yA4ZozXfH+Fk1luhRhaBhGEHHre1qVwi1CB+LBG0z/Hjv08mVjQtC4NbaV23peYmfTxCLTytjGrMp/mXvcaMl06SeBEvOnhJ1nagaySeJW7Bl7OWd9o25mWwgy+YWqJA2sZC8myN3rifYN1ewvAQV7lFEe0wqHxPI38c1KUDk9YIwvNBuBdSVTuB2EXz04RriFpZFiDCUnZRDQt5YhUZhYmUqbo7goWjvzno7FIYTaNxoNsY9EifgEF24EzrstAE3Ri0BGawKth9dUKM17hmTcAMt0R/XQLCjbzvp1inPEivipPbPd0pMKjhep+USsy186Dpwb4TBTUclLd8cS0yZfQUm++nxhrYeczmDW9u/jGJ+BouVQgzlOp36PR1iEFaM87SUZvvjaLjg4rxFa6aSkYMe9ig9d8p9Ve3haflJOuTowVWgHtiOKSQPDBnB5cMN6qgF1+qrrv8dRsdJJ9ceWmcgvnM1V8TaxpWw3uQBLCmzlhPf/xDLrtYCDmwMjIOdT1GH9VVVDtt4DZ+77w=
  template:
    metadata:
      name: rallly-pg-user
      namespace: rallly
