---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-registry-cred
  namespace: gitlab-runner
spec:
  encryptedData:
    .dockerconfigjson: AgBXbMLzHrIL1k24M9V6DT7JriAom2DB9aKUW7OaubNJZbG7dRKFEEecMh/qPPC+zhE3SfBDx77WCJIMhc15RGXuZZWA9mzYoWkdYh3BRR+9jEdttKyMmIkTCb6aviTS6VQHkVgInOCtQF6g8Rk/V6Bj1B0mzfkZ0trF2KI/mQBnm6jyuQp2I6AhWbkB7p5cFAEkhzgk4xNykC//Zm3Ztoy009x4H8xAiGj++X5AUw6VWmqRxXZGQBkXRWdDaJHZwbVkjat9CPgVTbgWvRzM21QqrD5xsa8OB/eJZExFiF3hx+MAZO9/qWYYHxwrwL15WgAk9l1SuY5nDhm43UVSvAe21kqSxWGcfJGE8/ICxksZm2+b5DX3zfXWweRmXCdbucibGOI4YAoElb2OiXSbZu8Fy1hPCC/Bjud9AE6aEEJ8JTzcK0AZ1q4lBjAbWFLnQtJJ7Y5ifkGTokaCiEwTGv4hrOXolvKeGw6AC36P2zzmxAE6agn1YBp7vteM5l89VrAeKgSt3c+BBeEAi9kCXu+TQBognkbl1k2eG9nLa8Jb35H54K9RCIadx0RZN1pauRbmIyhBCYVBsOuQudevapVT1Onyjx4bRBFE2OXAvgGbWaiTNjJfd0QkjjzWFhTjVejmrATZZeePfHcFxJLWO0JdzF1uvBEJn65SpVzDfTlObug2LwHbHlzIKMsV79uTkpX2tUVU1VYHNU6myguS6qnT8V4EEu2eglXgOnyTcYhfiMl0FdX7JSojM3W34CvHyEjj/LOf1nooDzYoERrWD00i1rkK7DlUq7UQlGc+7VAZsUt7w1S7RhfBfqovbdy2Ob60wJnBfDv1ZoqCobtA1uxOosF6Tex3n+DNx5VQa6h5K06EaHyYKSDbkh9VoKXRaRCV6jLB5oz2EWH3742/f2AZ+lrxiFh5PuLeOIiAvgwybNP5dtOl7BgAD02O39T0ROcMS16k8OPjLXQeIAR3kYcnOtaJQzmVLlXwLy0C0BybvJunLUZaeWaUsGjM+HZOsUnRiOpmU5uqsHC19odEgoSQQITesFaDvCRHOSo3JBT2tJqwv8dLjuJdqMHg8AU=
  template:
    metadata:
      name: image-registry-cred
      namespace: gitlab-runner
    type: kubernetes.io/dockerconfigjson
