---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-registry-cred-node
  namespace: remote-desktop
spec:
  encryptedData:
    .dockerconfigjson: AgBuBugBB6i5Dz1o8yNYEjfqw7KYtdP3+iE6XR6JMxaMf2DJ4BQAO41I5S57p07yLrNW5suzlkIq7okOVkwM7zMzN8vHNVCa8S0T68gIuBDBx3pTacD7OMClZINf1FRl8QJkeHVkAhpcCXmiUn3neMv1KCsxJf66JlUf8L2I1wNg+x/xOBKxuanbV2yJVYFSfgsR3eX/XHAg9WM9Qd8io0lnzunAKPNBMNRTbcDG3GSeikQgjBpQsvLlIFONVH8yCcEaOQzPAwP9AbaWOTDdx9PzV31sgMYztsqxmjlG5Q/nUjOXUGGk3u9EyOII/PjSAkE5dRBKCJjNx56rLfEfjLd2b/loP2Vdxrqxn6dxmnp1AuxMIeoVRBlVWm5uVc0TFZkmw5S8qxYCXCNBbhiD9t1Hz060H7qZ7G+zYztzEy4k7xQxNSRDPfRGdGti0K82vXAJnrtKl00WyDayLQGKm0zLVBWKpcxVpGeoXwiRB5HUQhefEGw1D5N1F+ZIJaSckTaEPzngbzxXF9FGbuDLWOZD7qKg8i9CzdK8lBJzpcBg7BWMeg2bH+YCCuTqooqZHEi0FHIcHn76cHOrPAwvtxm1wAkr+gX5FlEKhzFywlzOAPMIogP0EUvVUdQwq48+YufL+YiDl8y8CFZw+gG/ySowgGMG0mrzXaMNhXiLKHmGQOPfecuNUJ5C2q06H4u98pheeXywK5CPtTsi+Br00RZoUelFpYrvw1B9qjupB6PYxYdcgsJJ+lA7tTAuPmeaWvA2KYzC40cE5FD1zigb9jaDwIVylHdJlSuq09GvRTWq7GkqFP8z4g9dNQ3ioAqqyRb23NeG/OujxWJ0Hc5JQZF4vd6pQ+KhLOLDvWYTqSwOlzm2V8Q0ALLZzbq9YLsxfeil4VasyA4nxQHmXWuRFeoiP0zNmYYwhNwfhWO0f9C4PZczqN27ChSKkyz2LUcG/A91872jhpyuTk4MvUpwhsgmEh8y5jfVXSGosw1JGXuUz1ZAzFOJv58RcLcbXbnk3dY4u2J2aJLJGg==
  template:
    metadata:
      name: image-registry-cred-node
      namespace: remote-desktop
    type: kubernetes.io/dockerconfigjson
