---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-provisioner-token
  namespace: litellm
spec:
  encryptedData:
    token: AgCUT339NvOHxr7JrXgwaG3Q43IiKV2+iQ2LwS8L7iPflU1OT3pwFc4om76wupOaiOwWnpT7/8rTAhuqEGlGxXoCp3Rbjsf8RSlfkJ0a6jaQLqu81lfS+QTLETNv/LTm7BhQVE+RT8SPPuchq+3MdVSz7/Hi9mmYK7CXFXVAfCW4WtSEWW96nWoAGQYd67y0D44ilOrNNrLw4vz/Ah7gJR5KCxlDocNIhxHwkqAA48opEs5kgjCI+GJuVoPpfxCZ9UEyfvG6fva8FYwAPQw0y1zbwG188uI24THIW6A6iIZX5zoyWnr5hRvaYFDVzduEz8BhFcCR5xPVazP1KV8Gw0DN/mNVn0GRnOkuKw55441xdBzb7C2DcrWWT8InleR1UIJUoRXTkp5qe5EBQ6KHVkJWXmKInzS/lF+bIFqXlIarxUejnUzcTMUJ0ZAUx2DkelbRlVAnrP6XlkUy483BlUmQNHynQ6IMKaDm2LKHL6aiH9EXKQ9VVw0R5ekZQBRYFWN3SGSnVbJ8puArBuwyx8D1KrLkDeUumw3Ay6M0WtQsAzTyQ4gHdxfkf2dligR/E6Lno08PoFcqBmh+LBwKseEVBD19EbrObDkD180Se81iD8Qg/llw6bevlc0cQ0snZW6UNU83BnpIEv8UEhmfyfbEGNQ7y26jCzDvPH4yXMzPUr/xaMTFjvD3AWz5jtOhrD/ccI3japIMH4eP9Lqq614b2vXL5urOHHtQZd26Bjx4jKbfzuATnmTE8YoqpniKY4aNByFZ+LvMa+h7YElCM9nbFrcoJWwNnYjCzt8Ke26ZbODuewsj48GZSSHXHfZgOWoQw6kwJQNg0psJe2jG58FeGtORSho9rBA=
  template:
    metadata:
      name: authentik-provisioner-token
      namespace: litellm
