---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-s3-secret
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ACCESS_KEY_ID: ""
    SECRET_ACCESS_KEY: AgBoRrwsB3MNtw/aomhX3PDYahktIbKZbHRusTJXNaxa6yMukmWLJn56pN+C5+DPppA/avCJR9V5VhPvj8f5u7Zqttx4svoYZ1ArWDzcs8goqvdYu7Z/8MsoL9JNtW11kD+eDN8z744G9TM4shWwuBOHf1yndpWjkWWDGN9P4pGefF7HQ+K9M7V6WqFrdtOEHwY23sju2RsrG+LCkgq7n284fj3K0fIHO2Lj9ps1Koyh+A0SIbXs5FSXevvsukDrynPqbBpK01tiMsS221LxJ5FHgaW/ntp2Uow7qpuDjF2Fb18Mp9iuWGtAT7JDwSsaPPF5nh3koaqpfiTJkFcQb4jw1LzWAvL+Gae/C8FDkwi7rHcLSsnJ0fT8tgbSQYE4sgg9TLD2VEYVoETT59WpeQ/OQiOyYPKqsnpzGlo34IDr3skas6Fdt52cWRWdAuK8hV+U3Eu7o3RvVaWbzuZdzgafhSiUy2u+V3MBrCNhZ6FQLhf0ybAk/gGuxXKhuRYhZ52NjmnXHg35FyDEgR8SV+vNY1ZuuE5IqMmECxsuc1Awqc++ths2fpegl1+GmlPn+HMsQHRGSMmHrPcQBT7uO31Jbw7UAsJCQMAtzVnAfry+hqpWNJ+WeqDq2zWs+Sz+IV3kDNSKAZNO9BVKCqeJi2iqXifbVqh/iKU2MbZAXkKjXdn2j9NkKa1mDr9BDz5lcNb/FeH6vneRPLDDQSOAlCr8qq7yzrNC2wEGNwdPVgA5qJSOZgfvMNi0
  template:
    metadata:
      name: litellm-s3-secret
      namespace: litellm
