---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-oidc-client-secret
  namespace: litellm
spec:
  encryptedData:
    client-secret: AgBAzUiuZqQ0zh+YgqvVd00Orw561ce8dXa+m98J5yk6PHaoH3R28B5DdrKD1oq+jiqjpU1oZQ8PRKV3R3dJuQY49mbwRQ4w8Shu4K7A4ccBgyw8bCkuGW9lnx0vYp8puNwsRzajbOpPBf5aQFJ1YuI6QAKRt9/JYTXMBkkRT/EUkkoYCQyPfijHLE5D5NiUb3mI04MdsIHRO0YZWUHVeDmwJl06U6kd1t1xWJ6HSpET7EDgJ5KgDIfJ9LA48a7EMJqbU1AoV/WtlmRTod/vvcT9DTz9lDol23HLfb4UgeTfu/LvCRd2jGCyGQ3zCy9RTBgbr3aOLBc7yst6whD73QpLYoMwJp8V5LPM23v8cmj/jpGB1xrhw4RlWJuM0JAPZ+kuGNvkEXtYU3ReaE88RjVU+SzMO1yrN43vEfTaEqB49v9gj7NLxQx05oMEyaPsaEQrnYlfZqK4gSgLA6CkR/pgsATEyPXBm8b3nAD3X+jCcjeBk+eK+jdzpteZ8A7L0tD5bqnHpltiQgWg0LP0EwSSGqxn1LKDAY/UZ2NMCZZDqLuTPfM4xbYRaEoEUbixel7lUKowVM74cgxFvgXRSF/IIsC4cmrC9vSN3G7kDz1AVZo8/DYO+3oDYhIkJZoQGQyQi9cU50cti1NfyZomR+JTJN4u0bhAVtVVoAky+0NpB3brYpHEK92bYZlNr5hV+1B9/pU+6S9mCEQZGWazltIl+zVGCQ38SpH3foNLXsYInyrtTosVZKceTrHc9xwsZgIq1CEzr6MqDgZKO3Gs0lfh
  template:
    metadata:
      name: litellm-oidc-client-secret
      namespace: litellm
